export const ANSWER_ALIASES = {
  "lionel messi": ["messi","leo messi","leonel messi","lionel mesi","mesi"],
  "cristiano ronaldo": ["ronaldo","cr7","c ronaldo","cristiano","cristiano ronald","cristiano ronaldo dos santos aveiro"],
  "kylian mbappe": ["mbappe","mbappé","mbape","mbappee","mbappe jr","kylian mbappé"],
  "zinedine zidane": ["zidane","zizou"],
  "diego maradona": ["maradona"],
  "ronaldo": ["r9","ronaldo nazario","ronaldo nazário"],
  "ronaldo nazario": ["ronaldo","r9","ronaldo nazário"],
  "ronaldo nazário": ["ronaldo","r9","ronaldo nazario"],
  "roberto baggio": ["baggio"],
  "mario gotze": ["gotze","götze","mario götze","goetze","mario goetze"],
  "miroslav klose": ["klose"],
  "andres iniesta": ["iniesta","andrés iniesta"],
  "emiliano martinez": ["martinez","emiliano martínez","dibu martinez"],
  "angel di maria": ["di maria","ángel di maría","di maría","di mariaa","angel dimaria"],
  "james rodriguez": ["james","james rodríguez","rodriguez","rodríguez"],
  "thomas muller": ["muller","müller","thomas müller"],
  "geoff hurst": ["hurst"],
  "gerd muller": ["muller","müller","gerd müller"],
  "luka modric": ["modric","modrić","modrich","modrick","luka modrić"],
  "harry kane": ["kane"],
  "neymar": ["neymar jr","neymar junior","neymer","neymar da silva","neymar jr."],
  "zlatan ibrahimovic": ["zlatan","ibrahimovic","ibrahimović","ibrahimovics","ibra","zlatan ibrahimović"],
  "mohamed salah": ["salah","mo salah"],
  "sadio mane": ["mane","mané","sadio mané"],
  "kevin de bruyne": ["de bruyne","kdb","debruyne","de brunye","de bruin","debruyn"],
  "erling haaland": ["haaland","haland","håland","haalandd","erling håland"],
  "robert lewandowski": ["lewandowski","lewandoski","levandowski","levandoski","lewa"],
  "bukayo saka": ["saka","bukayo","bakayo saka","bukayo sacca"],
  "netherlands": ["holland","the netherlands"],
  "united states": ["usa","us","america","united states of america"],
  "south korea": ["korea","republic of korea"],
  "north korea": ["dpr korea"],
  "west germany": ["germany"],
  "czech republic": ["czechia"],
  "ivory coast": ["cote divoire","côte d'ivoire"],
  "bosnia and herzogovina": ["bosnia"],
  "bosnia and herzegovina": ["bosnia"],
  "serbia and montenegro": ["serbia"],
  "soviet union": ["ussr"],
  "saudi arabia": ["saudi"],
  "south africa": ["rsa"],
  "new zealand": ["nz"],
  "united arab emirates": ["uae"],
  "andrew cole": ["andy cole","andrew alexander cole"],
  "andy cole": ["andrew cole","andrew alexander cole"],
  "david beckham": ["beckham","becks","david robert joseph beckham"],
  "wayne rooney": ["rooney","wazza"],
  "steven gerrard": ["gerrard","stevie g"],
  "frank lampard": ["lampard","super frank"],
  "paul scholes": ["scholes","scholesy"],
  "ryan giggs": ["giggs"],
  "roy keane": ["keane"],
  "alan shearer": ["shearer"],
  "michael owen": ["owen"],
  "john terry": ["terry","jt"],
  "rio ferdinand": ["ferdinand","rio"],
  "ashley cole": ["cole"],
  "petr cech": ["cech","čech","petr čech"],
  "didier drogba": ["drogba"],
  "claude makelele": ["makelele","makélélé","claude makélélé"],
  "ngolo kante": ["kante","kanté","n'golo kante","n'golo kanté","ngolo kanté","kannte"],
  "n'golo kante": ["kante","kanté","ngolo kante","n'golo kanté","ngolo kanté","kannte"],
  "riyad mahrez": ["mahrez"],
  "jamie vardy": ["vardy"],
  "harry maguire": ["maguire"],
  "thierry henry": ["henry","titi"],
  "eric cantona": ["cantona","king eric"],
  "dennis bergkamp": ["bergkamp","the non flying dutchman","non flying dutchman"],
  "patrick vieira": ["vieira"],
  "robin van persie": ["van persie","rvp"],
  "ruud van nistelrooy": ["van nistelrooy","rvn","ruud"],
  "virgil van dijk": ["van dijk","vvd"],
  "arjen robben": ["robben"],
  "wesley sneijder": ["sneijder"],
  "rafael van der vaart": ["van der vaart"],
  "edwin van der sar": ["van der sar"],
  "johan cruyff": ["cruyff","cruijff","johan cruijff"],
  "johan neeskens": ["neeskens"],
  "dick nanninga": ["nanninga"],
  "pele": ["pelé","edson arantes do nascimento","the king","o rei"],
  "pelé": ["pele","edson arantes do nascimento","the king","o rei"],
  "ronaldinho": ["ronaldinho gaucho","ronaldinho gaúcho","r10","ronaldo de assis moreira"],
  "ronaldinho gaucho": ["ronaldinho","ronaldinho gaúcho","r10"],
  "kaka": ["kaká","ricardo kaka","ricardo kaká","ricardo izecson dos santos leite"],
  "kaká": ["kaka","ricardo kaka","ricardo kaká","ricardo izecson dos santos leite"],
  "romario": ["romário"],
  "romário": ["romario"],
  "zico": ["arthur antunes coimbra","white pele","white pelé"],
  "garrincha": ["mane garrincha","mané garrincha","manuel francisco dos santos"],
  "mane garrincha": ["garrincha","mané garrincha"],
  "mané garrincha": ["garrincha","mane garrincha"],
  "cafu": ["marcos evangelista de morais"],
  "hulk": ["givanildo vieira de sousa"],
  "deco": ["anderson luis de souza","anderson luís de souza"],
  "bebeto": ["jose roberto gama de oliveira","josé roberto gama de oliveira"],
  "didi": ["waldyr pereira"],
  "vava": ["vavá","edvaldo izidio neto","edvaldo izídio neto"],
  "vavá": ["vava","edvaldo izidio neto","edvaldo izídio neto"],
  "jairzinho": ["jair ventura filho"],
  "rivaldo": ["rivaldo vitor borba ferreira"],
  "adriano": ["adriano imperador","the emperor"],
  "robinho": ["robson de souza"],
  "paolo rossi": ["rossi"],
  "dino zoff": ["zoff"],
  "marco tardelli": ["tardelli"],
  "alessandro altobelli": ["altobelli"],
  "sergio aguero": ["aguero","agüero","kun aguero","kun agüero"],
  "sergio agüero": ["aguero","agüero","kun aguero","kun agüero"],
  "javier mascherano": ["mascherano","el jefecito","jefecito"],
  "juan roman riquelme": ["riquelme","juan román riquelme"],
  "juan román riquelme": ["riquelme","juan roman riquelme"],
  "carlos tevez": ["tevez","el apache","apache"],
  "gonzalo higuain": ["higuain","higuaín","gonzalo higuaín","higuan"],
  "gonzalo higuaín": ["higuain","higuaín","gonzalo higuain","higuan"],
  "lautaro martinez": ["lautaro","martinez","martínez","lautaro martínez","lautarro martinez"],
  "lautaro martínez": ["lautaro","martinez","martínez","lautaro martinez","lautarro martinez"],
  "jose luis brown": ["brown","josé luis brown"],
  "jorge valdano": ["valdano"],
  "jorge burruchaga": ["burruchaga"],
  "diego forlan": ["forlan","forlán","diego forlán","forland"],
  "fernando torres": ["torres","el nino","el niño"],
  "david villa": ["villa"],
  "iker casillas": ["casillas","san iker"],
  "sergio ramos": ["ramos"],
  "xavi": ["xavi hernandez","xavi hernández"],
  "xavi hernandez": ["xavi","xavi hernández"],
  "xavi hernández": ["xavi","xavi hernandez"],
  "cesc fabregas": ["fabregas","fàbregas","cesc fàbregas","fabregass","fabragas"],
  "cesc fàbregas": ["fabregas","fàbregas","cesc fabregas","fabregass","fabragas"],
  "alvaro morata": ["morata","álvaro morata","alvaro moratta","alvaro morrata"],
  "álvaro morata": ["morata","alvaro morata","alvaro moratta","alvaro morrata"],
  "carles puyol": ["puyol"],
  "jordi alba": ["alba"],
  "pedro": ["pedro rodriguez","pedro rodríguez"],
  "franz beckenbauer": ["beckenbauer","der kaiser","kaiser"],
  "bastian schweinsteiger": ["schweinsteiger","basti","schweinstiger","schweinsteigger","schweini"],
  "toni kroos": ["kroos"],
  "mesut ozil": ["ozil","özil","mesut özil","oezil","mesut oezil"],
  "mesut özil": ["ozil","özil","mesut ozil","oezil","mesut oezil"],
  "sami khedira": ["khedira"],
  "mario gomez": ["gomez","gómez","mario gómez"],
  "mario gómez": ["gomez","gómez","mario gomez"],
  "manuel neuer": ["neuer"],
  "oliver kahn": ["kahn"],
  "andreas brehme": ["brehme"],
  "karl-heinz rummenigge": ["rummenigge"],
  "rudi voller": ["voller","völler","rudi völler","voeller","rudi voeller"],
  "rudi völler": ["voller","völler","rudi voller","voeller","rudi voeller"],
  "eusebio": ["eusébio"],
  "eusébio": ["eusebio"],
  "luis figo": ["figo","luís figo"],
  "luís figo": ["figo","luis figo"],
  "ricardo carvalho": ["carvalho"],
  "joao cancelo": ["cancelo","joão cancelo","joao canceloo","jooa cancelo"],
  "joão cancelo": ["cancelo","joao cancelo","joao canceloo","jooa cancelo"],
  "joao felix": ["felix","félix","joão félix","joao félix","joao feliks"],
  "joão félix": ["felix","félix","joao felix","joao feliks"],
  "bruno fernandes": ["bruno","fernandes"],
  "ruben neves": ["neves","rúben neves","ruben nevees","ruben nevis"],
  "rúben neves": ["neves","ruben neves","ruben nevees","ruben nevis"],
  "nani": ["luis nani","luís nani"],
  "michel platini": ["platini"],
  "karim benzema": ["benzema","benzyma","benzima","karim benzemaa"],
  "antoine griezmann": ["griezmann","grizou","griezman","griezmannn","griezmanne","griezeman"],
  "olivier giroud": ["giroud"],
  "lilian thuram": ["thuram"],
  "just fontaine": ["fontaine"],
  "eden hazard": ["hazard"],
  "romelu lukaku": ["lukaku"],
  "thibaut courtois": ["courtois"],
  "vincent kompany": ["kompany"],
  "jan vertonghen": ["vertonghen","verthongen","vertongen","jan vertongen"],
  "toby alderweireld": ["alderweireld","alderweirald","alderweirelt","alderweireldd"],
  "axel witsel": ["witsel"],
  "heung-min son": ["son","son heung-min","sonny","son heung min","heung min son"],
  "son heung-min": ["son","heung-min son","sonny","heung min son","son heung min"],
  "jude bellingham": ["bellingham","jude","bellingam","bellinghem","belingham"],
  "cole palmer": ["palmer","cold palmer"],
  "phil foden": ["foden"],
  "mason mount": ["mount"],
  "declan rice": ["rice"],
  "martin odegaard": ["odegaard","ødegaard","martin ødegaard","odegaart","odegard","ödegaard"],
  "martin ødegaard": ["odegaard","ødegaard","martin odegaard","odegard","ödegaard"],
  "trent alexander-arnold": ["trent","taa","alexander-arnold","alexander arnold","trent alexander arnold","trent arnold","alexander arnald"],
  "darwin nunez": ["darwin","nunez","núñez","darwin núñez","darwin nunyez","darwin nunes"],
  "darwin núñez": ["darwin","nunez","núñez","darwin nunez","darwin nunyez","darwin nunes"],
  "luis diaz": ["diaz","díaz","luis díaz","luiz diaz","luis dias"],
  "luis díaz": ["diaz","díaz","luis diaz","luiz diaz","luis dias"],
  "andrew robertson": ["robertson","andy robertson"],
  "alisson": ["alisson becker"],
  "bernardo silva": ["bernardo"],
  "dušan vlahović": ["vlahovic","vlahović","dusan vlahovic","dusan vlahović","vlahovics","vlahovik"],
  "dusan vlahovic": ["vlahovic","vlahović","dušan vlahović","dusan vlahović","vlahovics","vlahovik"],
  "khvicha kvaratskhelia": ["kvaratskhelia","kvara","kvaratskelia","kvaradona","khvicha","kvicha kvaratskhelia","kvaratshelia","kvaratshkelia","kvaratskheliya"],
  "henrikh mkhitaryan": ["mkhitaryan","mkitaryan","mkhitarian","mkhiteryan","henrikh mkitaryan"],
  "miralem pjanic": ["pjanic","pjanić","miralem pjanić","pjanich","pjanik"],
  "miralem pjanić": ["pjanic","pjanić","miralem pjanic","pjanich","pjanik"],
  "federico chiesa": ["chiesa"],
  "leonardo bonucci": ["bonucci"],
  "giorgio chiellini": ["chiellini"],
  "marek hamsik": ["hamsik","hamšík","marek hamšík","hamshik","hamsick"],
  "marek hamšík": ["hamsik","hamšík","marek hamsik","hamshik","hamsick"],
  "dries mertens": ["mertens"],
  "mauro icardi": ["icardi"],
  "hakan sukur": ["sukur","şükür","hakan şükür"],
  "hakan şükür": ["sukur","şükür","hakan sukur"],
  "salvatore schillaci": ["schillaci","toto schillaci","totò schillaci"],
  "roger milla": ["milla"],
  "ahn jung-hwan": ["ahn jung hwan","ahn"],
  "pak doo-ik": ["pak doo ik"],
  "alcides ghiggia": ["ghiggia"],
  "juan alberto schiaffino": ["schiaffino"],
  "bobby charlton": ["charlton"],
  "paul breitner": ["breitner"],
  "grzegorz lato": ["lato"],
  "mario kempes": ["kempes"],
  "paul gascoigne": ["gascoigne","gazza"],
  "vinicius junior": ["vinicius","vinícius","vini","vini jr","vinicius jr","vinícius jr","vinicius junior","vini junior","vini jr."],
  "vinícius júnior": ["vinicius junior","vinicius jr","vini jr","vini","vinicius","vinícius"],
  "rodrygo": ["rodrygo goes","rodrigo","rodrygo gois","rodrygo góes"],
  "endrick": ["endrik","endrick felipe"],
  "xherdan shaqiri": ["shaqiri","shakiri","shaquiri","xerdan shaqiri","xherdan shakiri"],
  "granit xhaka": ["xhaka","zaka","xaka","granit zaka"],
  "mario götze": ["mario gotze","gotze","götze","goetze","mario goetze"],
  "ángel di maría": ["angel di maria","di maria","di maría","angel dimaria"],
  "paulo dybala": ["dybala","dibala","dyballa","la joya"],
  "julian alvarez": ["julian","alvarez","álvarez","julián álvarez","julian álvarez"],
  "julián álvarez": ["julian alvarez","julian","alvarez","álvarez"],
  "enzo fernandez": ["enzo","fernandez","fernández","enzo fernández","enzo fernandes"],
  "enzo fernández": ["enzo fernandez","enzo","fernandez","fernández","enzo fernandes"],
  "alexis mac allister": ["mac allister","macallister","mcallister","alexis mcallister","alexis macallister"],
  "diego forlán": ["diego forlan","forlan","forlán","forland"],
  "andriy shevchenko": ["shevchenko","sheva","andrei shevchenko","andry shevchenko","shevshenko"],
  "oleksandr zinchenko": ["zinchenko","zintchenko","sinchenko","zinchencko"],
  "wojciech szczesny": ["szczesny","szczęsny","wojciech szczęsny","sczesny","sceszny","szezney","chesney"],
  "wojciech szczęsny": ["wojciech szczesny","szczesny","szczęsny","sczesny","sceszny","chesney"],
};

export const LAST_WORD_BLACKLIST = new Set([
  "united states",
  "south korea",
  "north korea",
  "west germany",
  "east germany",
  "czech republic",
  "ivory coast",
  "south africa",
  "saudi arabia",
  "bosnia and herzegovina",
  "serbia and montenegro",
  "soviet union",
  "real madrid",
  "manchester united",
  "manchester city",
  "bayern munich",
  "borussia dortmund",
  "atletico madrid",
  "atlético madrid",
  "ac milan",
  "inter miami",
  "inter milan",
]);