export const ANSWER_ALIASES = {
  "lionel messi": ["messi", "leo messi"],
  "cristiano ronaldo": ["ronaldo", "cr7", "c ronaldo", "cristiano"],
  "kylian mbappe": ["mbappe", "mbappé"],
  "zinedine zidane": ["zidane", "zizou"],
  "diego maradona": ["maradona"],
  "ronaldo": ["r9", "ronaldo nazario", "ronaldo nazário"],
  "ronaldo nazario": ["ronaldo", "r9", "ronaldo nazário"],
  "ronaldo nazário": ["ronaldo", "r9", "ronaldo nazario"],
  "roberto baggio": ["baggio"],
  "mario gotze": ["gotze", "götze", "mario götze"],
  "miroslav klose": ["klose"],
  "andres iniesta": ["iniesta", "andrés iniesta"],
  "emiliano martinez": ["martinez", "emiliano martínez", "dibu martinez"],
  "angel di maria": ["di maria", "ángel di maría", "di maría"],
  "james rodriguez": ["james", "james rodríguez", "rodriguez", "rodríguez"],
  "thomas muller": ["muller", "müller", "thomas müller"],
  "geoff hurst": ["hurst"],
  "gerd muller": ["muller", "müller", "gerd müller"],
  "luka modric": ["modric", "modrić"],
  "harry kane": ["kane"],
  "neymar": ["neymar jr", "neymar junior"],
  "zlatan ibrahimovic": ["zlatan", "ibrahimovic", "ibrahimović"],
  "mohamed salah": ["salah", "mo salah"],
  "sadio mane": ["mane", "mané", "sadio mané"],
  "kevin de bruyne": ["de bruyne", "kdb"],
  "erling haaland": ["haaland"],
  "robert lewandowski": ["lewandowski"],
  "bukayo saka": ["saka"],

  "netherlands": ["holland", "the netherlands"],
  "united states": ["usa", "us", "america", "united states of america"],
  "south korea": ["korea", "republic of korea"],
  "north korea": ["dpr korea"],
  "west germany": ["germany"],
  "czech republic": ["czechia"],
  "ivory coast": ["cote divoire", "côte d'ivoire"],
  "bosnia and herzogovina": ["bosnia"],
  "bosnia and herzegovina": ["bosnia"],
  "serbia and montenegro": ["serbia"],
  "soviet union": ["ussr"],
  "saudi arabia": ["saudi"],
  "south africa": ["rsa"],
  "new zealand": ["nz"],
  "united arab emirates": ["uae"],
};

export const LAST_WORD_BLACKLIST = new Set([
  "united states",
  "south korea",
  "north korea",
  "west germany",
  "east germany",
  "czech republic",
  "ivory coast",
  "south africa",
  "saudi arabia",
  "bosnia and herzegovina",
  "serbia and montenegro",
  "soviet union",
  "real madrid",
  "manchester united",
  "manchester city",
  "bayern munich",
  "borussia dortmund",
  "atletico madrid",
  "atlético madrid",
  "ac milan",
  "inter miami",
  "inter milan",
]);