export const CONNECTIONS_PUZZLES = [
  {
    id: "connections-001",
    title: "Football Connections",
    difficulty: "Easy",
    groups: [
      { category: "World Cup winners", color: "green", items: ["Brazil", "Germany", "Argentina", "France"] },
      { category: "Goalkeepers", color: "blue", items: ["Buffon", "Casillas", "Neuer", "Cech"] },
      { category: "London clubs", color: "purple", items: ["Arsenal", "Chelsea", "Tottenham", "Fulham"] },
      { category: "Major trophies", color: "orange", items: ["World Cup", "Euros", "Champions League", "Copa America"] },
    ],
  },
  {
    id: "connections-002",
    title: "Football Connections",
    difficulty: "Easy",
    groups: [
      { category: "Ballon d'Or winners", color: "purple", items: ["Messi", "Ronaldo", "Modric", "Benzema"] },
      { category: "English stadiums", color: "green", items: ["Anfield", "Old Trafford", "Etihad", "Emirates"] },
      { category: "Brazil legends", color: "blue", items: ["Pele", "Rivaldo", "Kaka", "Ronaldinho"] },
      { category: "Club nicknames", color: "orange", items: ["Gunners", "Blues", "Reds", "Magpies"] },
    ],
  },
  {
    id: "connections-003",
    title: "Football Connections",
    difficulty: "Easy",
    groups: [
      { category: "International teams", color: "green", items: ["Italy", "Spain", "Portugal", "England"] },
      { category: "Famous managers", color: "blue", items: ["Guardiola", "Klopp", "Mourinho", "Ancelotti"] },
      { category: "Classic strikers", color: "purple", items: ["Shearer", "Henry", "Kane", "Lewandowski"] },
      { category: "Derby words", color: "orange", items: ["Clasico", "Old Firm", "Merseyside", "Milan"] },
    ],
  },
  {
    id: "connections-004",
    title: "Football Connections",
    difficulty: "Easy",
    groups: [
      { category: "Spanish clubs", color: "blue", items: ["Valencia", "Sevilla", "Villarreal", "Betis"] },
      { category: "Famous number 10s", color: "green", items: ["Maradona", "Totti", "Baggio", "Riquelme"] },
      { category: "Football awards", color: "purple", items: ["Golden Boot", "Golden Ball", "Yashin Trophy", "Kopa Trophy"] },
      { category: "African nations", color: "orange", items: ["Nigeria", "Ghana", "Senegal", "Morocco"] },
    ],
  },
  {
    id: "connections-005",
    title: "Football Connections",
    difficulty: "Easy",
    groups: [
      { category: "Manchester clubs", color: "green", items: ["United", "City", "Stockport", "Salford"] },
      { category: "France icons", color: "blue", items: ["Zidane", "Henry", "Platini", "Mbappe"] },
      { category: "Goal celebrations", color: "purple", items: ["Siu", "Robot", "Knee slide", "Panenka"] },
      { category: "Italian stadiums", color: "orange", items: ["San Siro", "Olimpico", "Maradona", "Allianz Stadium"] },
    ],
  },
  {
    id: "connections-006",
    title: "Football Connections",
    difficulty: "Medium",
    groups: [
      { category: "Barcelona midfield era", color: "blue", items: ["Xavi", "Iniesta", "Busquets", "Rakitic"] },
      { category: "Champions League final scorers", color: "green", items: ["Bale", "Mandzukic", "Eto'o", "Gerrard"] },
      { category: "German clubs", color: "purple", items: ["Dortmund", "Leverkusen", "Stuttgart", "Leipzig"] },
      { category: "Shirt number 7s", color: "orange", items: ["Beckham", "Cantona", "Raul", "Figo"] },
    ],
  },
  {
    id: "connections-007",
    title: "Football Connections",
    difficulty: "Medium",
    groups: [
      { category: "Zlatan clubs", color: "orange", items: ["Ajax", "Inter", "PSG", "LA Galaxy"] },
      { category: "National team nicknames", color: "green", items: ["Azzurri", "Three Lions", "Selecao", "Oranje"] },
      { category: "Premier League cult heroes", color: "blue", items: ["Okocha", "Di Canio", "Juninho", "Le Tissier"] },
      { category: "World Cup host cities", color: "purple", items: ["Doha", "Moscow", "Berlin", "Johannesburg"] },
    ],
  },
  {
    id: "connections-008",
    title: "Football Connections",
    difficulty: "Medium",
    groups: [
      { category: "Real Madrid Galacticos", color: "purple", items: ["Zidane", "Ronaldo", "Figo", "Beckham"] },
      { category: "Portuguese managers", color: "green", items: ["Mourinho", "Amorim", "Fonseca", "Villas-Boas"] },
      { category: "Scandinavian stars", color: "blue", items: ["Haaland", "Odegaard", "Eriksen", "Larsson"] },
      { category: "Trophy final venues", color: "orange", items: ["Wembley", "Luzhniki", "Stade de France", "Ataturk"] },
    ],
  },
  {
    id: "connections-009",
    title: "Football Connections",
    difficulty: "Medium",
    groups: [
      { category: "Ajax academy stars", color: "green", items: ["Cruyff", "Seedorf", "Sneijder", "De Ligt"] },
      { category: "Penalty specialists", color: "blue", items: ["Jorginho", "Toney", "Le Tissier", "Baines"] },
      { category: "Milan derby links", color: "purple", items: ["Inter", "Milan", "San Siro", "Nerazzurri"] },
      { category: "South American clubs", color: "orange", items: ["Boca Juniors", "River Plate", "Santos", "Penarol"] },
    ],
  },
  {
    id: "connections-010",
    title: "Football Connections",
    difficulty: "Medium",
    groups: [
      { category: "Swedish football", color: "blue", items: ["Ibrahimovic", "Isak", "Malmo", "Friends Arena"] },
      { category: "Treble winners", color: "green", items: ["Barcelona 2009", "Inter 2010", "Bayern 2020", "City 2023"] },
      { category: "Famous defenders", color: "purple", items: ["Maldini", "Nesta", "Puyol", "Cannavaro"] },
      { category: "Spanish stadiums", color: "orange", items: ["Camp Nou", "Bernabeu", "Mestalla", "San Mames"] },
    ],
  },
  {
    id: "connections-011",
    title: "Football Connections",
    difficulty: "Medium",
    groups: [
      { category: "Euro surprise stories", color: "orange", items: ["Greece 2004", "Denmark 1992", "Wales 2016", "Iceland clap"] },
      { category: "Chelsea legends", color: "blue", items: ["Drogba", "Lampard", "Terry", "Cech"] },
      { category: "Football roles", color: "green", items: ["Sweeper", "False nine", "Regista", "Wing-back"] },
      { category: "Red clubs", color: "purple", items: ["Liverpool", "Benfica", "Bayern", "Arsenal"] },
    ],
  },
  {
    id: "connections-012",
    title: "Football Connections",
    difficulty: "Medium",
    groups: [
      { category: "2010 Spain core", color: "green", items: ["Casillas", "Pique", "Xavi", "Villa"] },
      { category: "Current trophy names", color: "blue", items: ["FA Cup", "Copa del Rey", "DFB-Pokal", "Coppa Italia"] },
      { category: "Free-kick masters", color: "purple", items: ["Juninho", "Pirlo", "Ward-Prowse", "Mihajlovic"] },
      { category: "Black and white clubs", color: "orange", items: ["Juventus", "Newcastle", "Udinese", "Besiktas"] },
    ],
  },
  {
    id: "connections-013",
    title: "Football Connections",
    difficulty: "Hard",
    groups: [
      { category: "Won World Cup as player", color: "green", items: ["Zidane", "Iniesta", "Klose", "Cannavaro"] },
      { category: "Porto 2004 links", color: "blue", items: ["Deco", "Costinha", "Mourinho", "Dragao"] },
      { category: "Basque football", color: "purple", items: ["Athletic Club", "Real Sociedad", "Alaves", "Eibar"] },
      { category: "Fast World Cup goals", color: "orange", items: ["Hakan Sukur", "Robson", "Dempsey", "Masek"] },
    ],
  },
  {
    id: "connections-014",
    title: "Football Connections",
    difficulty: "Hard",
    groups: [
      { category: "Red Bull clubs", color: "orange", items: ["Leipzig", "Salzburg", "Bragantino", "New York"] },
      { category: "Only-club legends", color: "green", items: ["Totti", "Maldini", "Giggs", "Scholes"] },
      { category: "Iconic finals", color: "blue", items: ["Istanbul", "Maracana", "Wembley 1966", "Lisbon 2014"] },
      { category: "Ballon d'Or non-Europeans", color: "purple", items: ["Weah", "Rivaldo", "Ronaldinho", "Kaka"] },
    ],
  },
  {
    id: "connections-015",
    title: "Football Connections",
    difficulty: "Hard",
    groups: [
      { category: "Mourinho clubs", color: "purple", items: ["Porto", "Chelsea", "Inter", "Roma"] },
      { category: "World Cup Golden Ball winners", color: "green", items: ["Forlan", "Modric", "Messi", "Rossi"] },
      { category: "Derby clubs", color: "blue", items: ["Celtic", "Rangers", "Fenerbahce", "Galatasaray"] },
      { category: "Historic formations", color: "orange", items: ["Catenaccio", "Total Football", "Gegenpress", "WM"] },
    ],
  },
  {
    id: "connections-016",
    title: "Football Connections",
    difficulty: "Hard",
    groups: [
      { category: "Olympic gold football nations", color: "green", items: ["Nigeria", "Cameroon", "Mexico", "Canada"] },
      { category: "Champions League winning captains", color: "blue", items: ["Lahm", "Ramos", "Henderson", "Azpilicueta"] },
      { category: "Club ownership nicknames", color: "purple", items: ["Old Lady", "Red Devils", "Rossoneri", "Toffees"] },
      { category: "Famous assists", color: "orange", items: ["Sheringham", "Solskjaer", "Iniesta", "Gotze"] },
    ],
  },
  {
    id: "connections-017",
    title: "Football Connections",
    difficulty: "Hard",
    groups: [
      { category: "Played for both rivals", color: "orange", items: ["Figo", "Tevez", "Campbell", "Ibrahimovic"] },
      { category: "African Ballon d'Or nominees", color: "green", items: ["Drogba", "Eto'o", "Mane", "Salah"] },
      { category: "European Cup old powers", color: "blue", items: ["Steaua", "Red Star", "Hamburg", "Feyenoord"] },
      { category: "Classic football boots", color: "purple", items: ["Predator", "Mercurial", "Tiempo", "Copa Mundial"] },
    ],
  },
  {
    id: "connections-018",
    title: "Football Connections",
    difficulty: "Hard",
    groups: [
      { category: "Argentina 1986 links", color: "blue", items: ["Maradona", "Valdano", "Burruchaga", "Azteca"] },
      { category: "Serie A managers", color: "green", items: ["Conte", "Allegri", "Spalletti", "Sarri"] },
      { category: "Famous transfer records", color: "purple", items: ["Neymar", "Mbappe", "Pogba", "Grealish"] },
      { category: "One-word club names", color: "orange", items: ["Roma", "Napoli", "Chelsea", "Sevilla"] },
    ],
  },
  {
    id: "connections-019",
    title: "Football Connections",
    difficulty: "Hard",
    groups: [
      { category: "Penalty shootout icons", color: "green", items: ["Duckadam", "Goycochea", "Southgate", "Trezeguet"] },
      { category: "Invincibles links", color: "blue", items: ["Wenger", "Vieira", "Pires", "Highbury"] },
      { category: "Clubs in capitals", color: "purple", items: ["PSG", "Hertha", "Roma", "Arsenal"] },
      { category: "Famous football songs", color: "orange", items: ["You'll Never Walk Alone", "Blue Moon", "Hala Madrid", "Glory Glory"] },
    ],
  },
  {
    id: "connections-020",
    title: "Football Connections",
    difficulty: "Hard",
    groups: [
      { category: "Won Champions League as manager", color: "blue", items: ["Guardiola", "Ancelotti", "Klopp", "Benitez"] },
      { category: "Brazil 2002 starters", color: "green", items: ["Cafu", "Lucio", "Gilberto Silva", "Rivaldo"] },
      { category: "Cult stadium atmospheres", color: "purple", items: ["Bombonera", "Signal Iduna", "Celtic Park", "Marakana"] },
      { category: "Famous shirt numbers", color: "orange", items: ["14", "7", "10", "9"] },
    ],
  },
  {
    id: "connections-021",
    title: "Football Connections",
    difficulty: "Medium",
    groups: [
      { category: "Arsenal unbeaten players", color: "green", items: ["Henry", "Bergkamp", "Campbell", "Lehmann"] },
      { category: "World Cup mascots", color: "blue", items: ["Zakumi", "Fuleco", "La'eeb", "Footix"] },
      { category: "MLS clubs", color: "purple", items: ["LAFC", "Inter Miami", "Seattle", "Atlanta"] },
      { category: "Football skill moves", color: "orange", items: ["Elastico", "Cruyff turn", "Rainbow flick", "Step-over"] },
    ],
  },
  {
    id: "connections-022",
    title: "Football Connections",
    difficulty: "Hard",
    groups: [
      { category: "Won Euros as manager", color: "green", items: ["Rehhagel", "Del Bosque", "Mancini", "Deschamps"] },
      { category: "Champions League final losing clubs", color: "blue", items: ["Sampdoria", "Monaco", "Leverkusen", "Valencia"] },
      { category: "Football documentary subjects", color: "purple", items: ["Sunderland", "Wrexham", "Juventus", "Tottenham"] },
      { category: "Iconic World Cup balls", color: "orange", items: ["Tango", "Jabulani", "Brazuca", "Telstar"] },
    ],
  },  {
    id: "connections-023",
    title: "Football Connections",
    difficulty: "Hard",
    groups: [
      { category: "Played for both Barcelona and Inter", color: "green", items: ["Ronaldo", "Ibrahimovic", "Eto'o", "Coutinho"] },
      { category: "Scored in a World Cup final", color: "blue", items: ["Iniesta", "Gotze", "Mbappe", "Zidane"] },
      { category: "Managed Chelsea", color: "purple", items: ["Mourinho", "Ancelotti", "Conte", "Tuchel"] },
      { category: "Italian defensive legends", color: "orange", items: ["Maldini", "Nesta", "Cannavaro", "Chiellini"] },
    ],
  },
  {
    id: "connections-024",
    title: "Football Connections",
    difficulty: "Hard",
    groups: [
      { category: "Won the World Cup with France", color: "blue", items: ["Deschamps", "Pogba", "Lloris", "Thuram"] },
      { category: "Played for Arsenal", color: "green", items: ["Ozil", "Aubameyang", "Bergkamp", "Vieira"] },
      { category: "Famous Dutch forwards", color: "purple", items: ["Van Basten", "Van Persie", "Robben", "Kluivert"] },
      { category: "Ballon d'Or winners from Brazil", color: "orange", items: ["Ronaldo", "Rivaldo", "Ronaldinho", "Kaka"] },
    ],
  },
  {
    id: "connections-025",
    title: "Football Connections",
    difficulty: "Medium",
    groups: [
      { category: "Played for Real Madrid", color: "green", items: ["Ozil", "Ramos", "Casemiro", "Bale"] },
      { category: "Played for Liverpool", color: "blue", items: ["Salah", "Gerrard", "Mane", "Alisson"] },
      { category: "Played for Bayern Munich", color: "purple", items: ["Robben", "Ribery", "Lahm", "Kimmich"] },
      { category: "Played for Juventus", color: "orange", items: ["Pirlo", "Buffon", "Del Piero", "Pogba"] },
    ],
  },
  {
    id: "connections-026",
    title: "Football Connections",
    difficulty: "Hard",
    groups: [
      { category: "World Cup Golden Boot winners", color: "orange", items: ["Kane", "Muller", "Ronaldo", "Lineker"] },
      { category: "Champions League final winning scorers", color: "green", items: ["Bale", "Havertz", "Rodrygo", "Mandzukic"] },
      { category: "Famous penalty missers", color: "blue", items: ["Baggio", "Trezeguet", "Southgate", "Saka"] },
      { category: "Iconic free-kick takers", color: "purple", items: ["Juninho", "Pirlo", "Beckham", "Mihajlovic"] },
    ],
  },
  {
    id: "connections-027",
    title: "Football Connections",
    difficulty: "Hard",
    groups: [
      { category: "Won Champions League as manager", color: "blue", items: ["Zidane", "Guardiola", "Klopp", "Benitez"] },
      { category: "Won World Cup as player and manager", color: "green", items: ["Deschamps", "Beckenbauer", "Zagallo", "Scaloni"] },
      { category: "Managed Manchester United", color: "purple", items: ["Ferguson", "Mourinho", "Ten Hag", "Van Gaal"] },
      { category: "Managed Real Madrid", color: "orange", items: ["Ancelotti", "Mourinho", "Zidane", "Capello"] },
    ],
  },
  {
    id: "connections-028",
    title: "Football Connections",
    difficulty: "Medium",
    groups: [
      { category: "World Cup host countries", color: "green", items: ["Qatar", "Russia", "Brazil", "Germany"] },
      { category: "Euros host countries", color: "blue", items: ["France", "Portugal", "England", "Poland"] },
      { category: "Copa America winners", color: "purple", items: ["Argentina", "Uruguay", "Chile", "Colombia"] },
      { category: "African Cup of Nations winners", color: "orange", items: ["Senegal", "Egypt", "Nigeria", "Algeria"] },
    ],
  },
  {
    id: "connections-029",
    title: "Football Connections",
    difficulty: "Hard",
    groups: [
      { category: "Played for both Milan clubs", color: "purple", items: ["Pirlo", "Seedorf", "Ibrahimovic", "Ronaldo"] },
      { category: "Played for both Manchester clubs", color: "green", items: ["Tevez", "Hargreaves", "Schmeichel", "Sancho"] },
      { category: "Played for both Arsenal and Chelsea", color: "blue", items: ["Fabregas", "Giroud", "Ashley Cole", "Willian"] },
      { category: "Played for both Real Madrid and Barcelona", color: "orange", items: ["Figo", "Ronaldo", "Laudrup", "Saviola"] },
    ],
  },
  {
    id: "connections-030",
    title: "Football Connections",
    difficulty: "Hard",
    groups: [
      { category: "Iconic World Cup balls", color: "orange", items: ["Jabulani", "Brazuca", "Telstar", "Teamgeist"] },
      { category: "Football boot lines", color: "green", items: ["Predator", "Mercurial", "Tiempo", "Copa Mundial"] },
      { category: "Famous football video games", color: "blue", items: ["FIFA", "PES", "Football Manager", "Sensible Soccer"] },
      { category: "Football skill moves", color: "purple", items: ["Elastico", "Rabona", "Step-over", "Cruyff turn"] },
    ],
  },
  {
    id: "connections-031",
    title: "Football Connections",
    difficulty: "Hard",
    groups: [
      { category: "Brazil 2002 starters", color: "green", items: ["Cafu", "Lucio", "Rivaldo", "Ronaldo"] },
      { category: "Spain 2010 starters", color: "blue", items: ["Casillas", "Puyol", "Xavi", "Villa"] },
      { category: "Germany 2014 starters", color: "purple", items: ["Neuer", "Lahm", "Kroos", "Muller"] },
      { category: "Argentina 2022 starters", color: "orange", items: ["Martinez", "Romero", "Mac Allister", "Messi"] },
    ],
  },
  
  {
    id: "connections-032",
    title: "Football Connections",
    difficulty: "Hard",
    groups: [
      { category: "Played for both Barcelona and PSG", color: "green", items: ["Messi", "Neymar", "Ronaldinho", "Ibrahimovic"] },
      { category: "Played for both Real Madrid and Bayern", color: "blue", items: ["Kroos", "Robben", "Xabi Alonso", "James Rodriguez"] },
      { category: "Played for both Chelsea and Arsenal", color: "purple", items: ["Fabregas", "Giroud", "Willian", "Ashley Cole"] },
      { category: "Played for both Juventus and Manchester United", color: "orange", items: ["Pogba", "Ronaldo", "Tevez", "Evra"] },
    ],
  },
  {
    id: "connections-033",
    title: "Football Connections",
    difficulty: "Hard",
    groups: [
      { category: "World Cup final winning goalscorers", color: "green", items: ["Iniesta", "Gotze", "Burruchaga", "Gerd Muller"] },
      { category: "Champions League final winning goalscorers", color: "blue", items: ["Havertz", "Vinicius", "Bale", "Drogba"] },
      { category: "Euro final goalscorers", color: "purple", items: ["Eder", "Torres", "Trezeguet", "Charisteas"] },
      { category: "Copa America final goalscorers", color: "orange", items: ["Di Maria", "Guerrero", "Ronaldo", "Sanchez"] },
    ],
  },
  {
    id: "connections-034",
    title: "Football Connections",
    difficulty: "Hard",
    groups: [
      { category: "Brazilian Ballon d'Or winners", color: "green", items: ["Ronaldo", "Rivaldo", "Ronaldinho", "Kaka"] },
      { category: "Italian Ballon d'Or winners", color: "blue", items: ["Baggio", "Cannavaro", "Rivera", "Rossi"] },
      { category: "Dutch Ballon d'Or winners", color: "purple", items: ["Cruyff", "Gullit", "Van Basten", "Rijkaard"] },
      { category: "French Ballon d'Or winners", color: "orange", items: ["Zidane", "Platini", "Benzema", "Kopa"] },
    ],
  },
  {
    id: "connections-035",
    title: "Football Connections",
    difficulty: "Very Hard",
    groups: [
      { category: "Played for Inter and Real Madrid", color: "green", items: ["Ronaldo", "Sneijder", "Zamorano", "Samuel"] },
      { category: "Played for Milan and Real Madrid", color: "blue", items: ["Kaka", "Seedorf", "Ronaldo", "Theo Hernandez"] },
      { category: "Played for Barcelona and Milan", color: "purple", items: ["Ronaldinho", "Rivaldo", "Ibrahimovic", "Zambrotta"] },
      { category: "Played for Juventus and Milan", color: "orange", items: ["Pirlo", "Inzaghi", "Bonucci", "Higuain"] },
    ],
  },
  {
    id: "connections-036",
    title: "Football Connections",
    difficulty: "Hard",
    groups: [
      { category: "Arsenal Invincibles", color: "green", items: ["Henry", "Bergkamp", "Vieira", "Pires"] },
      { category: "Manchester United 1999 treble players", color: "blue", items: ["Keane", "Giggs", "Scholes", "Beckham"] },
      { category: "Barcelona 2009 treble players", color: "purple", items: ["Xavi", "Iniesta", "Puyol", "Eto'o"] },
      { category: "Inter 2010 treble players", color: "orange", items: ["Milito", "Sneijder", "Zanetti", "Maicon"] },
    ],
  },
  {
    id: "connections-037",
    title: "Football Connections",
    difficulty: "Hard",
    groups: [
      { category: "Played under Guardiola at Barcelona", color: "green", items: ["Messi", "Busquets", "Pique", "Pedro"] },
      { category: "Played under Mourinho at Chelsea", color: "blue", items: ["Drogba", "Lampard", "Terry", "Makelele"] },
      { category: "Played under Klopp at Liverpool", color: "purple", items: ["Salah", "Mane", "Firmino", "Henderson"] },
      { category: "Played under Ancelotti at Real Madrid", color: "orange", items: ["Ramos", "Modric", "Benzema", "Kroos"] },
    ],
  },
  {
    id: "connections-038",
    title: "Football Connections",
    difficulty: "Very Hard",
    groups: [
      { category: "Scored in the 2022 World Cup final", color: "green", items: ["Messi", "Di Maria", "Mbappe", "Montiel"] },
      { category: "Scored in the 2018 World Cup final", color: "blue", items: ["Griezmann", "Pogba", "Perisic", "Mandzukic"] },
      { category: "Scored in the 2006 World Cup final shootout", color: "purple", items: ["Pirlo", "Materazzi", "De Rossi", "Grosso"] },
      { category: "Scored in the 1998 World Cup final", color: "orange", items: ["Zidane", "Petit", "Desailly", "Lizarazu"] },
    ],
  },
  {
    id: "connections-039",
    title: "Football Connections",
    difficulty: "Hard",
    groups: [
      { category: "Famous number 9s", color: "green", items: ["Ronaldo", "Lewandowski", "Shearer", "Batistuta"] },
      { category: "Famous number 10s", color: "blue", items: ["Maradona", "Messi", "Totti", "Riquelme"] },
      { category: "Famous number 7s", color: "purple", items: ["Ronaldo", "Beckham", "Cantona", "Raul"] },
      { category: "Famous number 8s", color: "orange", items: ["Lampard", "Gerrard", "Iniesta", "Kroos"] },
    ],
  },
  {
    id: "connections-040",
    title: "Football Connections",
    difficulty: "Hard",
    groups: [
      { category: "Chelsea Champions League winners", color: "green", items: ["Drogba", "Cech", "Lampard", "Terry"] },
      { category: "Liverpool Champions League winners", color: "blue", items: ["Salah", "Van Dijk", "Alisson", "Henderson"] },
      { category: "Real Madrid Champions League winners", color: "purple", items: ["Ramos", "Benzema", "Modric", "Casemiro"] },
      { category: "Barcelona Champions League winners", color: "orange", items: ["Messi", "Xavi", "Iniesta", "Puyol"] },
    ],
  },
  {
    id: "connections-041",
    title: "Football Connections",
    difficulty: "Very Hard",
    groups: [
      { category: "Ajax academy products", color: "green", items: ["Cruyff", "Seedorf", "Sneijder", "De Ligt"] },
      { category: "Sporting CP academy products", color: "blue", items: ["Ronaldo", "Figo", "Nani", "Quaresma"] },
      { category: "La Masia products", color: "purple", items: ["Xavi", "Iniesta", "Busquets", "Pique"] },
      { category: "Santos academy products", color: "orange", items: ["Pele", "Neymar", "Robinho", "Rodrygo"] },
    ],
  },
  {
    id: "connections-042",
    title: "Football Connections",
    difficulty: "Hard",
    groups: [
      { category: "Played for Atletico Madrid", color: "green", items: ["Griezmann", "Torres", "Godin", "Falcao"] },
      { category: "Played for Dortmund", color: "blue", items: ["Haaland", "Reus", "Lewandowski", "Sancho"] },
      { category: "Played for Napoli", color: "purple", items: ["Maradona", "Hamsik", "Cavani", "Osimhen"] },
      { category: "Played for Roma", color: "orange", items: ["Totti", "De Rossi", "Salah", "Dzeko"] },
    ],
  },
  {
    id: "connections-043",
    title: "Football Connections",
    difficulty: "Very Hard",
    groups: [
      { category: "Penalty shootout heartbreak", color: "green", items: ["Baggio", "Trezeguet", "Southgate", "Saka"] },
      { category: "Famous red cards", color: "blue", items: ["Zidane", "Beckham", "Rooney", "Pepe"] },
      { category: "Famous handball moments", color: "purple", items: ["Maradona", "Suarez", "Henry", "Kukielka"] },
      { category: "Famous last-minute goals", color: "orange", items: ["Aguero", "Solskjaer", "Iniesta", "Grosso"] },
    ],
  },
  {
    id: "connections-044",
    title: "Football Connections",
    difficulty: "Hard",
    groups: [
      { category: "Portuguese icons", color: "green", items: ["Ronaldo", "Figo", "Eusebio", "Deco"] },
      { category: "Croatian icons", color: "blue", items: ["Modric", "Suker", "Boban", "Rakitic"] },
      { category: "Uruguayan icons", color: "purple", items: ["Suarez", "Forlan", "Cavani", "Recoba"] },
      { category: "Swedish icons", color: "orange", items: ["Ibrahimovic", "Larsson", "Brolin", "Ravelli"] },
    ],
  },
  {
    id: "connections-045",
    title: "Football Connections",
    difficulty: "Hard",
    groups: [
      { category: "Played for Manchester United", color: "green", items: ["Rooney", "Keane", "Vidic", "Scholes"] },
      { category: "Played for Manchester City", color: "blue", items: ["Aguero", "Silva", "Kompany", "De Bruyne"] },
      { category: "Played for Tottenham", color: "purple", items: ["Kane", "Son", "Bale", "Modric"] },
      { category: "Played for Newcastle", color: "orange", items: ["Shearer", "Ginola", "Asprilla", "Given"] },
    ],
  },
  {
    id: "connections-046",
    title: "Football Connections",
    difficulty: "Very Hard",
    groups: [
      { category: "Won World Cup Golden Ball", color: "green", items: ["Messi", "Modric", "Forlan", "Rossi"] },
      { category: "Won World Cup Golden Boot", color: "blue", items: ["Kane", "Klose", "Lineker", "Suker"] },
      { category: "Won World Cup Golden Glove", color: "purple", items: ["Neuer", "Courtois", "Martinez", "Casillas"] },
      { category: "Won World Cup Young Player Award", color: "orange", items: ["Mbappe", "Pogba", "Muller", "Enzo Fernandez"] },
    ],
  },
  {
    id: "connections-047",
    title: "Football Connections",
    difficulty: "Hard",
    groups: [
      { category: "Played for Liverpool and Barcelona", color: "green", items: ["Suarez", "Coutinho", "Mascherano", "Reina"] },
      { category: "Played for Arsenal and Barcelona", color: "blue", items: ["Henry", "Fabregas", "Overmars", "Song"] },
      { category: "Played for Chelsea and Real Madrid", color: "purple", items: ["Hazard", "Courtois", "Makelele", "Robben"] },
      { category: "Played for Dortmund and Bayern", color: "orange", items: ["Lewandowski", "Gotze", "Hummels", "Guerreiro"] },
    ],
  },
  {
    id: "connections-048",
    title: "Football Connections",
    difficulty: "Hard",
    groups: [
      { category: "Premier League Golden Boot winners", color: "green", items: ["Salah", "Kane", "Haaland", "Vardy"] },
      { category: "La Liga top scorers", color: "blue", items: ["Messi", "Ronaldo", "Benzema", "Suarez"] },
      { category: "Serie A top scorers", color: "purple", items: ["Immobile", "Osimhen", "Higuain", "Ibrahimovic"] },
      { category: "Bundesliga top scorers", color: "orange", items: ["Lewandowski", "Aubameyang", "Klose", "Kane"] },
    ],
  },
  {
    id: "connections-049",
    title: "Football Connections",
    difficulty: "Very Hard",
    groups: [
      { category: "Scored in a Champions League final for Real Madrid", color: "green", items: ["Ramos", "Bale", "Vinicius", "Asensio"] },
      { category: "Scored in a Champions League final for Barcelona", color: "blue", items: ["Messi", "Eto'o", "Villa", "Rakitic"] },
      { category: "Scored in a Champions League final for Liverpool", color: "purple", items: ["Gerrard", "Smicer", "Alonso", "Salah"] },
      { category: "Scored in a Champions League final for Bayern", color: "orange", items: ["Robben", "Muller", "Coman", "Mandzukic"] },
    ],
  },
  {
    id: "connections-050",
    title: "Football Connections",
    difficulty: "Hard",
    groups: [
      { category: "Played for Paris Saint-Germain", color: "green", items: ["Mbappe", "Verratti", "Cavani", "Thiago Silva"] },
      { category: "Played for Atletico Madrid", color: "blue", items: ["Godin", "Koke", "Saul", "Griezmann"] },
      { category: "Played for Valencia", color: "purple", items: ["Villa", "Silva", "Mata", "Albiol"] },
      { category: "Played for Sevilla", color: "orange", items: ["Rakitic", "Navas", "Kanoute", "Bacca"] },
    ],
  },
  {
    id: "connections-051",
    title: "Football Connections",
    difficulty: "Very Hard",
    groups: [
      { category: "Managed Bayern Munich", color: "green", items: ["Guardiola", "Ancelotti", "Heynckes", "Tuchel"] },
      { category: "Managed Juventus", color: "blue", items: ["Conte", "Allegri", "Lippi", "Sarri"] },
      { category: "Managed Barcelona", color: "purple", items: ["Rijkaard", "Enrique", "Valverde", "Koeman"] },
      { category: "Managed Inter", color: "orange", items: ["Mourinho", "Mancini", "Inzaghi", "Benitez"] },
    ],
  },
  {
    id: "connections-052",
    title: "Football Connections",
    difficulty: "Hard",
    groups: [
      { category: "England World Cup 2018 players", color: "green", items: ["Pickford", "Maguire", "Trippier", "Lingard"] },
      { category: "Croatia World Cup 2018 players", color: "blue", items: ["Modric", "Rakitic", "Perisic", "Subasic"] },
      { category: "Belgium World Cup 2018 players", color: "purple", items: ["Hazard", "Lukaku", "Courtois", "Witsel"] },
      { category: "France World Cup 2018 players", color: "orange", items: ["Pogba", "Kante", "Giroud", "Varane"] },
    ],
  },
  {
    id: "connections-053",
    title: "Football Connections",
    difficulty: "Very Hard",
    groups: [
      { category: "Argentina 2022 World Cup players", color: "green", items: ["Mac Allister", "Paredes", "Romero", "Dybala"] },
      { category: "France 2022 World Cup players", color: "blue", items: ["Tchouameni", "Rabiot", "Upamecano", "Kolo Muani"] },
      { category: "Morocco 2022 World Cup players", color: "purple", items: ["Amrabat", "Ziyech", "Bounou", "Hakimi"] },
      { category: "Croatia 2022 World Cup players", color: "orange", items: ["Gvardiol", "Livakovic", "Kovacic", "Petkovic"] },
    ],
  },
  {
    id: "connections-054",
    title: "Football Connections",
    difficulty: "Hard",
    groups: [
      { category: "Classic Premier League midfielders", color: "green", items: ["Gerrard", "Lampard", "Scholes", "Vieira"] },
      { category: "Classic La Liga midfielders", color: "blue", items: ["Xavi", "Iniesta", "Modric", "Busquets"] },
      { category: "Classic Serie A midfielders", color: "purple", items: ["Pirlo", "Seedorf", "De Rossi", "Nedved"] },
      { category: "Classic Bundesliga midfielders", color: "orange", items: ["Ballack", "Schweinsteiger", "Kroos", "Matthaus"] },
    ],
  },
  {
    id: "connections-055",
    title: "Football Connections",
    difficulty: "Very Hard",
    groups: [
      { category: "Brazilian forwards", color: "green", items: ["Romario", "Adriano", "Careca", "Bebeto"] },
      { category: "Argentine forwards", color: "blue", items: ["Batistuta", "Aguero", "Crespo", "Higuain"] },
      { category: "French forwards", color: "purple", items: ["Henry", "Trezeguet", "Giroud", "Anelka"] },
      { category: "Italian forwards", color: "orange", items: ["Del Piero", "Vieri", "Inzaghi", "Toni"] },
    ],
  },
  {
    id: "connections-056",
    title: "Football Connections",
    difficulty: "Hard",
    groups: [
      { category: "Famous captains", color: "green", items: ["Puyol", "Terry", "Ramos", "Zanetti"] },
      { category: "Famous left-backs", color: "blue", items: ["Marcelo", "Cole", "Lahm", "Alaba"] },
      { category: "Famous centre-backs", color: "purple", items: ["Nesta", "Vidic", "Kompany", "Stam"] },
      { category: "Famous right-backs", color: "orange", items: ["Cafu", "Alves", "Trent", "Carvajal"] },
    ],
  },
  {
    id: "connections-057",
    title: "Football Connections",
    difficulty: "Very Hard",
    groups: [
      { category: "Won Champions League with Real Madrid", color: "green", items: ["Casillas", "Marcelo", "Kroos", "Isco"] },
      { category: "Won Champions League with Barcelona", color: "blue", items: ["Valdes", "Alba", "Mascherano", "Pedro"] },
      { category: "Won Champions League with Chelsea", color: "purple", items: ["Mendy", "Kante", "Mount", "Havertz"] },
      { category: "Won Champions League with AC Milan", color: "orange", items: ["Dida", "Gattuso", "Shevchenko", "Ambrosini"] },
    ],
  },
  {
    id: "connections-058",
    title: "Football Connections",
    difficulty: "Hard",
    groups: [
      { category: "Famous penalty takers", color: "green", items: ["Jorginho", "Kane", "Le Tissier", "Baines"] },
      { category: "Famous long-shot scorers", color: "blue", items: ["Gerrard", "Lampard", "Kroos", "Seedorf"] },
      { category: "Famous dribblers", color: "purple", items: ["Hazard", "Neymar", "Robben", "Ribery"] },
      { category: "Famous target men", color: "orange", items: ["Drogba", "Ibrahimovic", "Giroud", "Dzeko"] },
    ],
  },
  {
    id: "connections-059",
    title: "Football Connections",
    difficulty: "Hard",
    groups: [
      { category: "Players strongly linked with Nike Mercurial", color: "green", items: ["Ronaldo", "Mbappe", "Cristiano Ronaldo", "Henry"] },
      { category: "Players strongly linked with Adidas Predator", color: "blue", items: ["Beckham", "Zidane", "Gerrard", "Pogba"] },
      { category: "Players strongly linked with Adidas Copa", color: "purple", items: ["Beckenbauer", "Maradona", "Kroos", "Dybala"] },
      { category: "Players strongly linked with Puma boots", color: "orange", items: ["Pele", "Eusebio", "Neymar", "Griezmann"] },
    ],
  },
  {
    id: "connections-060",
    title: "Football Connections",
    difficulty: "Very Hard",
    groups: [
      { category: "Played in El Clasico", color: "green", items: ["Figo", "Ramos", "Xavi", "Benzema"] },
      { category: "Played in the Manchester derby", color: "blue", items: ["Rooney", "Aguero", "Kompany", "Scholes"] },
      { category: "Played in the Milan derby", color: "purple", items: ["Maldini", "Zanetti", "Shevchenko", "Materazzi"] },
      { category: "Played in the North London derby", color: "orange", items: ["Kane", "Henry", "Campbell", "Fabregas"] },
    ],
  },
  {
    id: "connections-061",
    title: "Football Connections",
    difficulty: "Hard",
    groups: [
      { category: "Iconic World Cup goalkeepers", color: "green", items: ["Casillas", "Neuer", "Buffon", "Martinez"] },
      { category: "Iconic Champions League goalkeepers", color: "blue", items: ["Cech", "Dudek", "Navas", "Alisson"] },
      { category: "Iconic Premier League goalkeepers", color: "purple", items: ["Schmeichel", "Seaman", "Van der Sar", "De Gea"] },
      { category: "Iconic Serie A goalkeepers", color: "orange", items: ["Pagliuca", "Peruzzi", "Zoff", "Donnarumma"] },
    ],
  }



];
