export const CONNECTIONS_PUZZLES = [
  {
    id: "connections-001",
    title: "Football Connections",
    difficulty: "Easy",
    groups: [
      { category: "World Cup winners", color: "green", items: ["Brazil", "Germany", "Argentina", "France"] },
      { category: "Goalkeepers", color: "blue", items: ["Buffon", "Casillas", "Neuer", "Cech"] },
      { category: "London clubs", color: "purple", items: ["Arsenal", "Chelsea", "Tottenham", "Fulham"] },
      { category: "Major trophies", color: "orange", items: ["World Cup", "Euros", "Champions League", "Copa America"] },
    ],
  },
  {
    id: "connections-002",
    title: "Football Connections",
    difficulty: "Easy",
    groups: [
      { category: "Ballon d'Or winners", color: "purple", items: ["Messi", "Ronaldo", "Modric", "Benzema"] },
      { category: "English stadiums", color: "green", items: ["Anfield", "Old Trafford", "Etihad", "Emirates"] },
      { category: "Brazil legends", color: "blue", items: ["Pele", "Rivaldo", "Kaka", "Ronaldinho"] },
      { category: "Club nicknames", color: "orange", items: ["Gunners", "Blues", "Reds", "Magpies"] },
    ],
  },
  {
    id: "connections-003",
    title: "Football Connections",
    difficulty: "Easy",
    groups: [
      { category: "International teams", color: "green", items: ["Italy", "Spain", "Portugal", "England"] },
      { category: "Famous managers", color: "blue", items: ["Guardiola", "Klopp", "Mourinho", "Ancelotti"] },
      { category: "Classic strikers", color: "purple", items: ["Shearer", "Henry", "Kane", "Lewandowski"] },
      { category: "Derby words", color: "orange", items: ["Clasico", "Old Firm", "Merseyside", "Milan"] },
    ],
  },
  {
    id: "connections-004",
    title: "Football Connections",
    difficulty: "Easy",
    groups: [
      { category: "Spanish clubs", color: "blue", items: ["Valencia", "Sevilla", "Villarreal", "Betis"] },
      { category: "Famous number 10s", color: "green", items: ["Maradona", "Totti", "Baggio", "Riquelme"] },
      { category: "Football awards", color: "purple", items: ["Golden Boot", "Golden Ball", "Yashin Trophy", "Kopa Trophy"] },
      { category: "African nations", color: "orange", items: ["Nigeria", "Ghana", "Senegal", "Morocco"] },
    ],
  },
  {
    id: "connections-005",
    title: "Football Connections",
    difficulty: "Easy",
    groups: [
      { category: "Manchester clubs", color: "green", items: ["United", "City", "Stockport", "Salford"] },
      { category: "France icons", color: "blue", items: ["Zidane", "Henry", "Platini", "Mbappe"] },
      { category: "Goal celebrations", color: "purple", items: ["Siu", "Robot", "Knee slide", "Panenka"] },
      { category: "Italian stadiums", color: "orange", items: ["San Siro", "Olimpico", "Maradona", "Allianz Stadium"] },
    ],
  },
  {
    id: "connections-006",
    title: "Football Connections",
    difficulty: "Medium",
    groups: [
      { category: "Barcelona midfield era", color: "blue", items: ["Xavi", "Iniesta", "Busquets", "Rakitic"] },
      { category: "Champions League final scorers", color: "green", items: ["Bale", "Mandzukic", "Eto'o", "Gerrard"] },
      { category: "German clubs", color: "purple", items: ["Dortmund", "Leverkusen", "Stuttgart", "Leipzig"] },
      { category: "Shirt number 7s", color: "orange", items: ["Beckham", "Cantona", "Raul", "Figo"] },
    ],
  },
  {
    id: "connections-007",
    title: "Football Connections",
    difficulty: "Medium",
    groups: [
      { category: "Zlatan clubs", color: "orange", items: ["Ajax", "Inter", "PSG", "LA Galaxy"] },
      { category: "National team nicknames", color: "green", items: ["Azzurri", "Three Lions", "Selecao", "Oranje"] },
      { category: "Premier League cult heroes", color: "blue", items: ["Okocha", "Di Canio", "Juninho", "Le Tissier"] },
      { category: "World Cup host cities", color: "purple", items: ["Doha", "Moscow", "Berlin", "Johannesburg"] },
    ],
  },
  {
    id: "connections-008",
    title: "Football Connections",
    difficulty: "Medium",
    groups: [
      { category: "Real Madrid Galacticos", color: "purple", items: ["Zidane", "Ronaldo", "Figo", "Beckham"] },
      { category: "Portuguese managers", color: "green", items: ["Mourinho", "Amorim", "Fonseca", "Villas-Boas"] },
      { category: "Scandinavian stars", color: "blue", items: ["Haaland", "Odegaard", "Eriksen", "Larsson"] },
      { category: "Trophy final venues", color: "orange", items: ["Wembley", "Luzhniki", "Stade de France", "Ataturk"] },
    ],
  },
  {
    id: "connections-009",
    title: "Football Connections",
    difficulty: "Medium",
    groups: [
      { category: "Ajax academy stars", color: "green", items: ["Cruyff", "Seedorf", "Sneijder", "De Ligt"] },
      { category: "Penalty specialists", color: "blue", items: ["Jorginho", "Toney", "Le Tissier", "Baines"] },
      { category: "Milan derby links", color: "purple", items: ["Inter", "Milan", "San Siro", "Nerazzurri"] },
      { category: "South American clubs", color: "orange", items: ["Boca Juniors", "River Plate", "Santos", "Penarol"] },
    ],
  },
  {
    id: "connections-010",
    title: "Football Connections",
    difficulty: "Medium",
    groups: [
      { category: "Swedish football", color: "blue", items: ["Ibrahimovic", "Isak", "Malmo", "Friends Arena"] },
      { category: "Treble winners", color: "green", items: ["Barcelona 2009", "Inter 2010", "Bayern 2020", "City 2023"] },
      { category: "Famous defenders", color: "purple", items: ["Maldini", "Nesta", "Puyol", "Cannavaro"] },
      { category: "Spanish stadiums", color: "orange", items: ["Camp Nou", "Bernabeu", "Mestalla", "San Mames"] },
    ],
  },
  {
    id: "connections-011",
    title: "Football Connections",
    difficulty: "Medium",
    groups: [
      { category: "Euro surprise stories", color: "orange", items: ["Greece 2004", "Denmark 1992", "Wales 2016", "Iceland clap"] },
      { category: "Chelsea legends", color: "blue", items: ["Drogba", "Lampard", "Terry", "Cech"] },
      { category: "Football roles", color: "green", items: ["Sweeper", "False nine", "Regista", "Wing-back"] },
      { category: "Red clubs", color: "purple", items: ["Liverpool", "Benfica", "Bayern", "Arsenal"] },
    ],
  },
  {
    id: "connections-012",
    title: "Football Connections",
    difficulty: "Medium",
    groups: [
      { category: "2010 Spain core", color: "green", items: ["Casillas", "Pique", "Xavi", "Villa"] },
      { category: "Current trophy names", color: "blue", items: ["FA Cup", "Copa del Rey", "DFB-Pokal", "Coppa Italia"] },
      { category: "Free-kick masters", color: "purple", items: ["Juninho", "Pirlo", "Ward-Prowse", "Mihajlovic"] },
      { category: "Black and white clubs", color: "orange", items: ["Juventus", "Newcastle", "Udinese", "Besiktas"] },
    ],
  },
  {
    id: "connections-013",
    title: "Football Connections",
    difficulty: "Hard",
    groups: [
      { category: "Won World Cup as player", color: "green", items: ["Zidane", "Iniesta", "Klose", "Cannavaro"] },
      { category: "Porto 2004 links", color: "blue", items: ["Deco", "Costinha", "Mourinho", "Dragao"] },
      { category: "Basque football", color: "purple", items: ["Athletic Club", "Real Sociedad", "Alaves", "Eibar"] },
      { category: "Fast World Cup goals", color: "orange", items: ["Hakan Sukur", "Robson", "Dempsey", "Masek"] },
    ],
  },
  {
    id: "connections-014",
    title: "Football Connections",
    difficulty: "Hard",
    groups: [
      { category: "Red Bull clubs", color: "orange", items: ["Leipzig", "Salzburg", "Bragantino", "New York"] },
      { category: "Only-club legends", color: "green", items: ["Totti", "Maldini", "Giggs", "Scholes"] },
      { category: "Iconic finals", color: "blue", items: ["Istanbul", "Maracana", "Wembley 1966", "Lisbon 2014"] },
      { category: "Ballon d'Or non-Europeans", color: "purple", items: ["Weah", "Rivaldo", "Ronaldinho", "Kaka"] },
    ],
  },
  {
    id: "connections-015",
    title: "Football Connections",
    difficulty: "Hard",
    groups: [
      { category: "Mourinho clubs", color: "purple", items: ["Porto", "Chelsea", "Inter", "Roma"] },
      { category: "World Cup Golden Ball winners", color: "green", items: ["Forlan", "Modric", "Messi", "Rossi"] },
      { category: "Derby clubs", color: "blue", items: ["Celtic", "Rangers", "Fenerbahce", "Galatasaray"] },
      { category: "Historic formations", color: "orange", items: ["Catenaccio", "Total Football", "Gegenpress", "WM"] },
    ],
  },
  {
    id: "connections-016",
    title: "Football Connections",
    difficulty: "Hard",
    groups: [
      { category: "Olympic gold football nations", color: "green", items: ["Nigeria", "Cameroon", "Mexico", "Canada"] },
      { category: "Champions League winning captains", color: "blue", items: ["Lahm", "Ramos", "Henderson", "Azpilicueta"] },
      { category: "Club ownership nicknames", color: "purple", items: ["Old Lady", "Red Devils", "Rossoneri", "Toffees"] },
      { category: "Famous assists", color: "orange", items: ["Sheringham", "Solskjaer", "Iniesta", "Gotze"] },
    ],
  },
  {
    id: "connections-017",
    title: "Football Connections",
    difficulty: "Hard",
    groups: [
      { category: "Played for both rivals", color: "orange", items: ["Figo", "Tevez", "Campbell", "Ibrahimovic"] },
      { category: "African Ballon d'Or nominees", color: "green", items: ["Drogba", "Eto'o", "Mane", "Salah"] },
      { category: "European Cup old powers", color: "blue", items: ["Steaua", "Red Star", "Hamburg", "Feyenoord"] },
      { category: "Classic football boots", color: "purple", items: ["Predator", "Mercurial", "Tiempo", "Copa Mundial"] },
    ],
  },
  {
    id: "connections-018",
    title: "Football Connections",
    difficulty: "Hard",
    groups: [
      { category: "Argentina 1986 links", color: "blue", items: ["Maradona", "Valdano", "Burruchaga", "Azteca"] },
      { category: "Serie A managers", color: "green", items: ["Conte", "Allegri", "Spalletti", "Sarri"] },
      { category: "Famous transfer records", color: "purple", items: ["Neymar", "Mbappe", "Pogba", "Grealish"] },
      { category: "One-word club names", color: "orange", items: ["Roma", "Napoli", "Chelsea", "Sevilla"] },
    ],
  },
  {
    id: "connections-019",
    title: "Football Connections",
    difficulty: "Hard",
    groups: [
      { category: "Penalty shootout icons", color: "green", items: ["Duckadam", "Goycochea", "Southgate", "Trezeguet"] },
      { category: "Invincibles links", color: "blue", items: ["Wenger", "Vieira", "Pires", "Highbury"] },
      { category: "Clubs in capitals", color: "purple", items: ["PSG", "Hertha", "Roma", "Arsenal"] },
      { category: "Famous football songs", color: "orange", items: ["You'll Never Walk Alone", "Blue Moon", "Hala Madrid", "Glory Glory"] },
    ],
  },
  {
    id: "connections-020",
    title: "Football Connections",
    difficulty: "Hard",
    groups: [
      { category: "Won Champions League as manager", color: "blue", items: ["Guardiola", "Ancelotti", "Klopp", "Benitez"] },
      { category: "Brazil 2002 starters", color: "green", items: ["Cafu", "Lucio", "Gilberto Silva", "Rivaldo"] },
      { category: "Cult stadium atmospheres", color: "purple", items: ["Bombonera", "Signal Iduna", "Celtic Park", "Marakana"] },
      { category: "Famous shirt numbers", color: "orange", items: ["14", "7", "10", "9"] },
    ],
  },
  {
    id: "connections-021",
    title: "Football Connections",
    difficulty: "Medium",
    groups: [
      { category: "Arsenal unbeaten players", color: "green", items: ["Henry", "Bergkamp", "Campbell", "Lehmann"] },
      { category: "World Cup mascots", color: "blue", items: ["Zakumi", "Fuleco", "La'eeb", "Footix"] },
      { category: "MLS clubs", color: "purple", items: ["LAFC", "Inter Miami", "Seattle", "Atlanta"] },
      { category: "Football skill moves", color: "orange", items: ["Elastico", "Cruyff turn", "Rainbow flick", "Step-over"] },
    ],
  },
  {
    id: "connections-022",
    title: "Football Connections",
    difficulty: "Hard",
    groups: [
      { category: "Won Euros as manager", color: "green", items: ["Rehhagel", "Del Bosque", "Mancini", "Deschamps"] },
      { category: "Champions League final losing clubs", color: "blue", items: ["Sampdoria", "Monaco", "Leverkusen", "Valencia"] },
      { category: "Football documentary subjects", color: "purple", items: ["Sunderland", "Wrexham", "Juventus", "Tottenham"] },
      { category: "Iconic World Cup balls", color: "orange", items: ["Tango", "Jabulani", "Brazuca", "Telstar"] },
    ],
  },
];
