export const DAILY_LIST_CHALLENGES = [
  {
    id: "england-most-caps",
    label: "Most capped England players",
    question: "Can you name 10 players with the most appearances for England?",
    answers: [
      "Peter Shilton",
      "Wayne Rooney",
      "David Beckham",
      "Steven Gerrard",
      "Harry Kane",
      "Bobby Moore",
      "Ashley Cole",
      "Bobby Charlton",
      "Frank Lampard",
      "Billy Wright",
    ],
  },

  {
    id: "ucl-top-scorers",
    label: "Champions League top scorers",
    question: "Can you name 10 of the highest scorers in Champions League history?",
    answers: [
      "Cristiano Ronaldo",
      "Lionel Messi",
      "Robert Lewandowski",
      "Karim Benzema",
      "Raul",
      "Kylian Mbappe",
      "Erling Haaland",
      "Thomas Muller",
      "Ruud van Nistelrooy",
      "Harry Kane",
    ],
  },

  {
    id: "premier-league-top-scorers",
    label: "Premier League top scorers",
    question: "Can you name 10 of the highest scorers in Premier League history?",
    answers: [
      "Alan Shearer",
      "Harry Kane",
      "Wayne Rooney",
      "Mohamed Salah",
      "Andrew Cole",
      "Sergio Aguero",
      "Frank Lampard",
      "Thierry Henry",
      "Robbie Fowler",
      "Jermain Defoe",
    ],
  },

  {
    id: "world-cup-top-scorers",
    label: "World Cup top scorers",
    question: "Can you name 10 of the highest scorers in FIFA World Cup history?",
    answers: [
      "Miroslav Klose",
      "Ronaldo",
      "Gerd Muller",
      "Lionel Messi",
      "Just Fontaine",
      "Kylian Mbappe",
      "Pele",
      "Sandor Kocsis",
      "Jurgen Klinsmann",
      "Gabriel Batistuta",
    ],
  },

  {
    id: "ballon-dor-countries",
    label: "Ballon d'Or countries",
    question: "Can you name 10 countries with the most Ballon d'Or wins?",
    answers: [
      "Argentina",
      "France",
      "Germany",
      "Netherlands",
      "Portugal",
      "Brazil",
      "England",
      "Italy",
      "Spain",
      "Soviet Union",
    ],
  },

  {
    id: "ballon-dor-winners-modern",
    label: "Modern Ballon d'Or winners",
    question: "Can you name 10 players who have won the Ballon d'Or since 2000?",
    answers: [
      "Luis Figo",
      "Michael Owen",
      "Ronaldo",
      "Pavel Nedved",
      "Andriy Shevchenko",
      "Ronaldinho",
      "Fabio Cannavaro",
      "Kaka",
      "Cristiano Ronaldo",
      "Lionel Messi",
    ],
  },

  {
    id: "real-madrid-top-scorers",
    label: "Real Madrid top scorers",
    question: "Can you name 10 of Real Madrid's all-time top scorers?",
    answers: [
      "Cristiano Ronaldo",
      "Karim Benzema",
      "Raul",
      "Alfredo Di Stefano",
      "Santillana",
      "Ferenc Puskas",
      "Hugo Sanchez",
      "Francisco Gento",
      "Pirri",
      "Emilio Butragueno",
    ],
  },

  {
    id: "barcelona-appearances",
    label: "Barcelona appearance makers",
    question: "Can you name 10 players with the most appearances for Barcelona?",
    answers: [
      "Lionel Messi",
      "Xavi",
      "Sergio Busquets",
      "Andres Iniesta",
      "Gerard Pique",
      "Carles Puyol",
      "Migueli",
      "Victor Valdes",
      "Jordi Alba",
      "Guillermo Amor",
    ],
  },

  {
    id: "brazil-top-scorers",
    label: "Brazil top scorers",
    question: "Can you name 10 of Brazil's highest scoring national team players?",
    answers: [
      "Neymar",
      "Pele",
      "Ronaldo",
      "Romario",
      "Zico",
      "Bebeto",
      "Rivaldo",
      "Jairzinho",
      "Ronaldinho",
      "Ademir",
    ],
  },

  {
    id: "france-most-caps",
    label: "Most capped France players",
    question: "Can you name 10 players with the most appearances for France?",
    answers: [
      "Hugo Lloris",
      "Lilian Thuram",
      "Olivier Giroud",
      "Antoine Griezmann",
      "Marcel Desailly",
      "Zinedine Zidane",
      "Patrick Vieira",
      "Didier Deschamps",
      "Thierry Henry",
      "Karim Benzema",
    ],
  },

  {
    id: "spain-most-caps",
    label: "Most capped Spain players",
    question: "Can you name 10 players with the most appearances for Spain?",
    answers: [
      "Sergio Ramos",
      "Iker Casillas",
      "Sergio Busquets",
      "Xavi",
      "Andres Iniesta",
      "Andoni Zubizarreta",
      "David Silva",
      "Xabi Alonso",
      "Fernando Torres",
      "Cesc Fabregas",
    ],
  },

  {
    id: "sweden-most-caps",
    label: "Most capped Sweden players",
    question: "Can you name 10 players with the most appearances for Sweden?",
    answers: [
      "Anders Svensson",
      "Thomas Ravelli",
      "Sebastian Larsson",
      "Andreas Isaksson",
      "Zlatan Ibrahimovic",
      "Kim Kallstrom",
      "Olof Mellberg",
      "Henrik Larsson",
      "Mikael Nilsson",
      "Bjorn Nordqvist",
    ],
  },
];