export const DAILY_LIST_CHALLENGES = [
  {
    id: "england-most-caps",
    label: "Most capped England players",
    question: "Can you name 10 players with the most appearances for England?",
    answers: [
      { answer: "Peter Shilton", value: "125 caps" },
      { answer: "Wayne Rooney", value: "120 caps" },
      { answer: "David Beckham", value: "115 caps" },
      { answer: "Steven Gerrard", value: "114 caps" },
      { answer: "Harry Kane", value: "100+ caps" },
      { answer: "Bobby Moore", value: "108 caps" },
      { answer: "Ashley Cole", value: "107 caps" },
      { answer: "Bobby Charlton", value: "106 caps" },
      { answer: "Frank Lampard", value: "106 caps" },
      { answer: "Billy Wright", value: "105 caps" },
    ],
  },
  {
    id: "ucl-top-scorers",
    label: "Champions League top scorers",
    question: "Can you name 10 of the highest scorers in Champions League history?",
    answers: [
      { answer: "Cristiano Ronaldo", value: "140+ goals", aliases: ["Ronaldo", "CR7"] },
      { answer: "Lionel Messi", value: "125+ goals", aliases: ["Messi"] },
      { answer: "Robert Lewandowski", value: "100+ goals", aliases: ["Lewandowski"] },
      { answer: "Karim Benzema", value: "90 goals", aliases: ["Benzema"] },
      { answer: "Raul", value: "71 goals", aliases: ["Raúl"] },
      { answer: "Kylian Mbappe", value: "50+ goals", aliases: ["Mbappé", "Mbappe"] },
      { answer: "Erling Haaland", value: "50+ goals", aliases: ["Haaland"] },
      { answer: "Thomas Muller", value: "50+ goals", aliases: ["Thomas Müller", "Muller"] },
      { answer: "Ruud van Nistelrooy", value: "56 goals", aliases: ["Van Nistelrooy"] },
      { answer: "Harry Kane", value: "40+ goals", aliases: ["Kane"] },
    ],
  },
  {
    id: "premier-league-top-scorers",
    label: "Premier League top scorers",
    question: "Can you name 10 of the highest scorers in Premier League history?",
    answers: [
      { answer: "Alan Shearer", value: "260 goals", aliases: ["Shearer"] },
      { answer: "Harry Kane", value: "213 goals", aliases: ["Kane"] },
      { answer: "Wayne Rooney", value: "208 goals", aliases: ["Rooney"] },
      { answer: "Mohamed Salah", value: "180+ goals", aliases: ["Salah", "Mo Salah"] },
      { answer: "Andrew Cole", value: "187 goals", aliases: ["Andy Cole", "Cole"] },
      { answer: "Sergio Aguero", value: "184 goals", aliases: ["Sergio Agüero", "Aguero"] },
      { answer: "Frank Lampard", value: "177 goals", aliases: ["Lampard"] },
      { answer: "Thierry Henry", value: "175 goals", aliases: ["Henry"] },
      { answer: "Robbie Fowler", value: "163 goals", aliases: ["Fowler"] },
      { answer: "Jermain Defoe", value: "162 goals", aliases: ["Defoe"] },
    ],
  },
  {
    id: "world-cup-top-scorers",
    label: "World Cup top scorers",
    question: "Can you name 10 of the highest scorers in FIFA World Cup history?",
    answers: [
      { answer: "Miroslav Klose", value: "16 goals", aliases: ["Klose"] },
      { answer: "Ronaldo", value: "15 goals", aliases: ["R9", "Ronaldo Nazario"] },
      { answer: "Gerd Muller", value: "14 goals", aliases: ["Gerd Müller", "Muller"] },
      { answer: "Lionel Messi", value: "13 goals", aliases: ["Messi"] },
      { answer: "Just Fontaine", value: "13 goals", aliases: ["Fontaine"] },
      { answer: "Kylian Mbappe", value: "12 goals", aliases: ["Mbappé", "Mbappe"] },
      { answer: "Pele", value: "12 goals", aliases: ["Pelé"] },
      { answer: "Sandor Kocsis", value: "11 goals", aliases: ["Sándor Kocsis", "Kocsis"] },
      { answer: "Jurgen Klinsmann", value: "11 goals", aliases: ["Jürgen Klinsmann", "Klinsmann"] },
      { answer: "Gabriel Batistuta", value: "10 goals", aliases: ["Batistuta"] },
    ],
  },
  {
    id: "ballon-dor-countries",
    label: "Ballon d'Or countries",
    question: "Can you name 10 countries with the most Ballon d'Or wins?",
    answers: [
      { answer: "Argentina", value: "8 wins" },
      { answer: "France", value: "7 wins" },
      { answer: "Germany", value: "7 wins" },
      { answer: "Netherlands", value: "7 wins", aliases: ["Holland"] },
      { answer: "Portugal", value: "7 wins" },
      { answer: "Brazil", value: "5 wins" },
      { answer: "England", value: "5 wins" },
      { answer: "Italy", value: "5 wins" },
      { answer: "Spain", value: "4 wins" },
      { answer: "Soviet Union", value: "3 wins", aliases: ["USSR"] },
    ],
  },
  {
    id: "ballon-dor-winners-modern",
    label: "Modern Ballon d'Or winners",
    question: "Can you name 10 players who have won the Ballon d'Or since 2000?",
    answers: [
      { answer: "Luis Figo", value: "2000", aliases: ["Figo"] },
      { answer: "Michael Owen", value: "2001", aliases: ["Owen"] },
      { answer: "Ronaldo", value: "2002", aliases: ["R9", "Ronaldo Nazario"] },
      { answer: "Pavel Nedved", value: "2003", aliases: ["Pavel Nedvěd", "Nedved"] },
      { answer: "Andriy Shevchenko", value: "2004", aliases: ["Shevchenko"] },
      { answer: "Ronaldinho", value: "2005" },
      { answer: "Fabio Cannavaro", value: "2006", aliases: ["Cannavaro"] },
      { answer: "Kaka", value: "2007", aliases: ["Kaká"] },
      { answer: "Cristiano Ronaldo", value: "5 wins", aliases: ["Ronaldo", "CR7"] },
      { answer: "Lionel Messi", value: "8 wins", aliases: ["Messi"] },
    ],
  },
  {
    id: "real-madrid-top-scorers",
    label: "Real Madrid top scorers",
    question: "Can you name 10 of Real Madrid's all-time top scorers?",
    answers: [
      { answer: "Cristiano Ronaldo", value: "450 goals", aliases: ["Ronaldo", "CR7"] },
      { answer: "Karim Benzema", value: "354 goals", aliases: ["Benzema"] },
      { answer: "Raul", value: "323 goals", aliases: ["Raúl"] },
      { answer: "Alfredo Di Stefano", value: "308 goals", aliases: ["Di Stefano", "Di Stéfano"] },
      { answer: "Santillana", value: "290 goals" },
      { answer: "Ferenc Puskas", value: "242 goals", aliases: ["Puskás", "Puskas"] },
      { answer: "Hugo Sanchez", value: "208 goals", aliases: ["Hugo Sánchez", "Sanchez"] },
      { answer: "Francisco Gento", value: "182 goals", aliases: ["Gento"] },
      { answer: "Pirri", value: "172 goals" },
      { answer: "Emilio Butragueno", value: "171 goals", aliases: ["Butragueño", "Butragueno"] },
    ],
  },
  {
    id: "barcelona-appearances",
    label: "Barcelona appearance makers",
    question: "Can you name 10 players with the most appearances for Barcelona?",
    answers: [
      { answer: "Lionel Messi", value: "778 apps", aliases: ["Messi"] },
      { answer: "Xavi", value: "767 apps" },
      { answer: "Sergio Busquets", value: "722 apps", aliases: ["Busquets"] },
      { answer: "Andres Iniesta", value: "674 apps", aliases: ["Andrés Iniesta", "Iniesta"] },
      { answer: "Gerard Pique", value: "616 apps", aliases: ["Gerard Piqué", "Pique"] },
      { answer: "Carles Puyol", value: "593 apps", aliases: ["Puyol"] },
      { answer: "Migueli", value: "549 apps" },
      { answer: "Victor Valdes", value: "535 apps", aliases: ["Víctor Valdés", "Valdes"] },
      { answer: "Jordi Alba", value: "459 apps" },
      { answer: "Guillermo Amor", value: "421 apps", aliases: ["Amor"] },
    ],
  },
  {
    id: "brazil-top-scorers",
    label: "Brazil top scorers",
    question: "Can you name 10 of Brazil's highest scoring national team players?",
    answers: [
      { answer: "Neymar", value: "79 goals" },
      { answer: "Pele", value: "77 goals", aliases: ["Pelé"] },
      { answer: "Ronaldo", value: "62 goals", aliases: ["R9", "Ronaldo Nazario"] },
      { answer: "Romario", value: "55 goals", aliases: ["Romário"] },
      { answer: "Zico", value: "48 goals" },
      { answer: "Bebeto", value: "39 goals" },
      { answer: "Rivaldo", value: "35 goals" },
      { answer: "Jairzinho", value: "33 goals" },
      { answer: "Ronaldinho", value: "33 goals" },
      { answer: "Ademir", value: "32 goals" },
    ],
  },
  {
    id: "france-most-caps",
    label: "Most capped France players",
    question: "Can you name 10 players with the most appearances for France?",
    answers: [
      { answer: "Hugo Lloris", value: "145 caps", aliases: ["Lloris"] },
      { answer: "Lilian Thuram", value: "142 caps", aliases: ["Thuram"] },
      { answer: "Olivier Giroud", value: "130+ caps", aliases: ["Giroud"] },
      { answer: "Antoine Griezmann", value: "125+ caps", aliases: ["Griezmann"] },
      { answer: "Marcel Desailly", value: "116 caps", aliases: ["Desailly"] },
      { answer: "Zinedine Zidane", value: "108 caps", aliases: ["Zidane"] },
      { answer: "Patrick Vieira", value: "107 caps", aliases: ["Vieira"] },
      { answer: "Didier Deschamps", value: "103 caps", aliases: ["Deschamps"] },
      { answer: "Thierry Henry", value: "123 caps", aliases: ["Henry"] },
      { answer: "Karim Benzema", value: "97 caps", aliases: ["Benzema"] },
    ],
  },
  {
    id: "spain-most-caps",
    label: "Most capped Spain players",
    question: "Can you name 10 players with the most appearances for Spain?",
    answers: [
      { answer: "Sergio Ramos", value: "180 caps", aliases: ["Ramos"] },
      { answer: "Iker Casillas", value: "167 caps", aliases: ["Casillas"] },
      { answer: "Sergio Busquets", value: "143 caps", aliases: ["Busquets"] },
      { answer: "Xavi", value: "133 caps" },
      { answer: "Andres Iniesta", value: "131 caps", aliases: ["Andrés Iniesta", "Iniesta"] },
      { answer: "Andoni Zubizarreta", value: "126 caps", aliases: ["Zubizarreta"] },
      { answer: "David Silva", value: "125 caps" },
      { answer: "Xabi Alonso", value: "114 caps" },
      { answer: "Fernando Torres", value: "110 caps", aliases: ["Torres"] },
      { answer: "Cesc Fabregas", value: "110 caps", aliases: ["Cesc Fàbregas", "Fabregas"] },
    ],
  },
  {
    id: "sweden-most-caps",
    label: "Most capped Sweden players",
    question: "Can you name 10 players with the most appearances for Sweden?",
    answers: [
      { answer: "Anders Svensson", value: "148 caps" },
      { answer: "Thomas Ravelli", value: "143 caps", aliases: ["Ravelli"] },
      { answer: "Sebastian Larsson", value: "133 caps" },
      { answer: "Andreas Isaksson", value: "133 caps", aliases: ["Isaksson"] },
      { answer: "Zlatan Ibrahimovic", value: "122 caps", aliases: ["Zlatan", "Ibrahimovic"] },
      { answer: "Kim Kallstrom", value: "131 caps", aliases: ["Kim Källström", "Kallstrom"] },
      { answer: "Olof Mellberg", value: "117 caps", aliases: ["Mellberg"] },
      { answer: "Henrik Larsson", value: "106 caps" },
      { answer: "Mikael Nilsson", value: "64+ caps" },
      { answer: "Bjorn Nordqvist", value: "115 caps", aliases: ["Björn Nordqvist", "Nordqvist"] },
    ],
  },   {
    id: "xavi-most-teammate-matches",
    label: "Xavi most frequent teammates",
    question: "Can you name 10 players who played the most matches together with Xavi?",
    answers: [
      { answer: "Carles Puyol", value: "621 matches", aliases: ["Puyol"] },
      { answer: "Andres Iniesta", value: "486 matches", aliases: ["Andrés Iniesta", "Iniesta"] },
      { answer: "Victor Valdes", value: "476 matches", aliases: ["Víctor Valdés", "Valdes"] },
      { answer: "Lionel Messi", value: "399 matches", aliases: ["Messi"] },
      { answer: "Sergio Busquets", value: "386 matches", aliases: ["Busquets"] },
      { answer: "Gerard Pique", value: "373 matches", aliases: ["Gerard Piqué", "Pique"] },
      { answer: "Dani Alves", value: "343 matches", aliases: ["Daniel Alves"] },
      { answer: "Pedro", value: "263 matches", aliases: ["Pedro Rodriguez", "Pedro Rodríguez"] },
      { answer: "Javier Mascherano", value: "240+ matches", aliases: ["Mascherano"] },
      { answer: "Jordi Alba", value: "220+ matches" },
    ],
  },

  {
    id: "iniesta-most-teammate-matches",
    label: "Iniesta most frequent teammates",
    question: "Can you name 10 players who played the most matches together with Andres Iniesta?",
    answers: [
      { answer: "Lionel Messi", value: "488 matches", aliases: ["Messi"] },
      { answer: "Xavi", value: "486 matches" },
      { answer: "Victor Valdes", value: "480 matches", aliases: ["Víctor Valdés", "Valdes"] },
      { answer: "Sergio Busquets", value: "440 matches", aliases: ["Busquets"] },
      { answer: "Gerard Pique", value: "420 matches", aliases: ["Gerard Piqué", "Pique"] },
      { answer: "Carles Puyol", value: "378 matches", aliases: ["Puyol"] },
      { answer: "Dani Alves", value: "297 matches", aliases: ["Daniel Alves"] },
      { answer: "Pedro", value: "257 matches", aliases: ["Pedro Rodriguez", "Pedro Rodríguez"] },
      { answer: "Jordi Alba", value: "240+ matches" },
      { answer: "Javier Mascherano", value: "230+ matches", aliases: ["Mascherano"] },
    ],
  },

  {
    id: "zidane-most-teammate-matches",
    label: "Zidane most frequent teammates",
    question: "Can you name 10 players who played the most matches together with Zinedine Zidane?",
    answers: [
      { answer: "Bixente Lizarazu", value: "213 matches", aliases: ["Lizarazu"] },
      { answer: "Roberto Carlos", value: "203 matches" },
      { answer: "Iker Casillas", value: "197 matches", aliases: ["Casillas"] },
      { answer: "Michel Salgado", value: "190+ matches", aliases: ["Míchel Salgado", "Salgado"] },
      { answer: "Raul", value: "180+ matches", aliases: ["Raúl"] },
      { answer: "Luis Figo", value: "170+ matches", aliases: ["Figo"] },
      { answer: "Claude Makelele", value: "150+ matches", aliases: ["Claude Makélélé", "Makelele"] },
      { answer: "David Beckham", value: "140+ matches", aliases: ["Beckham"] },
      { answer: "Ronaldo", value: "130+ matches", aliases: ["R9", "Ronaldo Nazario"] },
      { answer: "Fernando Hierro", value: "120+ matches", aliases: ["Hierro"] },
    ],
  },

  {
    id: "henry-most-teammate-matches",
    label: "Henry most frequent teammates",
    question: "Can you name 10 players who played the most matches together with Thierry Henry?",
    answers: [
      { answer: "Patrick Vieira", value: "313 matches", aliases: ["Vieira"] },
      { answer: "Robert Pires", value: "287 matches", aliases: ["Robert Pirès", "Pires"] },
      { answer: "Freddie Ljungberg", value: "246 matches", aliases: ["Ljungberg"] },
      { answer: "Dennis Bergkamp", value: "230+ matches", aliases: ["Bergkamp"] },
      { answer: "Ashley Cole", value: "220+ matches" },
      { answer: "Sol Campbell", value: "200+ matches", aliases: ["Campbell"] },
      { answer: "Sylvain Wiltord", value: "180+ matches", aliases: ["Wiltord"] },
      { answer: "Lauren", value: "170+ matches" },
      { answer: "Kolo Toure", value: "160+ matches", aliases: ["Kolo Touré", "Toure"] },
      { answer: "Jens Lehmann", value: "150+ matches", aliases: ["Lehmann"] },
    ],
  },

  {
    id: "pirlo-most-teammate-matches",
    label: "Pirlo most frequent teammates",
    question: "Can you name 10 players who played the most matches together with Andrea Pirlo?",
    answers: [
      { answer: "Leonardo Bonucci", value: "178 matches", aliases: ["Bonucci"] },
      { answer: "Andriy Shevchenko", value: "168 matches", aliases: ["Shevchenko"] },
      { answer: "Alberto Gilardino", value: "165 matches", aliases: ["Gilardino"] },
      { answer: "Claudio Marchisio", value: "164 matches", aliases: ["Marchisio"] },
      { answer: "Andrea Barzagli", value: "156 matches", aliases: ["Barzagli"] },
      { answer: "Gennaro Gattuso", value: "150+ matches", aliases: ["Gattuso"] },
      { answer: "Massimo Ambrosini", value: "140+ matches", aliases: ["Ambrosini"] },
      { answer: "Clarence Seedorf", value: "130+ matches", aliases: ["Seedorf"] },
      { answer: "Gianluigi Buffon", value: "130+ matches", aliases: ["Buffon", "Gigi Buffon"] },
      { answer: "Kaka", value: "120+ matches", aliases: ["Kaká"] },
    ],
  },

  {
    id: "beckham-most-teammate-matches",
    label: "Beckham most frequent teammates",
    question: "Can you name 10 players who played the most matches together with David Beckham?",
    answers: [
      { answer: "Iker Casillas", value: "147 matches", aliases: ["Casillas"] },
      { answer: "Teddy Sheringham", value: "143 matches", aliases: ["Sheringham"] },
      { answer: "Ronny Johnsen", value: "136 matches", aliases: ["Johnsen"] },
      { answer: "Roberto Carlos", value: "135 matches" },
      { answer: "Raul", value: "130 matches", aliases: ["Raúl"] },
      { answer: "Dwight Yorke", value: "120+ matches", aliases: ["Yorke"] },
      { answer: "Ryan Giggs", value: "120+ matches", aliases: ["Giggs"] },
      { answer: "Paul Scholes", value: "110+ matches", aliases: ["Scholes"] },
      { answer: "Ruud van Nistelrooy", value: "109 matches", aliases: ["Van Nistelrooy"] },
      { answer: "Ronaldo", value: "104 matches", aliases: ["R9", "Ronaldo Nazario"] },
    ],
  },

  {
    id: "rooney-most-teammate-matches",
    label: "Rooney most frequent teammates",
    question: "Can you name 10 players who played the most matches together with Wayne Rooney?",
    answers: [
      { answer: "Michael Carrick", value: "366 matches", aliases: ["Carrick"] },
      { answer: "Rio Ferdinand", value: "349 matches", aliases: ["Ferdinand"] },
      { answer: "Patrice Evra", value: "301 matches", aliases: ["Evra"] },
      { answer: "Ryan Giggs", value: "290+ matches", aliases: ["Giggs"] },
      { answer: "Nemanja Vidic", value: "280+ matches", aliases: ["Nemanja Vidić", "Vidic"] },
      { answer: "Paul Scholes", value: "250+ matches", aliases: ["Scholes"] },
      { answer: "Cristiano Ronaldo", value: "240+ matches", aliases: ["Ronaldo", "CR7"] },
      { answer: "John O'Shea", value: "230+ matches", aliases: ["O'Shea", "John O Shea"] },
      { answer: "Darren Fletcher", value: "220+ matches", aliases: ["Fletcher"] },
      { answer: "Edwin van der Sar", value: "210+ matches", aliases: ["Van der Sar"] },
    ],
  },

  {
    id: "ucl-most-final-appearances-clubs",
    label: "Champions League final clubs",
    question: "Can you name 10 clubs with the most European Cup/Champions League final appearances?",
    answers: [
      { answer: "Real Madrid", value: "18 finals" },
      { answer: "AC Milan", value: "11 finals", aliases: ["Milan"] },
      { answer: "Bayern Munich", value: "11 finals", aliases: ["Bayern"] },
      { answer: "Liverpool", value: "10 finals" },
      { answer: "Juventus", value: "9 finals" },
      { answer: "Barcelona", value: "8 finals", aliases: ["FC Barcelona"] },
      { answer: "Benfica", value: "7 finals" },
      { answer: "Ajax", value: "6 finals" },
      { answer: "Inter", value: "6 finals", aliases: ["Inter Milan", "Internazionale"] },
      { answer: "Manchester United", value: "5 finals", aliases: ["Man United", "Man Utd"] },
    ],
  },

  {
    id: "ucl-most-titles-clubs",
    label: "Champions League title clubs",
    question: "Can you name 10 clubs with the most European Cup/Champions League titles?",
    answers: [
      { answer: "Real Madrid", value: "15 titles" },
      { answer: "AC Milan", value: "7 titles", aliases: ["Milan"] },
      { answer: "Bayern Munich", value: "6 titles", aliases: ["Bayern"] },
      { answer: "Liverpool", value: "6 titles" },
      { answer: "Barcelona", value: "5 titles", aliases: ["FC Barcelona"] },
      { answer: "Ajax", value: "4 titles" },
      { answer: "Inter", value: "3 titles", aliases: ["Inter Milan", "Internazionale"] },
      { answer: "Manchester United", value: "3 titles", aliases: ["Man United", "Man Utd"] },
      { answer: "Juventus", value: "2 titles" },
      { answer: "Benfica", value: "2 titles" },
    ],
  },

  {
    id: "world-cup-most-titles-countries",
    label: "World Cup title countries",
    question: "Can you name all countries with the most men's FIFA World Cup titles?",
    answers: [
      { answer: "Brazil", value: "5 titles" },
      { answer: "Germany", value: "4 titles", aliases: ["West Germany"] },
      { answer: "Italy", value: "4 titles" },
      { answer: "Argentina", value: "3 titles" },
      { answer: "France", value: "2 titles" },
      { answer: "Uruguay", value: "2 titles" },
      { answer: "England", value: "1 title" },
      { answer: "Spain", value: "1 title" },
    ],
  },

  {
    id: "euros-most-titles-countries",
    label: "Euro title countries",
    question: "Can you name 10 countries with the most UEFA European Championship titles or final appearances?",
    answers: [
      { answer: "Spain", value: "4 titles" },
      { answer: "Germany", value: "3 titles" },
      { answer: "France", value: "2 titles" },
      { answer: "Italy", value: "2 titles" },
      { answer: "Soviet Union", value: "1 title", aliases: ["USSR"] },
      { answer: "Czechoslovakia", value: "1 title" },
      { answer: "Netherlands", value: "1 title", aliases: ["Holland"] },
      { answer: "Denmark", value: "1 title" },
      { answer: "Greece", value: "1 title" },
      { answer: "Portugal", value: "1 title" },
    ],
  },

  {
    id: "premier-league-most-titles-clubs",
    label: "Premier League title clubs",
    question: "Can you name 10 clubs with the most English top-flight league titles?",
    answers: [
      { answer: "Manchester United", value: "20 titles", aliases: ["Man United", "Man Utd"] },
      { answer: "Liverpool", value: "20 titles" },
      { answer: "Arsenal", value: "13 titles" },
      { answer: "Everton", value: "9 titles" },
      { answer: "Manchester City", value: "10 titles", aliases: ["Man City"] },
      { answer: "Aston Villa", value: "7 titles" },
      { answer: "Sunderland", value: "6 titles" },
      { answer: "Chelsea", value: "6 titles" },
      { answer: "Newcastle United", value: "4 titles", aliases: ["Newcastle"] },
      { answer: "Sheffield Wednesday", value: "4 titles" },
    ],
  },

  {
    id: "la-liga-most-titles-clubs",
    label: "La Liga title clubs",
    question: "Can you name 10 clubs with the most La Liga titles?",
    answers: [
      { answer: "Real Madrid", value: "36 titles" },
      { answer: "Barcelona", value: "27 titles", aliases: ["FC Barcelona"] },
      { answer: "Atletico Madrid", value: "11 titles", aliases: ["Atlético Madrid", "Atleti"] },
      { answer: "Athletic Club", value: "8 titles", aliases: ["Athletic Bilbao"] },
      { answer: "Valencia", value: "6 titles" },
      { answer: "Real Sociedad", value: "2 titles" },
      { answer: "Deportivo La Coruna", value: "1 title", aliases: ["Deportivo La Coruña", "Deportivo"] },
      { answer: "Sevilla", value: "1 title" },
      { answer: "Real Betis", value: "1 title", aliases: ["Betis"] },
      { answer: "Real Valladolid", value: "0 titles / historic top-flight club", aliases: ["Valladolid"] },
    ],
  },

  {
    id: "serie-a-most-titles-clubs",
    label: "Serie A title clubs",
    question: "Can you name 10 clubs with the most Italian league titles?",
    answers: [
      { answer: "Juventus", value: "36 titles" },
      { answer: "Inter", value: "20 titles", aliases: ["Inter Milan", "Internazionale"] },
      { answer: "AC Milan", value: "19 titles", aliases: ["Milan"] },
      { answer: "Genoa", value: "9 titles" },
      { answer: "Torino", value: "7 titles" },
      { answer: "Bologna", value: "7 titles" },
      { answer: "Pro Vercelli", value: "7 titles" },
      { answer: "Roma", value: "3 titles" },
      { answer: "Napoli", value: "3 titles" },
      { answer: "Lazio", value: "2 titles" },
    ],
  },

  {
    id: "bundesliga-most-titles-clubs",
    label: "German league title clubs",
    question: "Can you name 10 clubs with the most German league titles?",
    answers: [
      { answer: "Bayern Munich", value: "33 titles", aliases: ["Bayern"] },
      { answer: "Nurnberg", value: "9 titles", aliases: ["Nürnberg", "FC Nurnberg"] },
      { answer: "Borussia Dortmund", value: "8 titles", aliases: ["Dortmund", "BVB"] },
      { answer: "Schalke", value: "7 titles", aliases: ["Schalke 04"] },
      { answer: "Hamburger SV", value: "6 titles", aliases: ["Hamburg", "HSV"] },
      { answer: "VfB Stuttgart", value: "5 titles", aliases: ["Stuttgart"] },
      { answer: "Borussia Monchengladbach", value: "5 titles", aliases: ["Borussia Mönchengladbach", "Gladbach"] },
      { answer: "Werder Bremen", value: "4 titles", aliases: ["Bremen"] },
      { answer: "Kaiserslautern", value: "4 titles" },
      { answer: "Koln", value: "3 titles", aliases: ["Köln", "Cologne"] },
    ],
  },

  {
    id: "ligue-1-most-titles-clubs",
    label: "French league title clubs",
    question: "Can you name 10 clubs with the most French league titles?",
    answers: [
      { answer: "Paris Saint-Germain", value: "12 titles", aliases: ["PSG"] },
      { answer: "Saint-Etienne", value: "10 titles", aliases: ["Saint-Étienne"] },
      { answer: "Marseille", value: "9 titles" },
      { answer: "Monaco", value: "8 titles" },
      { answer: "Nantes", value: "8 titles" },
      { answer: "Lyon", value: "7 titles" },
      { answer: "Bordeaux", value: "6 titles" },
      { answer: "Reims", value: "6 titles" },
      { answer: "Lille", value: "4 titles" },
      { answer: "Nice", value: "4 titles" },
    ],
  },

  {
    id: "ucl-final-goalscorers-modern",
    label: "Modern UCL final goalscorers",
    question: "Can you name 10 players who scored in a Champions League final since 2000?",
    answers: [
      { answer: "Zinedine Zidane", value: "2002 final", aliases: ["Zidane"] },
      { answer: "Hernan Crespo", value: "2005 final", aliases: ["Hernán Crespo", "Crespo"] },
      { answer: "Steven Gerrard", value: "2005 final", aliases: ["Gerrard"] },
      { answer: "Samuel Eto'o", value: "2006/2009 finals", aliases: ["Samuel Etoo", "Eto'o", "Etoo"] },
      { answer: "Lionel Messi", value: "2009/2011 finals", aliases: ["Messi"] },
      { answer: "Didier Drogba", value: "2012 final", aliases: ["Drogba"] },
      { answer: "Mario Mandzukic", value: "2013/2017 finals", aliases: ["Mario Mandžukić", "Mandzukic"] },
      { answer: "Cristiano Ronaldo", value: "2008/2014/2017 finals", aliases: ["Ronaldo", "CR7"] },
      { answer: "Gareth Bale", value: "2014/2018 finals", aliases: ["Bale"] },
      { answer: "Vinicius Junior", value: "2022/2024 finals", aliases: ["Vinícius Júnior", "Vini Jr"] },
    ],
  },

  {
    id: "world-cup-final-goalscorers-modern",
    label: "Modern World Cup final scorers",
    question: "Can you name 10 players who scored in a men's World Cup final since 1998?",
    answers: [
      { answer: "Zinedine Zidane", value: "1998 and 2006 finals", aliases: ["Zidane"] },
      { answer: "Emmanuel Petit", value: "1998 final", aliases: ["Petit"] },
      { answer: "Ronaldo", value: "2002 final", aliases: ["R9", "Ronaldo Nazario"] },
      { answer: "Marco Materazzi", value: "2006 final", aliases: ["Materazzi"] },
      { answer: "Andres Iniesta", value: "2010 final", aliases: ["Andrés Iniesta", "Iniesta"] },
      { answer: "Mario Gotze", value: "2014 final", aliases: ["Mario Götze", "Gotze"] },
      { answer: "Antoine Griezmann", value: "2018 final", aliases: ["Griezmann"] },
      { answer: "Kylian Mbappe", value: "2018 and 2022 finals", aliases: ["Kylian Mbappé", "Mbappe"] },
      { answer: "Lionel Messi", value: "2022 final", aliases: ["Messi"] },
      { answer: "Angel Di Maria", value: "2022 final", aliases: ["Ángel Di María", "Di Maria"] },
    ],
  },

  {
    id: "players-with-most-ucl-titles",
    label: "Players with most Champions League titles",
    question: "Can you name 10 players with the most European Cup/Champions League titles?",
    answers: [
      { answer: "Francisco Gento", value: "6 titles", aliases: ["Gento"] },
      { answer: "Luka Modric", value: "6 titles", aliases: ["Luka Modrić", "Modric"] },
      { answer: "Toni Kroos", value: "6 titles", aliases: ["Kroos"] },
      { answer: "Dani Carvajal", value: "6 titles", aliases: ["Daniel Carvajal", "Carvajal"] },
      { answer: "Nacho Fernandez", value: "6 titles", aliases: ["Nacho Fernández", "Nacho"] },
      { answer: "Cristiano Ronaldo", value: "5 titles", aliases: ["Ronaldo", "CR7"] },
      { answer: "Karim Benzema", value: "5 titles", aliases: ["Benzema"] },
      { answer: "Gareth Bale", value: "5 titles", aliases: ["Bale"] },
      { answer: "Marcelo", value: "5 titles" },
      { answer: "Casemiro", value: "5 titles" },
    ],
  },  {
    id: "lampard-most-teammate-matches",
    label: "Lampard most frequent teammates",
    question: "Can you name 10 players who played the most matches together with Frank Lampard?",
    answers: [
      { answer: "John Terry", value: "581 matches", aliases: ["Terry"] },
      { answer: "Petr Cech", value: "398 matches", aliases: ["Petr Čech", "Cech"] },
      { answer: "Ashley Cole", value: "351 matches" },
      { answer: "Joe Cole", value: "343 matches" },
      { answer: "Didier Drogba", value: "300 matches", aliases: ["Drogba"] },
      { answer: "Michael Essien", value: "280+ matches", aliases: ["Essien"] },
      { answer: "Branislav Ivanovic", value: "250+ matches", aliases: ["Branislav Ivanović", "Ivanovic"] },
      { answer: "Florent Malouda", value: "240+ matches", aliases: ["Malouda"] },
      { answer: "Ricardo Carvalho", value: "230+ matches", aliases: ["Carvalho"] },
      { answer: "Paulo Ferreira", value: "220+ matches", aliases: ["Ferreira"] },
    ],
  },

  {
    id: "ronaldo-nazario-most-teammate-matches",
    label: "R9 most frequent teammates",
    question: "Can you name 10 players who played the most matches together with Ronaldo Nazario?",
    answers: [
      { answer: "Roberto Carlos", value: "278 matches" },
      { answer: "Iker Casillas", value: "165 matches", aliases: ["Casillas"] },
      { answer: "Luis Figo", value: "164 matches", aliases: ["Luís Figo", "Figo"] },
      { answer: "Michel Salgado", value: "146 matches", aliases: ["Míchel Salgado", "Salgado"] },
      { answer: "Raul", value: "140+ matches", aliases: ["Raúl"] },
      { answer: "Zinedine Zidane", value: "130+ matches", aliases: ["Zidane"] },
      { answer: "David Beckham", value: "100+ matches", aliases: ["Beckham"] },
      { answer: "Guti", value: "100+ matches" },
      { answer: "Ivan Helguera", value: "90+ matches", aliases: ["Helguera"] },
      { answer: "Ronaldinho", value: "39 matches" },
    ],
  },

  {
    id: "robben-most-teammate-matches",
    label: "Robben most frequent teammates",
    question: "Can you name 10 players who played the most matches together with Arjen Robben?",
    answers: [
      { answer: "Philipp Lahm", value: "212 matches", aliases: ["Lahm"] },
      { answer: "David Alaba", value: "208 matches", aliases: ["Alaba"] },
      { answer: "Manuel Neuer", value: "204 matches", aliases: ["Neuer"] },
      { answer: "Franck Ribery", value: "187 matches", aliases: ["Franck Ribéry", "Ribery"] },
      { answer: "Thomas Muller", value: "180+ matches", aliases: ["Thomas Müller", "Muller"] },
      { answer: "Bastian Schweinsteiger", value: "170+ matches", aliases: ["Schweinsteiger"] },
      { answer: "Jerome Boateng", value: "160+ matches", aliases: ["Jérôme Boateng", "Boateng"] },
      { answer: "Robert Lewandowski", value: "150+ matches", aliases: ["Lewandowski"] },
      { answer: "Javi Martinez", value: "140+ matches", aliases: ["Javi Martínez"] },
      { answer: "Rafinha", value: "130+ matches" },
    ],
  },

  {
    id: "man-united-top-scorers",
    label: "Manchester United top scorers",
    question: "Can you name 10 of Manchester United's all-time top scorers?",
    answers: [
      { answer: "Wayne Rooney", value: "253 goals", aliases: ["Rooney"] },
      { answer: "Bobby Charlton", value: "249 goals", aliases: ["Charlton"] },
      { answer: "Denis Law", value: "237 goals", aliases: ["Law"] },
      { answer: "Jack Rowley", value: "211 goals", aliases: ["Rowley"] },
      { answer: "Dennis Viollet", value: "179 goals", aliases: ["Viollet"] },
      { answer: "George Best", value: "179 goals", aliases: ["Best"] },
      { answer: "Joe Spence", value: "168 goals", aliases: ["Spence"] },
      { answer: "Ryan Giggs", value: "168 goals", aliases: ["Giggs"] },
      { answer: "Mark Hughes", value: "163 goals", aliases: ["Hughes"] },
      { answer: "Paul Scholes", value: "155 goals", aliases: ["Scholes"] },
    ],
  },

  {
    id: "arsenal-top-scorers",
    label: "Arsenal top scorers",
    question: "Can you name 10 of Arsenal's all-time top scorers?",
    answers: [
      { answer: "Thierry Henry", value: "228 goals", aliases: ["Henry"] },
      { answer: "Ian Wright", value: "185 goals", aliases: ["Wright"] },
      { answer: "Robin van Persie", value: "132 goals", aliases: ["Van Persie"] },
      { answer: "Dennis Bergkamp", value: "120 goals", aliases: ["Bergkamp"] },
      { answer: "Theo Walcott", value: "108 goals", aliases: ["Walcott"] },
      { answer: "Cliff Bastin", value: "178 goals", aliases: ["Bastin"] },
      { answer: "John Radford", value: "149 goals", aliases: ["Radford"] },
      { answer: "Jimmy Brain", value: "139 goals", aliases: ["Brain"] },
      { answer: "Ted Drake", value: "139 goals", aliases: ["Drake"] },
      { answer: "Doug Lishman", value: "137 goals", aliases: ["Lishman"] },
    ],
  },

  {
    id: "chelsea-top-scorers",
    label: "Chelsea top scorers",
    question: "Can you name 10 of Chelsea's all-time top scorers?",
    answers: [
      { answer: "Frank Lampard", value: "211 goals", aliases: ["Lampard"] },
      { answer: "Bobby Tambling", value: "202 goals", aliases: ["Tambling"] },
      { answer: "Kerry Dixon", value: "193 goals", aliases: ["Dixon"] },
      { answer: "Didier Drogba", value: "164 goals", aliases: ["Drogba"] },
      { answer: "Roy Bentley", value: "150 goals", aliases: ["Bentley"] },
      { answer: "Peter Osgood", value: "150 goals", aliases: ["Osgood"] },
      { answer: "Jimmy Greaves", value: "132 goals", aliases: ["Greaves"] },
      { answer: "Eden Hazard", value: "110 goals", aliases: ["Hazard"] },
      { answer: "George Mills", value: "125 goals", aliases: ["Mills"] },
      { answer: "George Hilsdon", value: "108 goals", aliases: ["Hilsdon"] },
    ],
  },

  {
    id: "liverpool-top-scorers",
    label: "Liverpool top scorers",
    question: "Can you name 10 of Liverpool's all-time top scorers?",
    answers: [
      { answer: "Ian Rush", value: "346 goals", aliases: ["Rush"] },
      { answer: "Roger Hunt", value: "285 goals", aliases: ["Hunt"] },
      { answer: "Gordon Hodgson", value: "241 goals", aliases: ["Hodgson"] },
      { answer: "Billy Liddell", value: "228 goals", aliases: ["Liddell"] },
      { answer: "Steven Gerrard", value: "186 goals", aliases: ["Gerrard"] },
      { answer: "Robbie Fowler", value: "183 goals", aliases: ["Fowler"] },
      { answer: "Kenny Dalglish", value: "172 goals", aliases: ["Dalglish"] },
      { answer: "Michael Owen", value: "158 goals", aliases: ["Owen"] },
      { answer: "Harry Chambers", value: "151 goals", aliases: ["Chambers"] },
      { answer: "Sam Raybould", value: "130 goals", aliases: ["Raybould"] },
    ],
  },

  {
    id: "tottenham-top-scorers",
    label: "Tottenham top scorers",
    question: "Can you name 10 of Tottenham Hotspur's all-time top scorers?",
    answers: [
      { answer: "Harry Kane", value: "280 goals", aliases: ["Kane"] },
      { answer: "Jimmy Greaves", value: "266 goals", aliases: ["Greaves"] },
      { answer: "Bobby Smith", value: "208 goals", aliases: ["Smith"] },
      { answer: "Martin Chivers", value: "174 goals", aliases: ["Chivers"] },
      { answer: "Cliff Jones", value: "159 goals", aliases: ["Jones"] },
      { answer: "Jermain Defoe", value: "143 goals", aliases: ["Defoe"] },
      { answer: "George Hunt", value: "138 goals", aliases: ["Hunt"] },
      { answer: "Son Heung-min", value: "160+ goals", aliases: ["Heung-Min Son", "Son"] },
      { answer: "Len Duquemin", value: "134 goals", aliases: ["Duquemin"] },
      { answer: "Alan Gilzean", value: "133 goals", aliases: ["Gilzean"] },
    ],
  },

  {
    id: "bayern-top-scorers",
    label: "Bayern Munich top scorers",
    question: "Can you name 10 of Bayern Munich's all-time top scorers?",
    answers: [
      { answer: "Gerd Muller", value: "566 goals", aliases: ["Gerd Müller", "Muller"] },
      { answer: "Robert Lewandowski", value: "344 goals", aliases: ["Lewandowski"] },
      { answer: "Thomas Muller", value: "240+ goals", aliases: ["Thomas Müller", "Muller"] },
      { answer: "Karl-Heinz Rummenigge", value: "217 goals", aliases: ["Rummenigge"] },
      { answer: "Rainer Ohlhauser", value: "167 goals", aliases: ["Ohlhauser"] },
      { answer: "Roland Wohlfarth", value: "155 goals", aliases: ["Wohlfarth"] },
      { answer: "Dieter Hoeness", value: "145 goals", aliases: ["Dieter Hoeneß", "Hoeness"] },
      { answer: "Giovane Elber", value: "140 goals", aliases: ["Elber", "Élber"] },
      { answer: "Arjen Robben", value: "144 goals", aliases: ["Robben"] },
      { answer: "Mehmet Scholl", value: "117 goals", aliases: ["Scholl"] },
    ],
  },

  {
    id: "juventus-top-scorers",
    label: "Juventus top scorers",
    question: "Can you name 10 of Juventus' all-time top scorers?",
    answers: [
      { answer: "Alessandro Del Piero", value: "290 goals", aliases: ["Del Piero"] },
      { answer: "Giampiero Boniperti", value: "179 goals", aliases: ["Boniperti"] },
      { answer: "Roberto Bettega", value: "178 goals", aliases: ["Bettega"] },
      { answer: "David Trezeguet", value: "171 goals", aliases: ["Trezeguet"] },
      { answer: "Omar Sivori", value: "167 goals", aliases: ["Sívori", "Sivori"] },
      { answer: "Felice Borel", value: "157 goals", aliases: ["Borel"] },
      { answer: "Pietro Anastasi", value: "130 goals", aliases: ["Anastasi"] },
      { answer: "John Hansen", value: "124 goals" },
      { answer: "Roberto Baggio", value: "115 goals", aliases: ["Baggio"] },
      { answer: "Cristiano Ronaldo", value: "101 goals", aliases: ["Ronaldo", "CR7"] },
    ],
  },

  {
    id: "ac-milan-top-scorers",
    label: "AC Milan top scorers",
    question: "Can you name 10 of AC Milan's all-time top scorers?",
    answers: [
      { answer: "Gunnar Nordahl", value: "221 goals", aliases: ["Nordahl"] },
      { answer: "Andriy Shevchenko", value: "175 goals", aliases: ["Shevchenko"] },
      { answer: "Gianni Rivera", value: "164 goals", aliases: ["Rivera"] },
      { answer: "Jose Altafini", value: "161 goals", aliases: ["José Altafini", "Altafini"] },
      { answer: "Aldo Boffi", value: "136 goals", aliases: ["Boffi"] },
      { answer: "Filippo Inzaghi", value: "126 goals", aliases: ["Inzaghi", "Pippo"] },
      { answer: "Marco van Basten", value: "125 goals", aliases: ["Van Basten"] },
      { answer: "Giuseppe Santagostino", value: "106 goals", aliases: ["Santagostino"] },
      { answer: "Kaka", value: "104 goals", aliases: ["Kaká"] },
      { answer: "Pierino Prati", value: "102 goals", aliases: ["Prati"] },
    ],
  },

  {
    id: "inter-top-scorers",
    label: "Inter top scorers",
    question: "Can you name 10 of Inter Milan's all-time top scorers?",
    answers: [
      { answer: "Giuseppe Meazza", value: "284 goals", aliases: ["Meazza"] },
      { answer: "Alessandro Altobelli", value: "209 goals", aliases: ["Altobelli"] },
      { answer: "Roberto Boninsegna", value: "171 goals", aliases: ["Boninsegna"] },
      { answer: "Sandro Mazzola", value: "160 goals", aliases: ["Mazzola"] },
      { answer: "Luigi Cevenini", value: "158 goals", aliases: ["Cevenini"] },
      { answer: "Benito Lorenzi", value: "143 goals", aliases: ["Lorenzi"] },
      { answer: "Istvan Nyers", value: "133 goals", aliases: ["István Nyers", "Nyers"] },
      { answer: "Mauro Icardi", value: "124 goals", aliases: ["Icardi"] },
      { answer: "Christian Vieri", value: "123 goals", aliases: ["Vieri"] },
      { answer: "Lautaro Martinez", value: "120+ goals", aliases: ["Lautaro Martínez", "Lautaro"] },
    ],
  },

  {
    id: "ajax-top-scorers",
    label: "Ajax top scorers",
    question: "Can you name 10 of Ajax's all-time top scorers?",
    answers: [
      { answer: "Piet van Reenen", value: "273 goals", aliases: ["Van Reenen"] },
      { answer: "Johan Cruyff", value: "194 goals", aliases: ["Cruijff", "Cruyff"] },
      { answer: "Sjaak Swart", value: "175 goals", aliases: ["Swart"] },
      { answer: "Henk Groot", value: "149 goals", aliases: ["Groot"] },
      { answer: "Jari Litmanen", value: "133 goals", aliases: ["Litmanen"] },
      { answer: "Marco van Basten", value: "128 goals", aliases: ["Van Basten"] },
      { answer: "Dennis Bergkamp", value: "122 goals", aliases: ["Bergkamp"] },
      { answer: "Klaas-Jan Huntelaar", value: "158 goals", aliases: ["Huntelaar", "Klaas Jan Huntelaar"] },
      { answer: "Luis Suarez", value: "111 goals", aliases: ["Luis Suárez", "Suarez"] },
      { answer: "Wesley Sneijder", value: "58 goals", aliases: ["Sneijder"] },
    ],
  },

  {
    id: "barcelona-top-scorers",
    label: "Barcelona top scorers",
    question: "Can you name 10 of Barcelona's all-time top scorers?",
    answers: [
      { answer: "Lionel Messi", value: "672 goals", aliases: ["Messi"] },
      { answer: "Cesar Rodriguez", value: "232 goals", aliases: ["César Rodríguez", "Cesar"] },
      { answer: "Luis Suarez", value: "198 goals", aliases: ["Luis Suárez", "Suarez"] },
      { answer: "Ladislao Kubala", value: "194 goals", aliases: ["Kubala"] },
      { answer: "Josep Samitier", value: "184 goals", aliases: ["Samitier"] },
      { answer: "Josep Escola", value: "167 goals", aliases: ["Josep Escolà", "Escola"] },
      { answer: "Paulino Alcantara", value: "143 goals", aliases: ["Paulino Alcántara", "Alcantara"] },
      { answer: "Samuel Eto'o", value: "130 goals", aliases: ["Samuel Etoo", "Eto'o", "Etoo"] },
      { answer: "Rivaldo", value: "130 goals" },
      { answer: "Evaristo", value: "105 goals" },
    ],
  },

  {
    id: "atletico-madrid-top-scorers",
    label: "Atletico Madrid top scorers",
    question: "Can you name 10 of Atletico Madrid's all-time top scorers?",
    answers: [
      { answer: "Antoine Griezmann", value: "180+ goals", aliases: ["Griezmann"] },
      { answer: "Luis Aragones", value: "172 goals", aliases: ["Luis Aragonés", "Aragones"] },
      { answer: "Adrian Escudero", value: "169 goals", aliases: ["Escudero"] },
      { answer: "Paco Campos", value: "158 goals", aliases: ["Campos"] },
      { answer: "Jose Eulogio Garate", value: "136 goals", aliases: ["José Eulogio Gárate", "Garate"] },
      { answer: "Fernando Torres", value: "129 goals", aliases: ["Torres"] },
      { answer: "Sergio Aguero", value: "101 goals", aliases: ["Sergio Agüero", "Aguero"] },
      { answer: "Diego Forlan", value: "96 goals", aliases: ["Diego Forlán", "Forlan"] },
      { answer: "Diego Costa", value: "83 goals", aliases: ["Costa"] },
      { answer: "Radamel Falcao", value: "70 goals", aliases: ["Falcao"] },
    ],
  },

  {
    id: "most-capped-portugal-players",
    label: "Most capped Portugal players",
    question: "Can you name 10 players with the most appearances for Portugal?",
    answers: [
      { answer: "Cristiano Ronaldo", value: "200+ caps", aliases: ["Ronaldo", "CR7"] },
      { answer: "Joao Moutinho", value: "146 caps", aliases: ["João Moutinho", "Moutinho"] },
      { answer: "Pepe", value: "140+ caps" },
      { answer: "Luis Figo", value: "127 caps", aliases: ["Luís Figo", "Figo"] },
      { answer: "Nani", value: "112 caps" },
      { answer: "Fernando Couto", value: "110 caps", aliases: ["Couto"] },
      { answer: "Bruno Alves", value: "96 caps" },
      { answer: "Rui Patricio", value: "100+ caps", aliases: ["Rui Patrício", "Patricio"] },
      { answer: "Ricardo Carvalho", value: "89 caps", aliases: ["Carvalho"] },
      { answer: "Bernardo Silva", value: "90+ caps", aliases: ["Bernardo"] },
    ],
  },

  {
    id: "most-capped-italy-players",
    label: "Most capped Italy players",
    question: "Can you name 10 players with the most appearances for Italy?",
    answers: [
      { answer: "Gianluigi Buffon", value: "176 caps", aliases: ["Buffon", "Gigi Buffon"] },
      { answer: "Fabio Cannavaro", value: "136 caps", aliases: ["Cannavaro"] },
      { answer: "Paolo Maldini", value: "126 caps", aliases: ["Maldini"] },
      { answer: "Leonardo Bonucci", value: "120+ caps", aliases: ["Bonucci"] },
      { answer: "Daniele De Rossi", value: "117 caps", aliases: ["De Rossi"] },
      { answer: "Giorgio Chiellini", value: "117 caps", aliases: ["Chiellini"] },
      { answer: "Andrea Pirlo", value: "116 caps", aliases: ["Pirlo"] },
      { answer: "Dino Zoff", value: "112 caps", aliases: ["Zoff"] },
      { answer: "Giacinto Facchetti", value: "94 caps", aliases: ["Facchetti"] },
      { answer: "Alessandro Del Piero", value: "91 caps", aliases: ["Del Piero"] },
    ],
  },

  {
    id: "most-capped-germany-players",
    label: "Most capped Germany players",
    question: "Can you name 10 players with the most appearances for Germany?",
    answers: [
      { answer: "Lothar Matthaus", value: "150 caps", aliases: ["Lothar Matthäus", "Matthaus"] },
      { answer: "Miroslav Klose", value: "137 caps", aliases: ["Klose"] },
      { answer: "Thomas Muller", value: "130+ caps", aliases: ["Thomas Müller", "Muller"] },
      { answer: "Lukas Podolski", value: "130 caps", aliases: ["Podolski"] },
      { answer: "Bastian Schweinsteiger", value: "121 caps", aliases: ["Schweinsteiger"] },
      { answer: "Manuel Neuer", value: "120+ caps", aliases: ["Neuer"] },
      { answer: "Philipp Lahm", value: "113 caps", aliases: ["Lahm"] },
      { answer: "Jurgen Klinsmann", value: "108 caps", aliases: ["Jürgen Klinsmann", "Klinsmann"] },
      { answer: "Toni Kroos", value: "114 caps", aliases: ["Kroos"] },
      { answer: "Jurgen Kohler", value: "105 caps", aliases: ["Jürgen Kohler", "Kohler"] },
    ],
  },

  {
    id: "most-capped-netherlands-players",
    label: "Most capped Netherlands players",
    question: "Can you name 10 players with the most appearances for the Netherlands?",
    answers: [
      { answer: "Wesley Sneijder", value: "134 caps", aliases: ["Sneijder"] },
      { answer: "Edwin van der Sar", value: "130 caps", aliases: ["Van der Sar"] },
      { answer: "Frank de Boer", value: "112 caps", aliases: ["De Boer"] },
      { answer: "Rafael van der Vaart", value: "109 caps", aliases: ["Van der Vaart"] },
      { answer: "Giovanni van Bronckhorst", value: "106 caps", aliases: ["Van Bronckhorst"] },
      { answer: "Dirk Kuyt", value: "104 caps", aliases: ["Kuyt"] },
      { answer: "Robin van Persie", value: "102 caps", aliases: ["Van Persie"] },
      { answer: "Arjen Robben", value: "96 caps", aliases: ["Robben"] },
      { answer: "Clarence Seedorf", value: "87 caps", aliases: ["Seedorf"] },
      { answer: "Marc Overmars", value: "86 caps", aliases: ["Overmars"] },
    ],
  },

  {
    id: "most-capped-brazil-players",
    label: "Most capped Brazil players",
    question: "Can you name 10 players with the most appearances for Brazil?",
    answers: [
      { answer: "Cafu", value: "142 caps" },
      { answer: "Neymar", value: "125+ caps" },
      { answer: "Roberto Carlos", value: "125 caps" },
      { answer: "Dani Alves", value: "120+ caps", aliases: ["Daniel Alves"] },
      { answer: "Thiago Silva", value: "110+ caps" },
      { answer: "Lucio", value: "105 caps", aliases: ["Lúcio"] },
      { answer: "Claudio Taffarel", value: "101 caps", aliases: ["Taffarel"] },
      { answer: "Robinho", value: "100 caps" },
      { answer: "Ronaldo", value: "98 caps", aliases: ["R9", "Ronaldo Nazario"] },
      { answer: "Ronaldinho", value: "97 caps" },
    ],
  },  {
    id: "gerrard-most-teammate-matches",
    label: "Gerrard most frequent teammates",
    question: "Can you name 10 players who played the most matches together with Steven Gerrard?",
    answers: [
      { answer: "Jamie Carragher", value: "450+ matches", aliases: ["Carragher"] },
      { answer: "Sami Hyypia", value: "300+ matches", aliases: ["Hyypia", "Sami Hyypiä"] },
      { answer: "Pepe Reina", value: "300+ matches", aliases: ["Reina"] },
      { answer: "John Arne Riise", value: "250+ matches", aliases: ["Riise"] },
      { answer: "Xabi Alonso", value: "250+ matches" },
      { answer: "Dirk Kuyt", value: "230+ matches", aliases: ["Kuyt"] },
      { answer: "Martin Skrtel", value: "214 matches", aliases: ["Martin Škrtel", "Skrtel"] },
      { answer: "Glen Johnson", value: "187 matches" },
      { answer: "Lucas Leiva", value: "187 matches", aliases: ["Lucas"] },
      { answer: "Steve Finnan", value: "185 matches", aliases: ["Finnan"] },
    ],
  },

  {
    id: "drogba-most-teammate-matches",
    label: "Drogba most frequent teammates",
    question: "Can you name 10 players who played the most matches together with Didier Drogba?",
    answers: [
      { answer: "Frank Lampard", value: "300 matches", aliases: ["Lampard"] },
      { answer: "John Terry", value: "290+ matches", aliases: ["Terry"] },
      { answer: "Petr Cech", value: "270+ matches", aliases: ["Petr Čech", "Cech"] },
      { answer: "Ashley Cole", value: "240+ matches" },
      { answer: "Michael Essien", value: "220+ matches", aliases: ["Essien"] },
      { answer: "Florent Malouda", value: "200+ matches", aliases: ["Malouda"] },
      { answer: "Salomon Kalou", value: "190+ matches", aliases: ["Kalou"] },
      { answer: "John Obi Mikel", value: "180+ matches", aliases: ["Mikel", "Obi Mikel"] },
      { answer: "Branislav Ivanovic", value: "170+ matches", aliases: ["Branislav Ivanović", "Ivanovic"] },
      { answer: "Ricardo Carvalho", value: "160+ matches", aliases: ["Carvalho"] },
    ],
  },

  {
    id: "terry-most-teammate-matches",
    label: "Terry most frequent teammates",
    question: "Can you name 10 players who played the most matches together with John Terry?",
    answers: [
      { answer: "Frank Lampard", value: "581 matches", aliases: ["Lampard"] },
      { answer: "Petr Cech", value: "400+ matches", aliases: ["Petr Čech", "Cech"] },
      { answer: "Ashley Cole", value: "350+ matches" },
      { answer: "Didier Drogba", value: "290+ matches", aliases: ["Drogba"] },
      { answer: "Michael Essien", value: "280+ matches", aliases: ["Essien"] },
      { answer: "Branislav Ivanovic", value: "270+ matches", aliases: ["Branislav Ivanović", "Ivanovic"] },
      { answer: "Joe Cole", value: "250+ matches" },
      { answer: "Florent Malouda", value: "240+ matches", aliases: ["Malouda"] },
      { answer: "Ricardo Carvalho", value: "230+ matches", aliases: ["Carvalho"] },
      { answer: "Paulo Ferreira", value: "220+ matches", aliases: ["Ferreira"] },
    ],
  },

  {
    id: "scholes-most-teammate-matches",
    label: "Scholes most frequent teammates",
    question: "Can you name 10 players who played the most matches together with Paul Scholes?",
    answers: [
      { answer: "Ryan Giggs", value: "600+ matches", aliases: ["Giggs"] },
      { answer: "Gary Neville", value: "500+ matches", aliases: ["Neville"] },
      { answer: "Roy Keane", value: "400+ matches", aliases: ["Keane"] },
      { answer: "David Beckham", value: "350+ matches", aliases: ["Beckham"] },
      { answer: "Nicky Butt", value: "300+ matches", aliases: ["Butt"] },
      { answer: "Wayne Rooney", value: "250+ matches", aliases: ["Rooney"] },
      { answer: "Rio Ferdinand", value: "250+ matches", aliases: ["Ferdinand"] },
      { answer: "Cristiano Ronaldo", value: "200+ matches", aliases: ["Ronaldo", "CR7"] },
      { answer: "Darren Fletcher", value: "200+ matches", aliases: ["Fletcher"] },
      { answer: "Edwin van der Sar", value: "190+ matches", aliases: ["Van der Sar"] },
    ],
  },

  {
    id: "giggs-most-teammate-matches",
    label: "Giggs most frequent teammates",
    question: "Can you name 10 players who played the most matches together with Ryan Giggs?",
    answers: [
      { answer: "Paul Scholes", value: "600+ matches", aliases: ["Scholes"] },
      { answer: "Gary Neville", value: "500+ matches", aliases: ["Neville"] },
      { answer: "Roy Keane", value: "400+ matches", aliases: ["Keane"] },
      { answer: "David Beckham", value: "350+ matches", aliases: ["Beckham"] },
      { answer: "Nicky Butt", value: "300+ matches", aliases: ["Butt"] },
      { answer: "Wayne Rooney", value: "290+ matches", aliases: ["Rooney"] },
      { answer: "Rio Ferdinand", value: "280+ matches", aliases: ["Ferdinand"] },
      { answer: "Cristiano Ronaldo", value: "240+ matches", aliases: ["Ronaldo", "CR7"] },
      { answer: "John O'Shea", value: "230+ matches", aliases: ["O'Shea", "John O Shea"] },
      { answer: "Darren Fletcher", value: "220+ matches", aliases: ["Fletcher"] },
    ],
  },

  {
    id: "lahm-most-teammate-matches",
    label: "Lahm most frequent teammates",
    question: "Can you name 10 players who played the most matches together with Philipp Lahm?",
    answers: [
      { answer: "Bastian Schweinsteiger", value: "400+ matches", aliases: ["Schweinsteiger"] },
      { answer: "Thomas Muller", value: "350+ matches", aliases: ["Thomas Müller", "Muller"] },
      { answer: "Manuel Neuer", value: "300+ matches", aliases: ["Neuer"] },
      { answer: "Franck Ribery", value: "300+ matches", aliases: ["Franck Ribéry", "Ribery"] },
      { answer: "Arjen Robben", value: "212 matches", aliases: ["Robben"] },
      { answer: "David Alaba", value: "200+ matches", aliases: ["Alaba"] },
      { answer: "Jerome Boateng", value: "200+ matches", aliases: ["Jérôme Boateng", "Boateng"] },
      { answer: "Toni Kroos", value: "150+ matches", aliases: ["Kroos"] },
      { answer: "Miroslav Klose", value: "140+ matches", aliases: ["Klose"] },
      { answer: "Mario Gomez", value: "130+ matches", aliases: ["Mario Gómez", "Gomez"] },
    ],
  },

  {
    id: "del-piero-most-teammate-matches",
    label: "Del Piero most frequent teammates",
    question: "Can you name 10 players who played the most matches together with Alessandro Del Piero?",
    answers: [
      { answer: "Gianluigi Buffon", value: "300+ matches", aliases: ["Buffon", "Gigi Buffon"] },
      { answer: "Pavel Nedved", value: "250+ matches", aliases: ["Pavel Nedvěd", "Nedved"] },
      { answer: "David Trezeguet", value: "250+ matches", aliases: ["Trezeguet"] },
      { answer: "Mauro Camoranesi", value: "200+ matches", aliases: ["Camoranesi"] },
      { answer: "Gianluca Zambrotta", value: "180+ matches", aliases: ["Zambrotta"] },
      { answer: "Fabio Cannavaro", value: "150+ matches", aliases: ["Cannavaro"] },
      { answer: "Ciro Ferrara", value: "150+ matches", aliases: ["Ferrara"] },
      { answer: "Mark Iuliano", value: "140+ matches", aliases: ["Iuliano"] },
      { answer: "Alessio Tacchinardi", value: "140+ matches", aliases: ["Tacchinardi"] },
      { answer: "Edgar Davids", value: "130+ matches", aliases: ["Davids"] },
    ],
  },

  {
    id: "totti-most-teammate-matches",
    label: "Totti most frequent teammates",
    question: "Can you name 10 players who played the most matches together with Francesco Totti?",
    answers: [
      { answer: "Daniele De Rossi", value: "400+ matches", aliases: ["De Rossi"] },
      { answer: "Simone Perrotta", value: "300+ matches", aliases: ["Perrotta"] },
      { answer: "Christian Panucci", value: "250+ matches", aliases: ["Panucci"] },
      { answer: "Alessandro Florenzi", value: "200+ matches", aliases: ["Florenzi"] },
      { answer: "Mirko Vucinic", value: "180+ matches", aliases: ["Mirko Vučinić", "Vucinic"] },
      { answer: "Rodrigo Taddei", value: "180+ matches", aliases: ["Taddei"] },
      { answer: "Philippe Mexes", value: "170+ matches", aliases: ["Philippe Mexès", "Mexes"] },
      { answer: "David Pizarro", value: "160+ matches", aliases: ["Pizarro"] },
      { answer: "Vincenzo Montella", value: "150+ matches", aliases: ["Montella"] },
      { answer: "Gabriel Batistuta", value: "80+ matches", aliases: ["Batistuta"] },
    ],
  },

  {
    id: "maldini-most-teammate-matches",
    label: "Maldini most frequent teammates",
    question: "Can you name 10 players who played the most matches together with Paolo Maldini?",
    answers: [
      { answer: "Alessandro Costacurta", value: "600+ matches", aliases: ["Costacurta"] },
      { answer: "Franco Baresi", value: "400+ matches", aliases: ["Baresi"] },
      { answer: "Demetrio Albertini", value: "350+ matches", aliases: ["Albertini"] },
      { answer: "Andriy Shevchenko", value: "300+ matches", aliases: ["Shevchenko"] },
      { answer: "Clarence Seedorf", value: "250+ matches", aliases: ["Seedorf"] },
      { answer: "Gennaro Gattuso", value: "250+ matches", aliases: ["Gattuso"] },
      { answer: "Andrea Pirlo", value: "200+ matches", aliases: ["Pirlo"] },
      { answer: "Kaka", value: "200+ matches", aliases: ["Kaká"] },
      { answer: "Filippo Inzaghi", value: "200+ matches", aliases: ["Inzaghi", "Pippo"] },
      { answer: "Dida", value: "180+ matches" },
    ],
  },

  {
    id: "england-top-scorers",
    label: "England top scorers",
    question: "Can you name 10 of England's highest scoring national team players?",
    answers: [
      { answer: "Harry Kane", value: "60+ goals", aliases: ["Kane"] },
      { answer: "Wayne Rooney", value: "53 goals", aliases: ["Rooney"] },
      { answer: "Bobby Charlton", value: "49 goals", aliases: ["Charlton"] },
      { answer: "Gary Lineker", value: "48 goals", aliases: ["Lineker"] },
      { answer: "Jimmy Greaves", value: "44 goals", aliases: ["Greaves"] },
      { answer: "Michael Owen", value: "40 goals", aliases: ["Owen"] },
      { answer: "Nat Lofthouse", value: "30 goals", aliases: ["Lofthouse"] },
      { answer: "Alan Shearer", value: "30 goals", aliases: ["Shearer"] },
      { answer: "Tom Finney", value: "30 goals", aliases: ["Finney"] },
      { answer: "Vivian Woodward", value: "29 goals", aliases: ["Woodward"] },
    ],
  },

  {
    id: "spain-top-scorers",
    label: "Spain top scorers",
    question: "Can you name 10 of Spain's highest scoring national team players?",
    answers: [
      { answer: "David Villa", value: "59 goals", aliases: ["Villa"] },
      { answer: "Raul", value: "44 goals", aliases: ["Raúl"] },
      { answer: "Fernando Torres", value: "38 goals", aliases: ["Torres"] },
      { answer: "Alvaro Morata", value: "35+ goals", aliases: ["Álvaro Morata", "Morata"] },
      { answer: "David Silva", value: "35 goals" },
      { answer: "Fernando Hierro", value: "29 goals", aliases: ["Hierro"] },
      { answer: "Fernando Morientes", value: "27 goals", aliases: ["Morientes"] },
      { answer: "Emilio Butragueno", value: "26 goals", aliases: ["Butragueño", "Butragueno"] },
      { answer: "Sergio Ramos", value: "23 goals", aliases: ["Ramos"] },
      { answer: "Julio Salinas", value: "22 goals", aliases: ["Salinas"] },
    ],
  },

  {
    id: "italy-top-scorers",
    label: "Italy top scorers",
    question: "Can you name 10 of Italy's highest scoring national team players?",
    answers: [
      { answer: "Luigi Riva", value: "35 goals", aliases: ["Gigi Riva", "Riva"] },
      { answer: "Giuseppe Meazza", value: "33 goals", aliases: ["Meazza"] },
      { answer: "Silvio Piola", value: "30 goals", aliases: ["Piola"] },
      { answer: "Roberto Baggio", value: "27 goals", aliases: ["Baggio"] },
      { answer: "Alessandro Del Piero", value: "27 goals", aliases: ["Del Piero"] },
      { answer: "Adolfo Baloncieri", value: "25 goals", aliases: ["Baloncieri"] },
      { answer: "Filippo Inzaghi", value: "25 goals", aliases: ["Inzaghi", "Pippo"] },
      { answer: "Francesco Graziani", value: "23 goals", aliases: ["Graziani"] },
      { answer: "Christian Vieri", value: "23 goals", aliases: ["Vieri"] },
      { answer: "Francesco Totti", value: "9 goals", aliases: ["Totti"] },
    ],
  },

  {
    id: "germany-top-scorers",
    label: "Germany top scorers",
    question: "Can you name 10 of Germany's highest scoring national team players?",
    answers: [
      { answer: "Miroslav Klose", value: "71 goals", aliases: ["Klose"] },
      { answer: "Gerd Muller", value: "68 goals", aliases: ["Gerd Müller", "Muller"] },
      { answer: "Lukas Podolski", value: "49 goals", aliases: ["Podolski"] },
      { answer: "Rudi Voller", value: "47 goals", aliases: ["Rudi Völler", "Voller"] },
      { answer: "Jurgen Klinsmann", value: "47 goals", aliases: ["Jürgen Klinsmann", "Klinsmann"] },
      { answer: "Karl-Heinz Rummenigge", value: "45 goals", aliases: ["Rummenigge"] },
      { answer: "Uwe Seeler", value: "43 goals", aliases: ["Seeler"] },
      { answer: "Thomas Muller", value: "45+ goals", aliases: ["Thomas Müller", "Muller"] },
      { answer: "Michael Ballack", value: "42 goals", aliases: ["Ballack"] },
      { answer: "Oliver Bierhoff", value: "37 goals", aliases: ["Bierhoff"] },
    ],
  },

  {
    id: "netherlands-top-scorers",
    label: "Netherlands top scorers",
    question: "Can you name 10 of the Netherlands' highest scoring national team players?",
    answers: [
      { answer: "Robin van Persie", value: "50 goals", aliases: ["Van Persie"] },
      { answer: "Memphis Depay", value: "45+ goals", aliases: ["Depay", "Memphis"] },
      { answer: "Klaas-Jan Huntelaar", value: "42 goals", aliases: ["Huntelaar", "Klaas Jan Huntelaar"] },
      { answer: "Patrick Kluivert", value: "40 goals", aliases: ["Kluivert"] },
      { answer: "Dennis Bergkamp", value: "37 goals", aliases: ["Bergkamp"] },
      { answer: "Arjen Robben", value: "37 goals", aliases: ["Robben"] },
      { answer: "Faas Wilkes", value: "35 goals", aliases: ["Wilkes"] },
      { answer: "Ruud van Nistelrooy", value: "35 goals", aliases: ["Van Nistelrooy"] },
      { answer: "Abe Lenstra", value: "33 goals", aliases: ["Lenstra"] },
      { answer: "Johan Cruyff", value: "33 goals", aliases: ["Cruyff", "Cruijff"] },
    ],
  },

  {
    id: "argentina-top-scorers",
    label: "Argentina top scorers",
    question: "Can you name 10 of Argentina's highest scoring national team players?",
    answers: [
      { answer: "Lionel Messi", value: "100+ goals", aliases: ["Messi"] },
      { answer: "Gabriel Batistuta", value: "54 goals", aliases: ["Batistuta"] },
      { answer: "Sergio Aguero", value: "41 goals", aliases: ["Sergio Agüero", "Aguero"] },
      { answer: "Hernan Crespo", value: "35 goals", aliases: ["Hernán Crespo", "Crespo"] },
      { answer: "Diego Maradona", value: "34 goals", aliases: ["Maradona"] },
      { answer: "Gonzalo Higuain", value: "31 goals", aliases: ["Gonzalo Higuaín", "Higuain"] },
      { answer: "Angel Di Maria", value: "30+ goals", aliases: ["Ángel Di María", "Di Maria"] },
      { answer: "Lautaro Martinez", value: "30+ goals", aliases: ["Lautaro Martínez", "Lautaro"] },
      { answer: "Daniel Passarella", value: "22 goals", aliases: ["Passarella"] },
      { answer: "Daniel Bertoni", value: "21 goals", aliases: ["Bertoni"] },
    ],
  },

  {
    id: "portugal-top-scorers",
    label: "Portugal top scorers",
    question: "Can you name 10 of Portugal's highest scoring national team players?",
    answers: [
      { answer: "Cristiano Ronaldo", value: "130+ goals", aliases: ["Ronaldo", "CR7"] },
      { answer: "Pauleta", value: "47 goals" },
      { answer: "Eusebio", value: "41 goals", aliases: ["Eusébio"] },
      { answer: "Luis Figo", value: "32 goals", aliases: ["Luís Figo", "Figo"] },
      { answer: "Nuno Gomes", value: "29 goals" },
      { answer: "Helder Postiga", value: "27 goals", aliases: ["Hélder Postiga", "Postiga"] },
      { answer: "Rui Costa", value: "26 goals" },
      { answer: "Nani", value: "24 goals" },
      { answer: "Joao Pinto", value: "23 goals", aliases: ["João Pinto"] },
      { answer: "Bernardo Silva", value: "20+ goals", aliases: ["Bernardo"] },
    ],
  },

  {
    id: "sweden-top-scorers",
    label: "Sweden top scorers",
    question: "Can you name 10 of Sweden's highest scoring national team players?",
    answers: [
      { answer: "Zlatan Ibrahimovic", value: "62 goals", aliases: ["Zlatan", "Ibrahimovic"] },
      { answer: "Sven Rydell", value: "49 goals", aliases: ["Rydell"] },
      { answer: "Gunnar Nordahl", value: "43 goals", aliases: ["Nordahl"] },
      { answer: "Henrik Larsson", value: "37 goals", aliases: ["Larsson"] },
      { answer: "Karl-Alfred Jacobsson", value: "17+ goals", aliases: ["Jacobsson"] },
      { answer: "Marcus Berg", value: "24 goals", aliases: ["Berg"] },
      { answer: "Tomas Brolin", value: "27 goals", aliases: ["Brolin"] },
      { answer: "Kenneth Andersson", value: "31 goals", aliases: ["Andersson"] },
      { answer: "Agne Simonsson", value: "27 goals", aliases: ["Simonsson"] },
      { answer: "Ralf Edstrom", value: "15+ goals", aliases: ["Ralf Edström", "Edstrom"] },
    ],
  },

  {
    id: "world-cup-hosts-modern",
    label: "Modern World Cup hosts",
    question: "Can you name 10 countries that have hosted the men's FIFA World Cup since 1982?",
    answers: [
      { answer: "Spain", value: "1982" },
      { answer: "Mexico", value: "1986" },
      { answer: "Italy", value: "1990" },
      { answer: "United States", value: "1994", aliases: ["USA"] },
      { answer: "France", value: "1998" },
      { answer: "South Korea", value: "2002 co-host", aliases: ["Korea Republic"] },
      { answer: "Japan", value: "2002 co-host" },
      { answer: "Germany", value: "2006" },
      { answer: "South Africa", value: "2010" },
      { answer: "Brazil", value: "2014" },
    ],
  },

  {
    id: "euro-hosts-modern",
    label: "Modern Euro hosts",
    question: "Can you name 10 countries that hosted or co-hosted the UEFA European Championship since 1996?",
    answers: [
      { answer: "England", value: "1996" },
      { answer: "Belgium", value: "2000 co-host" },
      { answer: "Netherlands", value: "2000 co-host", aliases: ["Holland"] },
      { answer: "Portugal", value: "2004" },
      { answer: "Austria", value: "2008 co-host" },
      { answer: "Switzerland", value: "2008 co-host" },
      { answer: "Poland", value: "2012 co-host" },
      { answer: "Ukraine", value: "2012 co-host" },
      { answer: "France", value: "2016" },
      { answer: "Germany", value: "2024" },
    ],
  },

  {
    id: "ucl-winners-since-2000-clubs",
    label: "UCL winners since 2000",
    question: "Can you name 10 clubs that have won the Champions League since 2000?",
    answers: [
      { answer: "Real Madrid", value: "8 titles since 2000" },
      { answer: "Barcelona", value: "4 titles since 2000", aliases: ["FC Barcelona"] },
      { answer: "Bayern Munich", value: "3 titles since 2000", aliases: ["Bayern"] },
      { answer: "AC Milan", value: "2 titles since 2000", aliases: ["Milan"] },
      { answer: "Liverpool", value: "2 titles since 2000" },
      { answer: "Chelsea", value: "2 titles since 2000" },
      { answer: "Inter", value: "1 title since 2000", aliases: ["Inter Milan", "Internazionale"] },
      { answer: "Manchester United", value: "1 title since 2000", aliases: ["Man United", "Man Utd"] },
      { answer: "Porto", value: "1 title since 2000" },
      { answer: "Manchester City", value: "1 title since 2000", aliases: ["Man City"] },
    ],
  },  {
    id: "world-cup-golden-ball-winners",
    label: "World Cup Golden Ball winners",
    question: "Can you name 10 players who have won the FIFA World Cup Golden Ball?",
    targetCount: 10,
    answers: [
      { answer: "Paolo Rossi", value: "1982", aliases: ["Rossi"] },
      { answer: "Diego Maradona", value: "1986", aliases: ["Maradona"] },
      { answer: "Salvatore Schillaci", value: "1990", aliases: ["Schillaci"] },
      { answer: "Romario", value: "1994", aliases: ["Romário"] },
      { answer: "Ronaldo", value: "1998", aliases: ["R9", "Ronaldo Nazario"] },
      { answer: "Oliver Kahn", value: "2002", aliases: ["Kahn"] },
      { answer: "Zinedine Zidane", value: "2006", aliases: ["Zidane"] },
      { answer: "Diego Forlan", value: "2010", aliases: ["Diego Forlán", "Forlan"] },
      { answer: "Lionel Messi", value: "2014 and 2022", aliases: ["Messi"] },
      { answer: "Luka Modric", value: "2018", aliases: ["Luka Modrić", "Modric"] },
    ],
  },

  {
    id: "world-cup-golden-boot-winners-modern",
    label: "Modern World Cup Golden Boot winners",
    question: "Can you name 10 players who have won the FIFA World Cup Golden Boot since 1982?",
    targetCount: 10,
    answers: [
      { answer: "Paolo Rossi", value: "1982 / 6 goals", aliases: ["Rossi"] },
      { answer: "Gary Lineker", value: "1986 / 6 goals", aliases: ["Lineker"] },
      { answer: "Salvatore Schillaci", value: "1990 / 6 goals", aliases: ["Schillaci"] },
      { answer: "Oleg Salenko", value: "1994 / 6 goals", aliases: ["Salenko"] },
      { answer: "Hristo Stoichkov", value: "1994 / 6 goals", aliases: ["Stoichkov"] },
      { answer: "Davor Suker", value: "1998 / 6 goals", aliases: ["Davor Šuker", "Suker"] },
      { answer: "Ronaldo", value: "2002 / 8 goals", aliases: ["R9", "Ronaldo Nazario"] },
      { answer: "Miroslav Klose", value: "2006 / 5 goals", aliases: ["Klose"] },
      { answer: "Thomas Muller", value: "2010 / 5 goals", aliases: ["Thomas Müller", "Muller"] },
      { answer: "James Rodriguez", value: "2014 / 6 goals", aliases: ["James Rodríguez", "James"] },
      { answer: "Harry Kane", value: "2018 / 6 goals", aliases: ["Kane"] },
      { answer: "Kylian Mbappe", value: "2022 / 8 goals", aliases: ["Kylian Mbappé", "Mbappe"] },
    ],
  },

  {
    id: "world-cup-winning-captains-modern",
    label: "Modern World Cup winning captains",
    question: "Can you name 10 captains who lifted the men's FIFA World Cup from 1982 to 2022?",
    targetCount: 10,
    answers: [
      { answer: "Dino Zoff", value: "Italy / 1982", aliases: ["Zoff"] },
      { answer: "Diego Maradona", value: "Argentina / 1986", aliases: ["Maradona"] },
      { answer: "Lothar Matthaus", value: "West Germany / 1990", aliases: ["Lothar Matthäus", "Matthaus"] },
      { answer: "Dunga", value: "Brazil / 1994" },
      { answer: "Didier Deschamps", value: "France / 1998", aliases: ["Deschamps"] },
      { answer: "Cafu", value: "Brazil / 2002" },
      { answer: "Fabio Cannavaro", value: "Italy / 2006", aliases: ["Cannavaro"] },
      { answer: "Iker Casillas", value: "Spain / 2010", aliases: ["Casillas"] },
      { answer: "Philipp Lahm", value: "Germany / 2014", aliases: ["Lahm"] },
      { answer: "Hugo Lloris", value: "France / 2018", aliases: ["Lloris"] },
      { answer: "Lionel Messi", value: "Argentina / 2022", aliases: ["Messi"] },
    ],
  },

  {
    id: "world-cup-final-goalkeepers-modern",
    label: "Modern World Cup final goalkeepers",
    question: "Can you name 10 goalkeepers who started a men's World Cup final since 1994?",
    targetCount: 10,
    answers: [
      { answer: "Claudio Taffarel", value: "Brazil / 1994 and 1998", aliases: ["Taffarel"] },
      { answer: "Gianluca Pagliuca", value: "Italy / 1994", aliases: ["Pagliuca"] },
      { answer: "Fabien Barthez", value: "France / 1998 and 2006", aliases: ["Barthez"] },
      { answer: "Oliver Kahn", value: "Germany / 2002", aliases: ["Kahn"] },
      { answer: "Gianluigi Buffon", value: "Italy / 2006", aliases: ["Buffon", "Gigi Buffon"] },
      { answer: "Iker Casillas", value: "Spain / 2010", aliases: ["Casillas"] },
      { answer: "Maarten Stekelenburg", value: "Netherlands / 2010", aliases: ["Stekelenburg"] },
      { answer: "Manuel Neuer", value: "Germany / 2014", aliases: ["Neuer"] },
      { answer: "Sergio Romero", value: "Argentina / 2014", aliases: ["Romero"] },
      { answer: "Hugo Lloris", value: "France / 2018 and 2022", aliases: ["Lloris"] },
      { answer: "Danijel Subasic", value: "Croatia / 2018", aliases: ["Danijel Subašić", "Subasic"] },
      { answer: "Emiliano Martinez", value: "Argentina / 2022", aliases: ["Emiliano Martínez", "Dibu Martinez", "Dibu"] },
    ],
  },

  {
    id: "ucl-winning-captains-modern",
    label: "Modern Champions League winning captains",
    question: "Can you name 10 captains who lifted the Champions League trophy since 2000?",
    targetCount: 10,
    answers: [
      { answer: "Stefan Effenberg", value: "Bayern Munich / 2001", aliases: ["Effenberg"] },
      { answer: "Paolo Maldini", value: "AC Milan / 2003 and 2007", aliases: ["Maldini"] },
      { answer: "Fernando Hierro", value: "Real Madrid / 2002", aliases: ["Hierro"] },
      { answer: "Jorge Costa", value: "Porto / 2004", aliases: ["Costa"] },
      { answer: "Steven Gerrard", value: "Liverpool / 2005", aliases: ["Gerrard"] },
      { answer: "Carles Puyol", value: "Barcelona / 2006", aliases: ["Puyol"] },
      { answer: "Rio Ferdinand", value: "Manchester United / 2008", aliases: ["Ferdinand"] },
      { answer: "Javier Zanetti", value: "Inter / 2010", aliases: ["Zanetti"] },
      { answer: "Iker Casillas", value: "Real Madrid / 2014", aliases: ["Casillas"] },
      { answer: "Sergio Ramos", value: "Real Madrid / 2016-2018", aliases: ["Ramos"] },
      { answer: "Jordan Henderson", value: "Liverpool / 2019", aliases: ["Henderson"] },
      { answer: "Cesar Azpilicueta", value: "Chelsea / 2021", aliases: ["César Azpilicueta", "Azpilicueta"] },
    ],
  },

  {
    id: "ucl-final-losing-clubs-since-2000",
    label: "UCL final losing clubs since 2000",
    question: "Can you name 10 clubs that lost a Champions League final since 2000?",
    targetCount: 10,
    answers: [
      { answer: "Valencia", value: "2000 and 2001" },
      { answer: "Bayer Leverkusen", value: "2002", aliases: ["Leverkusen"] },
      { answer: "Juventus", value: "2003, 2015 and 2017" },
      { answer: "Monaco", value: "2004" },
      { answer: "AC Milan", value: "2005", aliases: ["Milan"] },
      { answer: "Arsenal", value: "2006" },
      { answer: "Chelsea", value: "2008" },
      { answer: "Manchester United", value: "2009 and 2011", aliases: ["Man United", "Man Utd"] },
      { answer: "Bayern Munich", value: "2010 and 2012", aliases: ["Bayern"] },
      { answer: "Atletico Madrid", value: "2014 and 2016", aliases: ["Atlético Madrid", "Atleti"] },
      { answer: "Tottenham Hotspur", value: "2019", aliases: ["Tottenham", "Spurs"] },
      { answer: "Paris Saint-Germain", value: "2020", aliases: ["PSG"] },
      { answer: "Inter", value: "2023", aliases: ["Inter Milan", "Internazionale"] },
      { answer: "Borussia Dortmund", value: "2013 and 2024", aliases: ["Dortmund", "BVB"] },
    ],
  },

  {
    id: "world-cup-final-losing-countries-modern",
    label: "Modern World Cup final losers",
    question: "Can you name 10 countries that lost a men's World Cup final from 1978 to 2022?",
    targetCount: 10,
    answers: [
      { answer: "Netherlands", value: "1978 and 2010", aliases: ["Holland"] },
      { answer: "West Germany", value: "1982 and 1986", aliases: ["Germany"] },
      { answer: "Argentina", value: "1990 and 2014" },
      { answer: "Italy", value: "1994" },
      { answer: "Brazil", value: "1998" },
      { answer: "Germany", value: "2002" },
      { answer: "France", value: "2006 and 2022" },
      { answer: "Croatia", value: "2018" },
    ],
  },

  {
    id: "ucl-final-venues-since-2000",
    label: "Champions League final venues",
    question: "Can you name 10 stadiums that hosted a Champions League final since 2000?",
    targetCount: 10,
    answers: [
      { answer: "Stade de France", value: "2000, 2006 and 2022" },
      { answer: "San Siro", value: "2001 and 2016", aliases: ["Giuseppe Meazza"] },
      { answer: "Hampden Park", value: "2002" },
      { answer: "Old Trafford", value: "2003" },
      { answer: "Arena AufSchalke", value: "2004", aliases: ["Veltins-Arena"] },
      { answer: "Ataturk Olympic Stadium", value: "2005 and 2023", aliases: ["Atatürk Olympic Stadium"] },
      { answer: "Olympiastadion", value: "2015", aliases: ["Berlin Olympic Stadium"] },
      { answer: "Wembley Stadium", value: "2011, 2013 and 2024", aliases: ["Wembley"] },
      { answer: "Estadio da Luz", value: "2014 and 2020", aliases: ["Estádio da Luz"] },
      { answer: "Millennium Stadium", value: "2017", aliases: ["Principality Stadium"] },
      { answer: "NSC Olimpiyskiy", value: "2018", aliases: ["Olympic Stadium Kyiv"] },
      { answer: "Wanda Metropolitano", value: "2019", aliases: ["Metropolitano"] },
      { answer: "Estadio do Dragao", value: "2021", aliases: ["Estádio do Dragão"] },
    ],
  },

  {
    id: "world-cup-final-venues-modern",
    label: "Modern World Cup final venues",
    question: "Can you name 10 stadiums that hosted a men's World Cup final from 1982 to 2022?",
    targetCount: 10,
    answers: [
      { answer: "Santiago Bernabeu", value: "1982", aliases: ["Santiago Bernabéu", "Bernabeu"] },
      { answer: "Estadio Azteca", value: "1986", aliases: ["Azteca"] },
      { answer: "Stadio Olimpico", value: "1990" },
      { answer: "Rose Bowl", value: "1994" },
      { answer: "Stade de France", value: "1998" },
      { answer: "International Stadium Yokohama", value: "2002", aliases: ["Yokohama"] },
      { answer: "Olympiastadion", value: "2006", aliases: ["Berlin Olympic Stadium"] },
      { answer: "Soccer City", value: "2010", aliases: ["FNB Stadium"] },
      { answer: "Maracana", value: "2014", aliases: ["Maracanã"] },
      { answer: "Luzhniki Stadium", value: "2018", aliases: ["Luzhniki"] },
      { answer: "Lusail Stadium", value: "2022", aliases: ["Lusail"] },
    ],
  },

  {
    id: "euro-final-goalscorers-since-1996",
    label: "Euro final goalscorers",
    question: "Can you name 10 players who scored in a UEFA Euro final since 1996?",
    targetCount: 10,
    answers: [
      { answer: "Oliver Bierhoff", value: "1996 final", aliases: ["Bierhoff"] },
      { answer: "Marco Delvecchio", value: "2000 final", aliases: ["Delvecchio"] },
      { answer: "Sylvain Wiltord", value: "2000 final", aliases: ["Wiltord"] },
      { answer: "David Trezeguet", value: "2000 final", aliases: ["Trezeguet"] },
      { answer: "Angelos Charisteas", value: "2004 final", aliases: ["Charisteas"] },
      { answer: "Fernando Torres", value: "2008 final", aliases: ["Torres"] },
      { answer: "David Silva", value: "2012 final" },
      { answer: "Jordi Alba", value: "2012 final" },
      { answer: "Juan Mata", value: "2012 final", aliases: ["Mata"] },
      { answer: "Eder", value: "2016 final", aliases: ["Éder"] },
      { answer: "Luke Shaw", value: "2020 final" },
      { answer: "Leonardo Bonucci", value: "2020 final", aliases: ["Bonucci"] },
      { answer: "Nico Williams", value: "2024 final" },
      { answer: "Mikel Oyarzabal", value: "2024 final", aliases: ["Oyarzabal"] },
      { answer: "Cole Palmer", value: "2024 final" },
    ],
  },

  {
    id: "players-scored-in-ucl-and-world-cup-finals",
    label: "Scored in UCL and World Cup finals",
    question: "Can you name players who have scored in both a Champions League final and a World Cup final?",
    targetCount: 10,
    answers: [
      { answer: "Zinedine Zidane", value: "UCL 2002 / WC 1998 and 2006", aliases: ["Zidane"] },
      { answer: "Lionel Messi", value: "UCL 2009, 2011 / WC 2022", aliases: ["Messi"] },
      { answer: "Cristiano Ronaldo", value: "UCL 2008, 2014, 2017 / WC not final", aliases: ["Ronaldo", "CR7"] },
      { answer: "Samuel Eto'o", value: "UCL finals / no WC final", aliases: ["Eto'o", "Etoo"] },
      { answer: "Kylian Mbappe", value: "WC 2018 and 2022 / no UCL final goal", aliases: ["Mbappé", "Mbappe"] },
      { answer: "Mario Mandzukic", value: "UCL 2013, 2017 / WC 2018", aliases: ["Mario Mandžukić", "Mandzukic"] },
      { answer: "Angel Di Maria", value: "UCL 2014 assist / WC 2022 goal", aliases: ["Ángel Di María", "Di Maria"] },
      { answer: "Ronaldo", value: "WC 2002 / no UCL final goal", aliases: ["R9", "Ronaldo Nazario"] },
      { answer: "Zlatan Ibrahimovic", value: "No final goals", aliases: ["Zlatan"] },
      { answer: "Didier Drogba", value: "UCL 2012 / no WC final", aliases: ["Drogba"] },
    ],
  },

  {
    id: "euro-winning-captains-modern",
    label: "Modern Euro winning captains",
    question: "Can you name 10 captains who lifted the UEFA European Championship from 1988 to 2024?",
    targetCount: 10,
    answers: [
      { answer: "Ruud Gullit", value: "Netherlands / 1988", aliases: ["Gullit"] },
      { answer: "Lars Olsen", value: "Denmark / 1992" },
      { answer: "Jurgen Klinsmann", value: "Germany / 1996", aliases: ["Jürgen Klinsmann", "Klinsmann"] },
      { answer: "Didier Deschamps", value: "France / 2000", aliases: ["Deschamps"] },
      { answer: "Theodoros Zagorakis", value: "Greece / 2004", aliases: ["Zagorakis"] },
      { answer: "Iker Casillas", value: "Spain / 2008 and 2012", aliases: ["Casillas"] },
      { answer: "Cristiano Ronaldo", value: "Portugal / 2016", aliases: ["Ronaldo", "CR7"] },
      { answer: "Giorgio Chiellini", value: "Italy / 2020", aliases: ["Chiellini"] },
      { answer: "Alvaro Morata", value: "Spain / 2024", aliases: ["Álvaro Morata", "Morata"] },
    ],
  },

  {
    id: "copa-america-most-titles-countries",
    label: "Copa America title countries",
    question: "Can you name countries with the most Copa America titles?",
    targetCount: 8,
    answers: [
      { answer: "Argentina", value: "16 titles" },
      { answer: "Uruguay", value: "15 titles" },
      { answer: "Brazil", value: "9 titles" },
      { answer: "Paraguay", value: "2 titles" },
      { answer: "Chile", value: "2 titles" },
      { answer: "Peru", value: "2 titles" },
      { answer: "Colombia", value: "1 title" },
      { answer: "Bolivia", value: "1 title" },
    ],
  },

  {
    id: "afcon-most-titles-countries",
    label: "AFCON title countries",
    question: "Can you name 10 countries with the most Africa Cup of Nations titles?",
    targetCount: 10,
    answers: [
      { answer: "Egypt", value: "7 titles" },
      { answer: "Cameroon", value: "5 titles" },
      { answer: "Ghana", value: "4 titles" },
      { answer: "Nigeria", value: "3 titles" },
      { answer: "Ivory Coast", value: "3 titles", aliases: ["Cote d'Ivoire", "Côte d'Ivoire"] },
      { answer: "Algeria", value: "2 titles" },
      { answer: "DR Congo", value: "2 titles", aliases: ["Democratic Republic of the Congo", "Zaire"] },
      { answer: "Ethiopia", value: "1 title" },
      { answer: "Sudan", value: "1 title" },
      { answer: "Congo", value: "1 title" },
      { answer: "Morocco", value: "1 title" },
      { answer: "South Africa", value: "1 title" },
      { answer: "Tunisia", value: "1 title" },
      { answer: "Zambia", value: "1 title" },
      { answer: "Senegal", value: "1 title" },
    ],
  },

  {
    id: "asian-cup-most-titles-countries",
    label: "Asian Cup title countries",
    question: "Can you name countries with the most AFC Asian Cup titles?",
    targetCount: 10,
    answers: [
      { answer: "Japan", value: "4 titles" },
      { answer: "Saudi Arabia", value: "3 titles" },
      { answer: "Iran", value: "3 titles" },
      { answer: "South Korea", value: "2 titles", aliases: ["Korea Republic"] },
      { answer: "Qatar", value: "2 titles" },
      { answer: "Israel", value: "1 title" },
      { answer: "Kuwait", value: "1 title" },
      { answer: "Australia", value: "1 title" },
      { answer: "Iraq", value: "1 title" },
    ],
  },

  {
    id: "ucl-finals-decided-by-penalties",
    label: "UCL finals decided by penalties",
    question: "Can you name clubs involved in Champions League finals decided by penalties since 2000?",
    targetCount: 10,
    answers: [
      { answer: "Bayern Munich", value: "2001 and 2012", aliases: ["Bayern"] },
      { answer: "Valencia", value: "2001" },
      { answer: "AC Milan", value: "2003 and 2005", aliases: ["Milan"] },
      { answer: "Juventus", value: "2003" },
      { answer: "Liverpool", value: "2005" },
      { answer: "Manchester United", value: "2008", aliases: ["Man United", "Man Utd"] },
      { answer: "Chelsea", value: "2008 and 2012" },
      { answer: "Atletico Madrid", value: "2016", aliases: ["Atlético Madrid", "Atleti"] },
      { answer: "Real Madrid", value: "2016" },
    ],
  },

  {
    id: "world-cup-finals-decided-by-penalties",
    label: "World Cup penalty finals",
    question: "Can you name countries involved in men's World Cup finals decided by penalties?",
    targetCount: 6,
    answers: [
      { answer: "Brazil", value: "1994 winner" },
      { answer: "Italy", value: "1994 loser and 2006 winner" },
      { answer: "France", value: "2006 loser and 2022 loser" },
      { answer: "Argentina", value: "2022 winner" },
      { answer: "Germany", value: "None as final shootout team", aliases: ["West Germany"] },
      { answer: "Croatia", value: "No final shootout", aliases: [] },
    ],
  },

  {
    id: "euros-finals-decided-by-penalties",
    label: "Euro penalty finals",
    question: "Can you name countries involved in UEFA Euro finals decided by penalties?",
    targetCount: 6,
    answers: [
      { answer: "Czechoslovakia", value: "1976 winner" },
      { answer: "West Germany", value: "1976 loser", aliases: ["Germany"] },
      { answer: "Italy", value: "2020 winner" },
      { answer: "England", value: "2020 loser" },
      { answer: "Spain", value: "No Euro final shootout win", aliases: [] },
      { answer: "France", value: "No Euro final shootout win", aliases: [] },
    ],
  },

  {
    id: "world-cup-hat-trick-scorers-modern",
    label: "Modern World Cup hat-tricks",
    question: "Can you name 10 players who scored a men's World Cup hat-trick from 1982 to 2022?",
    targetCount: 10,
    answers: [
      { answer: "Paolo Rossi", value: "1982 vs Brazil", aliases: ["Rossi"] },
      { answer: "Gary Lineker", value: "1986 vs Poland", aliases: ["Lineker"] },
      { answer: "Emilio Butragueno", value: "1986 vs Denmark", aliases: ["Butragueño", "Butragueno"] },
      { answer: "Michel", value: "1990 vs South Korea", aliases: ["Míchel"] },
      { answer: "Tomas Skuhravy", value: "1990 vs Costa Rica", aliases: ["Tomáš Skuhravý", "Skuhravy"] },
      { answer: "Gabriel Batistuta", value: "1994 and 1998", aliases: ["Batistuta"] },
      { answer: "Oleg Salenko", value: "1994 vs Cameroon / 5 goals", aliases: ["Salenko"] },
      { answer: "Miroslav Klose", value: "2002 vs Saudi Arabia", aliases: ["Klose"] },
      { answer: "Goncalo Ramos", value: "2022 vs Switzerland", aliases: ["Gonçalo Ramos"] },
      { answer: "Kylian Mbappe", value: "2022 final vs Argentina", aliases: ["Kylian Mbappé", "Mbappe"] },
    ],
  },
  
];

