export const WHO_AM_I_QUESTIONS = [
    {
    id: "whoami_051",
    answer: "Claudio Marchisio",
    acceptedAnswers: ["Claudio Marchisio", "Marchisio"],
    difficulty: "Hard",
    clues: [
      "I am from Italy.",
      "I was a midfielder with a calm style.",
      "I had dark hair and often looked very composed on the pitch.",
      "I spent most of my career in one country.",
      "I was known for intelligence more than flashy skills.",
      "I became strongly connected with black and white stripes.",
      "I played many years beside other famous Italian midfielders.",
      "I reached the Champions League final in 2015.",
      "My initials are CM.",
      "I am Claudio Marchisio.",
    ],
  },
  {
    id: "whoami_052",
    answer: "Daniele De Rossi",
    acceptedAnswers: ["Daniele De Rossi", "De Rossi"],
    difficulty: "Hard",
    clues: [
      "I am from Italy.",
      "I was a tough midfielder.",
      "I was known for passion and leadership.",
      "I spent almost my entire European career at one club.",
      "I often played deeper in midfield.",
      "I won the World Cup in 2006.",
      "I was strongly associated with the city of Rome.",
      "I played for Roma for many years.",
      "My initials are DDR.",
      "I am Daniele De Rossi.",
    ],
  },
  {
    id: "whoami_053",
    answer: "Yaya Toure",
    acceptedAnswers: ["Yaya Toure", "Yaya Touré", "Toure", "Touré"],
    difficulty: "Medium",
    clues: [
      "I am from Ivory Coast.",
      "I was a tall and powerful midfielder.",
      "I could defend, carry the ball and score goals.",
      "I played in several European leagues.",
      "I won major trophies in Spain.",
      "I later became a Premier League star.",
      "I was a key player in Manchester City's rise.",
      "I scored many important goals from midfield.",
      "My first name starts with Y.",
      "I am Yaya Toure.",
    ],
  },
  {
    id: "whoami_054",
    answer: "Michael Essien",
    acceptedAnswers: ["Michael Essien", "Essien"],
    difficulty: "Hard",
    clues: [
      "I am from Ghana.",
      "I was a strong and energetic midfielder.",
      "I was known for power, tackling and long shots.",
      "I played in France before moving to England.",
      "I became important at a London club.",
      "I played under Jose Mourinho.",
      "I won multiple Premier League titles.",
      "I scored a famous goal against Barcelona.",
      "My initials are ME.",
      "I am Michael Essien.",
    ],
  },
  {
    id: "whoami_055",
    answer: "Dimitar Berbatov",
    acceptedAnswers: ["Dimitar Berbatov", "Berbatov"],
    difficulty: "Hard",
    clues: [
      "I am from Bulgaria.",
      "I was a striker with a very relaxed playing style.",
      "I was known for first touch and elegance.",
      "I played in Germany before moving to England.",
      "I became popular in North London.",
      "I later joined Manchester United.",
      "I won Premier League titles.",
      "I scored a hat-trick against Liverpool.",
      "My initials are DB.",
      "I am Dimitar Berbatov.",
    ],
  },
  {
    id: "whoami_056",
    answer: "Jermain Defoe",
    acceptedAnswers: ["Jermain Defoe", "Defoe"],
    difficulty: "Hard",
    clues: [
      "I am from England.",
      "I was not very tall for a striker.",
      "I was known for quick finishing inside the box.",
      "I played for several English clubs.",
      "I had more than one spell at the same North London club.",
      "I scored many Premier League goals.",
      "I also played in Major League Soccer.",
      "I represented England at international level.",
      "My initials are JD.",
      "I am Jermain Defoe.",
    ],
  },
  {
    id: "whoami_057",
    answer: "Robinho",
    acceptedAnswers: ["Robinho"],
    difficulty: "Hard",
    clues: [
      "I am from Brazil.",
      "I was a small, skillful attacker.",
      "I became famous very young.",
      "I was known for stepovers and flair.",
      "I played for Santos early in my career.",
      "I moved to Real Madrid.",
      "I later became a major signing for Manchester City.",
      "I also played for AC Milan.",
      "My name starts with R.",
      "I am Robinho.",
    ],
  },
  {
    id: "whoami_058",
    answer: "Diego Forlan",
    acceptedAnswers: ["Diego Forlan", "Forlan", "Forlán"],
    difficulty: "Hard",
    clues: [
      "I am from Uruguay.",
      "I was a striker with blond hair.",
      "I was known for shooting with both feet.",
      "I played in England, Spain and Italy.",
      "I became much more successful in Spain than in England.",
      "I won the Europa League with Atletico Madrid.",
      "I was brilliant at the 2010 World Cup.",
      "I won the Golden Ball at the 2010 World Cup.",
      "My initials are DF.",
      "I am Diego Forlan.",
    ],
  },
  {
    id: "whoami_059",
    answer: "Giovani dos Santos",
    acceptedAnswers: ["Giovani dos Santos", "Dos Santos", "Giovani"],
    difficulty: "Hard",
    clues: [
      "I am from Mexico.",
      "I was an attacking player with great technical ability.",
      "I was seen as a huge talent when I was young.",
      "I came through a famous Spanish academy.",
      "I played for Barcelona early in my career.",
      "I later played for Tottenham.",
      "I also played in Spain for Villarreal.",
      "I represented Mexico for many years.",
      "My initials are GDS.",
      "I am Giovani dos Santos.",
    ],
  },
  {
    id: "whoami_060",
    answer: "Giovani Lo Celso",
    acceptedAnswers: ["Giovani Lo Celso", "Lo Celso"],
    difficulty: "Hard",
    clues: [
      "I am from Argentina.",
      "I am a left-footed midfielder.",
      "I am known for technique and ball control.",
      "I played in France before moving to Spain.",
      "I had an important spell at Real Betis.",
      "I later joined Tottenham Hotspur.",
      "I also played for Villarreal.",
      "I won the 2021 Copa America with Argentina.",
      "My initials are GLC.",
      "I am Giovani Lo Celso.",
    ],
  },
  {
    id: "whoami_061",
    answer: "Ever Banega",
    acceptedAnswers: ["Ever Banega", "Banega"],
    difficulty: "Hard",
    clues: [
      "I am from Argentina.",
      "I was a technical central midfielder.",
      "I liked to control the tempo of the game.",
      "I played most of my European football in Spain.",
      "I played for Valencia.",
      "I became especially important at Sevilla.",
      "I won the Europa League multiple times.",
      "I represented Argentina internationally.",
      "My initials are EB.",
      "I am Ever Banega.",
    ],
  },
  {
    id: "whoami_062",
    answer: "Ivan Rakitic",
    acceptedAnswers: ["Ivan Rakitic", "Rakitic", "Rakitić"],
    difficulty: "Medium",
    clues: [
      "I represented Croatia.",
      "I was born in Switzerland.",
      "I was a technical midfielder.",
      "I played in Germany before moving to Spain.",
      "I became a key player at Sevilla.",
      "I later joined Barcelona.",
      "I scored in the 2015 Champions League final.",
      "I helped Croatia reach the 2018 World Cup final.",
      "My initials are IR.",
      "I am Ivan Rakitic.",
    ],
  },
  {
    id: "whoami_063",
    answer: "Seydou Keita",
    acceptedAnswers: ["Seydou Keita", "Keita", "Keïta"],
    difficulty: "Hard",
    clues: [
      "I am from Mali.",
      "I was a left-footed midfielder.",
      "I was known for work rate and tactical intelligence.",
      "I played in France before moving to Spain.",
      "I played for Sevilla.",
      "I later joined Barcelona.",
      "I was part of Pep Guardiola's Barcelona squad.",
      "I won the Champions League with Barcelona.",
      "My initials are SK.",
      "I am Seydou Keita.",
    ],
  },
  {
    id: "whoami_064",
    answer: "Pedro",
    acceptedAnswers: ["Pedro", "Pedro Rodriguez", "Pedro Rodríguez"],
    difficulty: "Hard",
    clues: [
      "I am from Spain.",
      "I was a quick winger.",
      "I was not always the biggest star in my teams.",
      "I was known for movement and finishing.",
      "I came through Barcelona's system.",
      "I played with many legendary players at Barcelona.",
      "I scored in several different competitions in one season.",
      "I later played for Chelsea and Roma.",
      "My name starts with P.",
      "I am Pedro.",
    ],
  },
  {
    id: "whoami_065",
    answer: "Alexis Sanchez",
    acceptedAnswers: ["Alexis Sanchez", "Alexis Sánchez", "Alexis", "Sanchez", "Sánchez"],
    difficulty: "Medium",
    clues: [
      "I am from Chile.",
      "I was a quick and aggressive forward.",
      "I was known for energy and direct dribbling.",
      "I played in Italy before moving to Spain.",
      "I played for Udinese.",
      "I later joined Barcelona.",
      "I became a star at Arsenal.",
      "I won Copa America with Chile.",
      "My initials are AS.",
      "I am Alexis Sanchez.",
    ],
  },
  {
    id: "whoami_066",
    answer: "Eduardo Vargas",
    acceptedAnswers: ["Eduardo Vargas", "Vargas"],
    difficulty: "Hard",
    clues: [
      "I am from Chile.",
      "I was a forward with pace and direct movement.",
      "I played in South America before moving to Europe.",
      "I joined Napoli early in my European career.",
      "I also played in Spain, Germany and Mexico.",
      "I was often very important for my national team.",
      "I won Copa America with Chile.",
      "I scored many goals for Chile in major tournaments.",
      "My initials are EV.",
      "I am Eduardo Vargas.",
    ],
  },
  {
    id: "whoami_067",
    answer: "Fred",
    acceptedAnswers: ["Fred", "Frederico Chaves Guedes"],
    difficulty: "Hard",
    clues: [
      "I am from Brazil.",
      "I was a striker.",
      "I had a short name used on my shirt.",
      "I played in France for several years.",
      "I became important at Lyon.",
      "I later returned to Brazilian football.",
      "I represented Brazil at the 2014 World Cup.",
      "I started up front for Brazil in that tournament.",
      "My name starts with F.",
      "I am Fred.",
    ],
  },
  {
    id: "whoami_068",
    answer: "Oscar",
    acceptedAnswers: ["Oscar", "Oscar dos Santos", "Oscar dos Santos Emboaba"],
    difficulty: "Hard",
    clues: [
      "I am from Brazil.",
      "I was an attacking midfielder.",
      "I was known for technique and intelligent movement.",
      "I played for Internacional before moving to Europe.",
      "I joined Chelsea in 2012.",
      "I scored a famous goal against Juventus.",
      "I won the Premier League with Chelsea.",
      "I later moved to China while still in my prime.",
      "My name starts with O.",
      "I am Oscar.",
    ],
  },
  {
    id: "whoami_069",
    answer: "Ramires",
    acceptedAnswers: ["Ramires", "Ramires Santos"],
    difficulty: "Hard",
    clues: [
      "I am from Brazil.",
      "I was a very energetic midfielder.",
      "I was known for running, pressing and stamina.",
      "I played for Benfica before moving to England.",
      "I became important at Chelsea.",
      "I won the Champions League in 2012.",
      "I scored a famous chip against Barcelona.",
      "I represented Brazil internationally.",
      "My name starts with R.",
      "I am Ramires.",
    ],
  },
  {
    id: "whoami_070",
    answer: "Salomon Kalou",
    acceptedAnswers: ["Salomon Kalou", "Kalou"],
    difficulty: "Hard",
    clues: [
      "I am from Ivory Coast.",
      "I was a forward or winger.",
      "I played in the Netherlands before moving to England.",
      "I joined a big London club.",
      "I was often used as a squad player in attack.",
      "I won the Premier League.",
      "I won the Champions League in 2012.",
      "I played for Chelsea for several years.",
      "My initials are SK.",
      "I am Salomon Kalou.",
    ],
  },,  {
    id: "whoami_071",
    answer: "Henrikh Mkhitaryan",
    acceptedAnswers: ["Henrikh Mkhitaryan", "Mkhitaryan"],
    difficulty: "Hard",
    clues: [
      "I played for Manchester United.",
      "I was an attacking midfielder with very good movement.",
      "I was known for technique, intelligence and arriving in dangerous areas.",
      "I played in Ukraine before moving to a bigger European league.",
      "I became a star at Shakhtar Donetsk.",
      "I later played for Borussia Dortmund.",
      "I moved to Manchester United in the Premier League.",
      "I scored in the 2017 Europa League final.",
      "My surname is M....",
      "I am Henrikh Mkhitaryan.",
    ],
  },
  {
    id: "whoami_072",
    answer: "Arda Turan",
    acceptedAnswers: ["Arda Turan", "Arda", "Turan"],
    difficulty: "Hard",
    clues: [
      "I am from Turkey.",
      "I was a technical midfielder or winger.",
      "I was known for close control and aggression.",
      "I became a star in my home country first.",
      "I played for Galatasaray early in my career.",
      "I moved to Atletico Madrid.",
      "I won La Liga under Diego Simeone.",
      "I later joined Barcelona.",
      "My first name is A....",
      "I am Arda Turan.",
    ],
  },
  {
    id: "whoami_073",
    answer: "Samir Nasri",
    acceptedAnswers: ["Samir Nasri", "Nasri"],
    difficulty: "Hard",
    clues: [
      "I am from France.",
      "I was an attacking midfielder with excellent close control.",
      "I was often compared to older French creative midfielders.",
      "I started my career at Marseille.",
      "I moved to Arsenal in 2008.",
      "I later joined Manchester City.",
      "I won the Premier League in England.",
      "I was known for dribbling between lines.",
      "My surname is Na....",
      "I am Samir Nasri.",
    ],
  },
  {
    id: "whoami_074",
    answer: "Yoann Gourcuff",
    acceptedAnswers: ["Yoann Gourcuff", "Gourcuff"],
    difficulty: "Hard",
    clues: [
      "I am from France.",
      "I was an elegant attacking midfielder.",
      "I was known for technique and a smooth playing style.",
      "I played for Rennes early in my career.",
      "I moved to AC Milan as a young player.",
      "I became a star at Bordeaux.",
      "I won Ligue 1 with Bordeaux.",
      "I was once seen as a next Zidane.",
      "My surname is Gou....",
      "I am Yoann Gourcuff.",
    ],
  },
  {
    id: "whoami_075",
    answer: "Jeremy Menez",
    acceptedAnswers: ["Jeremy Menez", "Jérémy Ménez", "Menez", "Ménez"],
    difficulty: "Hard",
    clues: [
      "I am from France.",
      "I was an attacking player with flair.",
      "I was known for dribbling and unpredictable moments.",
      "I played for Monaco early in my career.",
      "I moved to Roma in Italy.",
      "I later played for Paris Saint-Germain.",
      "I also played for AC Milan.",
      "I scored a famous backheel goal in Serie A.",
      "My surname is M....",
      "I am Jeremy Menez.",
    ],
  },
  {
    id: "whoami_076",
    answer: "Blaise Matuidi",
    acceptedAnswers: ["Blaise Matuidi", "Matuidi"],
    difficulty: "Hard",
    clues: [
      "I am from France.",
      "I was a left-footed midfielder.",
      "I was known more for energy than flair.",
      "I covered huge distances in midfield.",
      "I played for Saint-Etienne before joining a bigger club.",
      "I became important at Paris Saint-Germain.",
      "I later played for Juventus.",
      "I won the 2018 World Cup with France.",
      "My surname is M....",
      "I am Blaise Matuidi.",
    ],
  },
  {
    id: "whoami_077",
    answer: "Lassana Diarra",
    acceptedAnswers: ["Lassana Diarra", "Lass Diarra", "Diarra"],
    difficulty: "Hard",
    clues: [
      "I am from France.",
      "I was a defensive midfielder.",
      "I was not very tall but was strong in duels.",
      "I played for multiple big European clubs.",
      "I played for Chelsea early in my career.",
      "I also played for Arsenal and Portsmouth.",
      "I moved to Real Madrid in 2009.",
      "I later played for Marseille and Paris Saint-Germain.",
      "My surname is Di...",
      "I am Lassana Diarra.",
    ],
  },
  {
    id: "whoami_078",
    answer: "Emmanuel Adebayor",
    acceptedAnswers: ["Emmanuel Adebayor", "Adebayor"],
    difficulty: "Hard",
    clues: [
      "I am from Togo.",
      "I was a tall striker.",
      "I was known for long legs, power and movement.",
      "I played in France before moving to England.",
      "I became famous at Arsenal.",
      "I later joined Manchester City.",
      "I also played for Real Madrid on loan.",
      "I scored against Arsenal and celebrated by running the length of the pitch.",
      "My surname is A...",
      "I am Emmanuel Adebayor.",
    ],
  },
  {
    id: "whoami_079",
    answer: "Peter Crouch",
    acceptedAnswers: ["Peter Crouch", "Crouch"],
    difficulty: "Hard",
    clues: [
      "I am from England.",
      "I was unusually tall for a striker.",
      "I was known for headers and a strange-looking elegance.",
      "I played for many English clubs.",
      "I played for Southampton and Portsmouth.",
      "I also played for Liverpool.",
      "I scored many Premier League goals.",
      "I was famous for a robot celebration.",
      "My surname is C....",
      "I am Peter Crouch.",
    ],
  },
  {
    id: "whoami_080",
    answer: "Mirko Vucinic",
    acceptedAnswers: ["Mirko Vucinic", "Vucinic", "Vučinić"],
    difficulty: "Hard",
    clues: [
      "I am from Montenegro.",
      "I was a forward with good technique.",
      "I could play as a striker or wide attacker.",
      "I spent many years in Italian football.",
      "I played for Lecce early in Serie A.",
      "I became important at Roma.",
      "I later joined Juventus.",
      "I won Serie A titles with Juventus.",
      "My surname is V.....",
      "I am Mirko Vucinic.",
    ],
  },
  {
    id: "whoami_081",
    answer: "Stevan Jovetic",
    acceptedAnswers: ["Stevan Jovetic", "Jovetic", "Jovetić"],
    difficulty: "Hard",
    clues: [
      "I am from Montenegro.",
      "I was a creative forward.",
      "I was known for technique and curly hair.",
      "I became famous in Serie A.",
      "I played for Fiorentina.",
      "I later moved to Manchester City.",
      "I also played for Inter.",
      "I represented Montenegro for many years.",
      "My surname is J....",
      "I am Stevan Jovetic.",
    ],
  },
  {
    id: "whoami_082",
    answer: "Alvaro Negredo",
    acceptedAnswers: ["Alvaro Negredo", "Álvaro Negredo", "Negredo"],
    difficulty: "Hard",
    clues: [
      "I am from Spain.",
      "I was a left-footed striker.",
      "I was strong and direct in the box.",
      "I played for several Spanish clubs.",
      "I became well known at Sevilla.",
      "I moved to Manchester City in 2013.",
      "I won the Premier League in England.",
      "I later returned to Spanish football.",
      "My surname is N....",
      "I am Alvaro Negredo.",
    ],
  },
  {
    id: "whoami_083",
    answer: "Roberto Soldado",
    acceptedAnswers: ["Roberto Soldado", "Soldado"],
    difficulty: "Hard",
    clues: [
      "I am from Spain.",
      "I was a striker.",
      "I was known for penalty-box finishing.",
      "I came through Real Madrid's system.",
      "I became more important at other Spanish clubs.",
      "I scored many goals for Valencia.",
      "I later joined Tottenham Hotspur.",
      "I also played for Villarreal.",
      "My surname is S.....",
      "I am Roberto Soldado.",
    ],
  },
  {
    id: "whoami_084",
    answer: "Christian Benteke",
    acceptedAnswers: ["Christian Benteke", "Benteke"],
    difficulty: "Hard",
    clues: [
      "I represent Belgium.",
      "I was born in DR Congo.",
      "I was a powerful striker.",
      "I was known for headers and physical play.",
      "I became a Premier League name at Aston Villa.",
      "I moved to Liverpool in 2015.",
      "I later played for Crystal Palace.",
      "I scored a famous overhead kick for Belgium.",
      "My surname is B....",
      "I am Christian Benteke.",
    ],
  },
  {
    id: "whoami_085",
    answer: "Michu",
    acceptedAnswers: ["Michu", "Miguel Perez Cuesta", "Miguel Pérez Cuesta"],
    difficulty: "Hard",
    clues: [
      "I am from Spain.",
      "I was an attacking midfielder or forward.",
      "I was tall and left-footed.",
      "I became famous later than many expected.",
      "I played for Rayo Vallecano.",
      "I moved to Swansea City.",
      "I had one incredible Premier League season.",
      "I helped Swansea win the League Cup.",
      "My football name has five letters.",
      "I am Michu.",
    ],
  },
  {
    id: "whoami_086",
    answer: "Michy Batshuayi",
    acceptedAnswers: ["Michy Batshuayi", "Batshuayi", "Michy"],
    difficulty: "Hard",
    clues: [
      "I represent Belgium.",
      "I was a striker with pace and power.",
      "I played in France before moving to England.",
      "I became known at Marseille.",
      "I joined Chelsea in 2016.",
      "I scored the goal that won Chelsea the Premier League in 2017.",
      "I also played for Borussia Dortmund on loan.",
      "I represented Belgium at major tournaments.",
      "My first name is Michy.",
      "I am Michy Batshuayi.",
    ],
  },
  {
    id: "whoami_087",
    answer: "Kevin Gameiro",
    acceptedAnswers: ["Kevin Gameiro", "Gameiro"],
    difficulty: "Hard",
    clues: [
      "I am from France.",
      "I was a quick striker.",
      "I was known for movement and finishing.",
      "I played for Lorient early in my career.",
      "I later joined Paris Saint-Germain.",
      "I became especially successful at Sevilla.",
      "I won the Europa League multiple times.",
      "I also played for Atletico Madrid.",
      "My surname is Ga...",
      "I am Kevin Gameiro.",
    ],
  },
  {
    id: "whoami_088",
    answer: "Fernando Llorente",
    acceptedAnswers: ["Fernando Llorente", "Llorente"],
    difficulty: "Hard",
    clues: [
      "I am from Spain.",
      "I was a very tall striker.",
      "I was known for headers and hold-up play.",
      "I became a star in the Basque Country.",
      "I played for Athletic Bilbao.",
      "I later joined Juventus.",
      "I also played for Tottenham Hotspur.",
      "I won the World Cup with Spain in 2010.",
      "My surname is L....",
      "I am Fernando Llorente.",
    ],
  },
  {
    id: "whoami_089",
    answer: "Iago Aspas",
    acceptedAnswers: ["Iago Aspas", "Aspas"],
    difficulty: "Hard",
    clues: [
      "I am from Spain.",
      "I am a left-footed forward.",
      "I was known for clever movement and finishing.",
      "I became strongly connected with one Spanish club.",
      "I played for Celta Vigo.",
      "I had a difficult spell at Liverpool.",
      "I returned to Spain and became a La Liga star again.",
      "I represented Spain at the 2018 World Cup.",
      "My surname is A...",
      "I am Iago Aspas.",
    ],
  },
  {
    id: "whoami_090",
    answer: "Aritz Aduriz",
    acceptedAnswers: ["Aritz Aduriz", "Aduriz"],
    difficulty: "Hard",
    clues: [
      "I am from Spain.",
      "I was a striker who aged very well.",
      "I was known for heading, timing and toughness.",
      "I played for several Spanish clubs.",
      "I became a legend in the Basque Country.",
      "I played for Athletic Bilbao.",
      "I scored many goals in La Liga after turning 30.",
      "I scored a famous scissor-kick goal against Barcelona.",
      "My surname is Ad...",
      "I am Aritz Aduriz.",
    ],
  },  {
    id: "whoami_091",
    answer: "Mesut Ozil",
    acceptedAnswers: ["Mesut Ozil", "Mesut Özil", "Ozil", "Özil"],
    difficulty: "Medium",
    clues: [
      "I am from Germany.",
      "I was a left-footed attacking midfielder.",
      "I was known more for vision than physical power.",
      "I had a calm and elegant playing style.",
      "I played in Germany before moving to Spain.",
      "I later became a star in North London.",
      "I won the World Cup in 2014.",
      "I wore number 10 for Arsenal.",
      "My surname is O.....",
      "I am Mesut Ozil.",
    ],
  },
  {
    id: "whoami_092",
    answer: "Angel Di Maria",
    acceptedAnswers: ["Angel Di Maria", "Ángel Di María", "Di Maria", "Di María"],
    difficulty: "Medium",
    clues: [
      "I am from Argentina.",
      "I am a left-footed wide player.",
      "I was known for speed, crossing and big-game moments.",
      "I played in Portugal before moving to Spain.",
      "I became important at Real Madrid.",
      "I later played in England and France.",
      "I scored in the 2022 World Cup final.",
      "I won the Champions League with Real Madrid.",
      "My surname is D....",
      "I am Angel Di Maria.",
    ],
  },
  {
    id: "whoami_093",
    answer: "James Rodriguez",
    acceptedAnswers: ["James Rodriguez", "James Rodríguez", "James"],
    difficulty: "Medium",
    clues: [
      "I am from Colombia.",
      "I am a left-footed attacking midfielder.",
      "I became famous for technique and shooting.",
      "I played in Portugal and France before moving to Spain.",
      "I had a breakout tournament in 2014.",
      "I won the Golden Boot at the 2014 World Cup.",
      "I scored a famous volley against Uruguay.",
      "I later played for Real Madrid and Bayern Munich.",
      "My first name is Ja....",
      "I am James Rodriguez.",
    ],
  },
  {
    id: "whoami_094",
    answer: "Isco",
    acceptedAnswers: ["Isco", "Francisco Roman Alarcon", "Francisco Román Alarcón"],
    difficulty: "Hard",
    clues: [
      "I am from Spain.",
      "I was an attacking midfielder with excellent close control.",
      "I was known for turning away from pressure.",
      "I became famous in southern Spain.",
      "I played for Malaga before moving to a bigger club.",
      "I joined Real Madrid in 2013.",
      "I won multiple Champions League titles.",
      "I also represented Spain internationally.",
      "My football name has four letters.",
      "I am Isco.",
    ],
  },
  {
    id: "whoami_095",
    answer: "Juan Mata",
    acceptedAnswers: ["Juan Mata", "Mata"],
    difficulty: "Medium",
    clues: [
      "I am from Spain.",
      "I was a left-footed attacking midfielder.",
      "I was known for intelligence and final passes.",
      "I played in Spain before moving to England.",
      "I became very popular at Chelsea.",
      "I later joined Manchester United.",
      "I won the Champions League in 2012.",
      "I won the World Cup with Spain in 2010.",
      "My surname is M....",
      "I am Juan Mata.",
    ],
  },
  {
    id: "whoami_096",
    answer: "Cesc Fabregas",
    acceptedAnswers: ["Cesc Fabregas", "Cesc Fàbregas", "Fabregas", "Fàbregas"],
    difficulty: "Medium",
    clues: [
      "I am from Spain.",
      "I was a central midfielder with great passing range.",
      "I left my home country at a young age.",
      "I became a captain in England while still young.",
      "I later returned to Barcelona.",
      "I also played for Chelsea.",
      "I won the Premier League in England.",
      "I won the World Cup and European Championship with Spain.",
      "My surname is Fa....",
      "I am Cesc Fabregas.",
    ],
  },
  {
    id: "whoami_097",
    answer: "David Silva",
    acceptedAnswers: ["David Silva", "Silva"],
    difficulty: "Medium",
    clues: [
      "I am from Spain.",
      "I was a small left-footed midfielder.",
      "I was known for balance, passing and calmness.",
      "I played in Spain before moving to England.",
      "I became a legend at a club wearing sky blue.",
      "I won multiple Premier League titles.",
      "I was part of Spain's golden generation.",
      "I won the World Cup in 2010.",
      "My surname is S....",
      "I am David Silva.",
    ],
  },
  {
    id: "whoami_098",
    answer: "David Villa",
    acceptedAnswers: ["David Villa", "Villa"],
    difficulty: "Medium",
    clues: [
      "I am from Spain.",
      "I was a striker who could also play wide.",
      "I was known for sharp finishing with both feet.",
      "I played for Valencia for several years.",
      "I later joined Barcelona.",
      "I scored in the 2011 Champions League final.",
      "I won the World Cup in 2010.",
      "I became Spain's all-time top scorer.",
      "My surname is V....",
      "I am David Villa.",
    ],
  },
  {
    id: "whoami_099",
    answer: "Fernando Torres",
    acceptedAnswers: ["Fernando Torres", "Torres", "El Nino", "El Niño"],
    difficulty: "Medium",
    clues: [
      "I am from Spain.",
      "I was a fast striker.",
      "I had blond hair for much of my career.",
      "I became a captain at a young age in Spain.",
      "I moved to Liverpool and became a star.",
      "I later played for Chelsea.",
      "I scored in a Champions League semi-final at Camp Nou.",
      "I scored the winning goal in the Euro 2008 final.",
      "My nickname was El Nino.",
      "I am Fernando Torres.",
    ],
  },
  {
    id: "whoami_100",
    answer: "Mario Balotelli",
    acceptedAnswers: ["Mario Balotelli", "Balotelli"],
    difficulty: "Hard",
    clues: [
      "I am from Italy.",
      "I was a powerful striker.",
      "I was known for talent and controversy.",
      "I played for both Milan clubs.",
      "I also played in England.",
      "I won the Premier League with Manchester City.",
      "I scored twice against Germany at Euro 2012.",
      "I had the famous 'Why Always Me?' celebration.",
      "My surname is B....",
      "I am Mario Balotelli.",
    ],
  },
  {
    id: "whoami_101",
    answer: "Ciro Immobile",
    acceptedAnswers: ["Ciro Immobile", "Immobile"],
    difficulty: "Hard",
    clues: [
      "I am from Italy.",
      "I was a striker known for movement and finishing.",
      "I played for several Italian clubs.",
      "I had spells in Germany and Spain.",
      "I became most famous in Rome.",
      "I scored many goals for Lazio.",
      "I won the European Championship with Italy in 2021.",
      "I won the European Golden Shoe in 2020.",
      "My surname is I....",
      "I am Ciro Immobile.",
    ],
  },
  {
    id: "whoami_102",
    answer: "Lorenzo Insigne",
    acceptedAnswers: ["Lorenzo Insigne", "Insigne"],
    difficulty: "Hard",
    clues: [
      "I am from Italy.",
      "I was a small and technical winger.",
      "I was known for curling shots from the left side.",
      "I became strongly connected with southern Italy.",
      "I spent many years at Napoli.",
      "I often played from the left wing.",
      "I won Euro 2020 with Italy.",
      "I later moved to Toronto FC.",
      "My surname is I....",
      "I am Lorenzo Insigne.",
    ],
  },
  {
    id: "whoami_103",
    answer: "Federico Chiesa",
    acceptedAnswers: ["Federico Chiesa", "Chiesa"],
    difficulty: "Medium",
    clues: [
      "I am from Italy.",
      "I am a fast wide attacker.",
      "I am the son of a former professional footballer.",
      "I became known for direct dribbling and energy.",
      "I played for Fiorentina early in my career.",
      "I later joined Juventus.",
      "I was one of Italy's key players at Euro 2020.",
      "I scored important goals during that tournament.",
      "My surname is C....",
      "I am Federico Chiesa.",
    ],
  },
  {
    id: "whoami_104",
    answer: "Dries Mertens",
    acceptedAnswers: ["Dries Mertens", "Mertens"],
    difficulty: "Hard",
    clues: [
      "I am from Belgium.",
      "I was a small attacking player.",
      "I was known for quick feet and clever finishing.",
      "I played in the Netherlands before moving to Italy.",
      "I joined Napoli in 2013.",
      "I became one of Napoli's greatest modern goalscorers.",
      "I often played as a false nine.",
      "I represented Belgium's golden generation.",
      "My surname is M....",
      "I am Dries Mertens.",
    ],
  },
  {
    id: "whoami_105",
    answer: "Mousa Dembele",
    acceptedAnswers: ["Mousa Dembele", "Mousa Dembélé", "Dembele", "Dembélé"],
    difficulty: "Hard",
    clues: [
      "I am from Belgium.",
      "I was a midfielder with incredible strength on the ball.",
      "I was known for dribbling through pressure.",
      "I played in the Netherlands before moving to England.",
      "I played for Fulham.",
      "I later became important at Tottenham Hotspur.",
      "I was admired by many teammates for my technical level.",
      "I represented Belgium internationally.",
      "My surname is D.....",
      "I am Mousa Dembele.",
    ],
  },
  {
    id: "whoami_106",
    answer: "Marouane Fellaini",
    acceptedAnswers: ["Marouane Fellaini", "Fellaini"],
    difficulty: "Hard",
    clues: [
      "I am from Belgium.",
      "I was a tall midfielder.",
      "I was known for chest control and aerial duels.",
      "I had a very recognizable hairstyle.",
      "I played for Standard Liege before moving to England.",
      "I became important at Everton.",
      "I later joined Manchester United.",
      "I was often used as a physical Plan B.",
      "My surname is F....",
      "I am Marouane Fellaini.",
    ],
  },
  {
    id: "whoami_107",
    answer: "Hulk",
    acceptedAnswers: ["Hulk", "Givanildo Vieira de Sousa"],
    difficulty: "Hard",
    clues: [
      "I am from Brazil.",
      "I was a powerful left-footed attacker.",
      "I was known for strength and extremely hard shots.",
      "I played in Japan early in my career.",
      "I became famous at Porto.",
      "I later moved to Zenit Saint Petersburg.",
      "I represented Brazil internationally.",
      "My football name is also a comic-book character.",
      "My name has four letters.",
      "I am Hulk.",
    ],
  },
  {
    id: "whoami_108",
    answer: "Willian",
    acceptedAnswers: ["Willian", "Willian Borges da Silva"],
    difficulty: "Hard",
    clues: [
      "I am from Brazil.",
      "I was a right-footed winger.",
      "I was known for work rate, dribbling and set pieces.",
      "I played in Ukraine before moving to England.",
      "I became a key player at Chelsea.",
      "I won Premier League titles in England.",
      "I later played for Arsenal.",
      "I also returned to Brazil late in my career.",
      "My football name has seven letters.",
      "I am Willian.",
    ],
  },
  {
    id: "whoami_109",
    answer: "Douglas Costa",
    acceptedAnswers: ["Douglas Costa", "Costa"],
    difficulty: "Hard",
    clues: [
      "I am from Brazil.",
      "I was a very quick winger.",
      "I was known for acceleration and left-footed dribbling.",
      "I played in Ukraine before moving to Germany.",
      "I joined Bayern Munich.",
      "I later played for Juventus.",
      "I represented Brazil internationally.",
      "Injuries stopped me from becoming even bigger.",
      "My surname is Costa.",
      "I am Douglas Costa.",
    ],
  },
  {
    id: "whoami_110",
    answer: "Luis Fabiano",
    acceptedAnswers: ["Luis Fabiano", "Luís Fabiano", "Fabiano"],
    difficulty: "Hard",
    clues: [
      "I am from Brazil.",
      "I was a striker.",
      "I was known for aggression and finishing.",
      "I played in Portugal but became bigger in Spain.",
      "I had a long and successful spell at Sevilla.",
      "I won the UEFA Cup with Sevilla.",
      "I represented Brazil at the 2010 World Cup.",
      "I scored many goals for Brazil.",
      "My surname is Fab....",
      "I am Luis Fabiano.",
    ],
  },
  

];
